package vision_test

// The expected pictures of the cave, from cave.py (the Etapa 9 artboards,
// cave-data.md): B bright, d dim, g seen in grey (darkvision), # a wall seen,
// @ the viewer's own square, a space unseen. Its lines are sampled; the
// functions here walk them exactly, and agree with it on every square.
var caveVision = map[string][]string{
	"pensantus": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"########               #",
		"#gggggg#########   BBBB#",
		"gggggggggggggggBBBBBBBd#",
		"ggggg@ggggggggBBBBdBddd#",
		"#gggggg#  ######       #",
		"#gggggg#                ",
		"######g                 ",
		"     #gg                ",
		"     #ggg               ",
		"     # gg               ",
		"      ####              ",
	},
	"toren": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"       #      ##       #",
		"      @        ddBBBBBd#",
		"              dddddBddd#",
		"             ###   dddd#",
		"                  ######",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
	},
	"brisa": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"              ##       #",
		"    @          ddBBBBBd#",
		"              dddddBddd#",
		"             ###    ddd#",
		"                   #####",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
	},
	"salvia": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"########               #",
		"#gggggg#########    BBB#",
		"gggggggggggggggddBBBBBd#",
		"ggg@ggggggggggBBdddBddd#",
		"#gggggg#  ######       #",
		"#gggggg#                ",
		"######gg                ",
		"     # gg               ",
		"        ggg             ",
		"         ggg            ",
		"        #####           ",
	},
	"salvia-lobo": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                       #",
		"              ##    BBB#",
		"               ddBBBBBd#",
		"   @          dddddBddd#",
		"             ###       #",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
	},
	"toren-tocha": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"########                ",
		"#ddBBBB#########       #",
		"ddBBBB@BBBBddddddBBBBBd#",
		"dddBBBBBBBdddddddddBddd#",
		"#ddBBBB#BB######   dddd#",
		"#dddBBB# d##      ######",
		"######B   d             ",
		"     #d    d            ",
		"     #d                 ",
		"     #dd                ",
		"     ####               ",
	},
	"brisa-tocha": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"########                ",
		"#ddBBBB#########       #",
		"ddBB@BBBBBBddddddBBBBBd#",
		"dddBBBBBBBdddddddddBddd#",
		"#ddBBBB# B######    ddd#",
		"#dddBBB#  #        #####",
		"######B                 ",
		"     #                  ",
		"                        ",
		"       d                ",
		"      ###               ",
	},
	"pensantus-tocha": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"########               #",
		"#BBBBBB#########   BBBB#",
		"BBBBBBBBBBBBBBBBBBBBBBd#",
		"BBBBB@BBBBBBBBBBBBdBddd#",
		"#BBBBBB#  ######       #",
		"#BBBBBB#                ",
		"######B                 ",
		"     #Bg                ",
		"     #Bgg               ",
		"     # Bg               ",
		"      ####              ",
	},
	"salvia-tocha": {
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"                        ",
		"########               #",
		"#BBBBBB#########    BBB#",
		"BBBBBBBBBBBBBBBddBBBBBd#",
		"BBB@BBBBBBBBBBBBdddBddd#",
		"#BBBBBB#  ######       #",
		"#BBBBBB#                ",
		"######Bg                ",
		"     # gg               ",
		"        ggg             ",
		"         ggg            ",
		"        #####           ",
	},
}
