// Package rules is the fifth edition (2014) rules engine: it turns a character's
// choices (a Build) into the numbers of the sheet (Derived), from rules
// content that is data, not code (ADR-0008).
//
// The package is pure. It never touches a database, the network, the clock
// or randomness: the same Build and Content always give the same Derived.
// That makes every rule a fast table test (derive_test.go), and lets the
// characters module call Derive on every read.
//
// Content comes from two places, embedded in the binary (package srd51):
//
//   - data/: the SRD 5.1 snapshot, generated by cmd/srdimport from
//     5e-database at a pinned commit. Never edited by hand.
//   - effects/: what the SRD only says in prose, written by hand as
//     structured effects (modifier, proficiency, roll_mode, sense,
//     spellcasting, resource, choice, grant_action, note, handler), plus
//     our Portuguese names. Formulas in effects run on Expr, locked down by
//     package formula.
//
// Derive never fails: an unknown key, an unusual choice or a formula that
// breaks becomes an Issue on the sheet, and the rest is still computed ("o
// app é um assistente, não um juiz"). Validate is the strict part, run only
// on writes.
package rules
