-- +goose Up
-- The session events of Etapa 9 (ADR-0007), all in one migration so that the
-- Etapa 9 slices built at the same time never rewrite each other's CHECK:
-- traps (noticed, searched, triggered, disarmed, revealed; MR-035), treasure
-- (found and unmarked; MR-041), cover and sides in a combat (cover_set,
-- side_set; MR-034), the opportunity attack the server offers (MR-034, RN-21),
-- the character's creatures and Wild Shape (MR-037) and seeing through a
-- familiar's eyes (MR-036). Their payloads hold IDs and results only. The
-- CHECK lists every kind of the history (see 00083): dropped, if present, and
-- added again, so re-running this migration is safe.
ALTER TABLE session_events
    DROP CONSTRAINT IF EXISTS session_events_kind_valid,
    ADD CONSTRAINT session_events_kind_valid CHECK (kind IN (
        'character_vitals_adjusted',
        'encounter_started',
        'initiative_submitted',
        'initiative_order_set',
        'combat_begun',
        'turn_ended',
        'combatant_moved',
        'combatant_hidden_set',
        'combatants_added',
        'combatant_removed',
        'encounter_ended',
        'attack_rolled',
        'damage_rolled',
        'damage_applied',
        'damage_discarded',
        'action_taken',
        'hit_points_adjusted',
        'action_undone',
        'spell_cast',
        'reaction_used',
        'reaction_declined',
        'death_save_rolled',
        'death_confirmed',
        'conditions_set',
        'xp_awarded',
        'xp_award_undone',
        'milestone_marked',
        'scene_opened',
        'scene_closed',
        'scene_check_rolled',
        'clue_revealed',
        'stage_changed',
        'scene_attempt_granted',
        'turn_part_ended',
        'trap_noticed',
        'trap_searched',
        'trap_triggered',
        'trap_disarmed',
        'trap_revealed',
        'treasure_found',
        'treasure_unfound',
        'cover_set',
        'side_set',
        'opportunity_offered',
        'creature_summoned',
        'creature_dismissed',
        'wild_shape_started',
        'wild_shape_ended',
        'familiar_sight'
    ));

-- +goose Down
DELETE FROM session_events WHERE kind IN ('trap_noticed', 'trap_searched', 'trap_triggered', 'trap_disarmed', 'trap_revealed', 'treasure_found', 'treasure_unfound', 'cover_set', 'side_set', 'opportunity_offered', 'creature_summoned', 'creature_dismissed', 'wild_shape_started', 'wild_shape_ended', 'familiar_sight');

ALTER TABLE session_events
    DROP CONSTRAINT IF EXISTS session_events_kind_valid,
    ADD CONSTRAINT session_events_kind_valid CHECK (kind IN (
        'character_vitals_adjusted',
        'encounter_started',
        'initiative_submitted',
        'initiative_order_set',
        'combat_begun',
        'turn_ended',
        'combatant_moved',
        'combatant_hidden_set',
        'combatants_added',
        'combatant_removed',
        'encounter_ended',
        'attack_rolled',
        'damage_rolled',
        'damage_applied',
        'damage_discarded',
        'action_taken',
        'hit_points_adjusted',
        'action_undone',
        'spell_cast',
        'reaction_used',
        'reaction_declined',
        'death_save_rolled',
        'death_confirmed',
        'conditions_set',
        'xp_awarded',
        'xp_award_undone',
        'milestone_marked',
        'scene_opened',
        'scene_closed',
        'scene_check_rolled',
        'clue_revealed',
        'stage_changed',
        'scene_attempt_granted',
        'turn_part_ended'
    ));
