-- +goose Up
-- The session event of a door a move opened (MR-010, RN-26, ADR-0007): a
-- `door_opened` event is written in the move's transaction, before the move's
-- own event, and holds IDs and squares only. It is its own event, and not a part
-- of the move's, because the master's undo takes the move back but not the door
-- (a door opened stays opened), so the line of the combat log stays. The CHECK
-- lists every kind of the history (see 00090): dropped, if present, and added
-- again, so re-running this migration is safe.
ALTER TABLE session_events
    DROP CONSTRAINT IF EXISTS session_events_kind_valid,
    ADD CONSTRAINT session_events_kind_valid CHECK (kind IN (
        'character_vitals_adjusted',
        'encounter_started',
        'initiative_submitted',
        'initiative_order_set',
        'combat_begun',
        'turn_ended',
        'combatant_moved',
        'combatant_hidden_set',
        'combatants_added',
        'combatant_removed',
        'encounter_ended',
        'attack_rolled',
        'damage_rolled',
        'damage_applied',
        'damage_discarded',
        'action_taken',
        'hit_points_adjusted',
        'action_undone',
        'spell_cast',
        'reaction_used',
        'reaction_declined',
        'death_save_rolled',
        'death_confirmed',
        'conditions_set',
        'xp_awarded',
        'xp_award_undone',
        'milestone_marked',
        'scene_opened',
        'scene_closed',
        'scene_check_rolled',
        'clue_revealed',
        'stage_changed',
        'scene_attempt_granted',
        'turn_part_ended',
        'trap_noticed',
        'trap_searched',
        'trap_triggered',
        'trap_disarmed',
        'trap_revealed',
        'treasure_found',
        'treasure_unfound',
        'cover_set',
        'side_set',
        'opportunity_offered',
        'creature_summoned',
        'creature_dismissed',
        'wild_shape_started',
        'wild_shape_ended',
        'familiar_sight',
        'door_opened'
    ));

-- +goose Down
DELETE FROM session_events WHERE kind = 'door_opened';

ALTER TABLE session_events
    DROP CONSTRAINT IF EXISTS session_events_kind_valid,
    ADD CONSTRAINT session_events_kind_valid CHECK (kind IN (
        'character_vitals_adjusted',
        'encounter_started',
        'initiative_submitted',
        'initiative_order_set',
        'combat_begun',
        'turn_ended',
        'combatant_moved',
        'combatant_hidden_set',
        'combatants_added',
        'combatant_removed',
        'encounter_ended',
        'attack_rolled',
        'damage_rolled',
        'damage_applied',
        'damage_discarded',
        'action_taken',
        'hit_points_adjusted',
        'action_undone',
        'spell_cast',
        'reaction_used',
        'reaction_declined',
        'death_save_rolled',
        'death_confirmed',
        'conditions_set',
        'xp_awarded',
        'xp_award_undone',
        'milestone_marked',
        'scene_opened',
        'scene_closed',
        'scene_check_rolled',
        'clue_revealed',
        'stage_changed',
        'scene_attempt_granted',
        'turn_part_ended',
        'trap_noticed',
        'trap_searched',
        'trap_triggered',
        'trap_disarmed',
        'trap_revealed',
        'treasure_found',
        'treasure_unfound',
        'cover_set',
        'side_set',
        'opportunity_offered',
        'creature_summoned',
        'creature_dismissed',
        'wild_shape_started',
        'wild_shape_ended',
        'familiar_sight'
    ));
