-- +goose Up
-- The session events of a puzzle (MR-038, RN-27, ADR-0007): the master showed it
-- (`puzzle_shown`), the players solved it (`puzzle_solved`), the master put it back
-- at its start (`puzzle_reset`, also for a new start) or hid it (`puzzle_closed`).
-- Each holds IDs only (the puzzle, the run, the character that solved it, what the
-- "Ao resolver" action did): never the solution or the state. The moves are not
-- events: they live in puzzle_moves. The CHECK lists every kind of the history (see
-- 00090 and 00121): dropped, if present, and added again, so re-running this
-- migration is safe.
ALTER TABLE session_events
    DROP CONSTRAINT IF EXISTS session_events_kind_valid,
    ADD CONSTRAINT session_events_kind_valid CHECK (kind IN (
        'character_vitals_adjusted',
        'encounter_started',
        'initiative_submitted',
        'initiative_order_set',
        'combat_begun',
        'turn_ended',
        'combatant_moved',
        'combatant_hidden_set',
        'combatants_added',
        'combatant_removed',
        'encounter_ended',
        'attack_rolled',
        'damage_rolled',
        'damage_applied',
        'damage_discarded',
        'action_taken',
        'hit_points_adjusted',
        'action_undone',
        'spell_cast',
        'reaction_used',
        'reaction_declined',
        'death_save_rolled',
        'death_confirmed',
        'conditions_set',
        'xp_awarded',
        'xp_award_undone',
        'milestone_marked',
        'scene_opened',
        'scene_closed',
        'scene_check_rolled',
        'clue_revealed',
        'stage_changed',
        'scene_attempt_granted',
        'turn_part_ended',
        'trap_noticed',
        'trap_searched',
        'trap_triggered',
        'trap_disarmed',
        'trap_revealed',
        'treasure_found',
        'treasure_unfound',
        'cover_set',
        'side_set',
        'opportunity_offered',
        'creature_summoned',
        'creature_dismissed',
        'wild_shape_started',
        'wild_shape_ended',
        'familiar_sight',
        'door_opened',
        'puzzle_shown',
        'puzzle_solved',
        'puzzle_reset',
        'puzzle_closed'
    ));

-- +goose Down
DELETE FROM session_events WHERE kind IN ('puzzle_shown', 'puzzle_solved', 'puzzle_reset', 'puzzle_closed');

ALTER TABLE session_events
    DROP CONSTRAINT IF EXISTS session_events_kind_valid,
    ADD CONSTRAINT session_events_kind_valid CHECK (kind IN (
        'character_vitals_adjusted',
        'encounter_started',
        'initiative_submitted',
        'initiative_order_set',
        'combat_begun',
        'turn_ended',
        'combatant_moved',
        'combatant_hidden_set',
        'combatants_added',
        'combatant_removed',
        'encounter_ended',
        'attack_rolled',
        'damage_rolled',
        'damage_applied',
        'damage_discarded',
        'action_taken',
        'hit_points_adjusted',
        'action_undone',
        'spell_cast',
        'reaction_used',
        'reaction_declined',
        'death_save_rolled',
        'death_confirmed',
        'conditions_set',
        'xp_awarded',
        'xp_award_undone',
        'milestone_marked',
        'scene_opened',
        'scene_closed',
        'scene_check_rolled',
        'clue_revealed',
        'stage_changed',
        'scene_attempt_granted',
        'turn_part_ended',
        'trap_noticed',
        'trap_searched',
        'trap_triggered',
        'trap_disarmed',
        'trap_revealed',
        'treasure_found',
        'treasure_unfound',
        'cover_set',
        'side_set',
        'opportunity_offered',
        'creature_summoned',
        'creature_dismissed',
        'wild_shape_started',
        'wild_shape_ended',
        'familiar_sight',
        'door_opened'
    ));
