// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package packagedb

import (
	"time"
)

type CampaignExport struct {
	ID          string
	CampaignID  string
	RequestedBy string
	State       string
	Percent     int32
	Failure     string
	FileName    string
	BlobKey     string
	ByteSize    int64
	EntryCount  int32
	CreateKey   *string
	CreateHash  *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FinishedAt  *time.Time
	ExpiresAt   time.Time
}

type CampaignImport struct {
	ID          string
	UserID      string
	FileName    string
	Fingerprint string
	TotalBytes  int64
	PartSize    int32
	PartCount   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ExpiresAt   time.Time
}

type CampaignImportPart struct {
	ImportID   string
	PartNumber int32
	ByteSize   int32
	CreatedAt  time.Time
}
