// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package packagedb

import (
	"context"
	"time"
)

const cancelCampaignExport = `-- name: CancelCampaignExport :one
UPDATE campaign_exports
SET state = 'canceled', updated_at = $2, finished_at = $2, expires_at = $3
WHERE id = $1 AND state = 'running'
RETURNING id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at
`

type CancelCampaignExportParams struct {
	ID        string
	UpdatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CancelCampaignExport(ctx context.Context, arg CancelCampaignExportParams) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, cancelCampaignExport, arg.ID, arg.UpdatedAt, arg.ExpiresAt)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteCampaignExport = `-- name: DeleteCampaignExport :exec
DELETE FROM campaign_exports WHERE id = $1
`

func (q *Queries) DeleteCampaignExport(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCampaignExport, id)
	return err
}

const deleteCampaignExportsOfCampaign = `-- name: DeleteCampaignExportsOfCampaign :exec
DELETE FROM campaign_exports WHERE campaign_id = $1
`

func (q *Queries) DeleteCampaignExportsOfCampaign(ctx context.Context, campaignID string) error {
	_, err := q.db.Exec(ctx, deleteCampaignExportsOfCampaign, campaignID)
	return err
}

const deleteCampaignExportsOfUser = `-- name: DeleteCampaignExportsOfUser :exec
DELETE FROM campaign_exports WHERE requested_by = $1
`

func (q *Queries) DeleteCampaignExportsOfUser(ctx context.Context, requestedBy string) error {
	_, err := q.db.Exec(ctx, deleteCampaignExportsOfUser, requestedBy)
	return err
}

const deleteCampaignImport = `-- name: DeleteCampaignImport :exec
DELETE FROM campaign_imports WHERE id = $1
`

// The parts' rows go with it (ON DELETE CASCADE).
func (q *Queries) DeleteCampaignImport(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCampaignImport, id)
	return err
}

const failCampaignExport = `-- name: FailCampaignExport :one
UPDATE campaign_exports
SET state = 'failed', failure = $2, updated_at = $3, finished_at = $3, expires_at = $4
WHERE id = $1 AND state = 'running'
RETURNING id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at
`

type FailCampaignExportParams struct {
	ID        string
	Failure   string
	UpdatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) FailCampaignExport(ctx context.Context, arg FailCampaignExportParams) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, failCampaignExport,
		arg.ID,
		arg.Failure,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const failStaleCampaignExports = `-- name: FailStaleCampaignExports :execrows
UPDATE campaign_exports
SET state = 'failed', failure = 'interrupted', updated_at = $1, finished_at = $1, expires_at = $2
WHERE state = 'running' AND updated_at < $3
`

type FailStaleCampaignExportsParams struct {
	Now         time.Time
	ExpiresAt   time.Time
	StaleBefore time.Time
}

// A run that has not moved for a while was cut off by a restart: it will not finish.
func (q *Queries) FailStaleCampaignExports(ctx context.Context, arg FailStaleCampaignExportsParams) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleCampaignExports, arg.Now, arg.ExpiresAt, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishCampaignExport = `-- name: FinishCampaignExport :one
UPDATE campaign_exports
SET state = 'done', percent = 100, file_name = $2, blob_key = $3, byte_size = $4, entry_count = $5,
    updated_at = $6, finished_at = $6, expires_at = $7
WHERE id = $1 AND state = 'running'
RETURNING id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at
`

type FinishCampaignExportParams struct {
	ID         string
	FileName   string
	BlobKey    string
	ByteSize   int64
	EntryCount int32
	UpdatedAt  time.Time
	ExpiresAt  time.Time
}

// The zip is in the store: the file lives until expires_at.
func (q *Queries) FinishCampaignExport(ctx context.Context, arg FinishCampaignExportParams) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, finishCampaignExport,
		arg.ID,
		arg.FileName,
		arg.BlobKey,
		arg.ByteSize,
		arg.EntryCount,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCampaignExport = `-- name: GetCampaignExport :one
SELECT id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at FROM campaign_exports WHERE id = $1
`

func (q *Queries) GetCampaignExport(ctx context.Context, id string) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, getCampaignExport, id)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCampaignExportByCreateKey = `-- name: GetCampaignExportByCreateKey :one
SELECT id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at FROM campaign_exports WHERE create_key = $1
`

func (q *Queries) GetCampaignExportByCreateKey(ctx context.Context, createKey *string) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, getCampaignExportByCreateKey, createKey)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCampaignExportForUpdate = `-- name: GetCampaignExportForUpdate :one
SELECT id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at FROM campaign_exports WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCampaignExportForUpdate(ctx context.Context, id string) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, getCampaignExportForUpdate, id)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCampaignImport = `-- name: GetCampaignImport :one
SELECT id, user_id, file_name, fingerprint, total_bytes, part_size, part_count, created_at, updated_at, expires_at FROM campaign_imports WHERE id = $1
`

func (q *Queries) GetCampaignImport(ctx context.Context, id string) (CampaignImport, error) {
	row := q.db.QueryRow(ctx, getCampaignImport, id)
	var i CampaignImport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.Fingerprint,
		&i.TotalBytes,
		&i.PartSize,
		&i.PartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCampaignImportOfUser = `-- name: GetCampaignImportOfUser :one
SELECT id, user_id, file_name, fingerprint, total_bytes, part_size, part_count, created_at, updated_at, expires_at FROM campaign_imports WHERE user_id = $1
`

func (q *Queries) GetCampaignImportOfUser(ctx context.Context, userID string) (CampaignImport, error) {
	row := q.db.QueryRow(ctx, getCampaignImportOfUser, userID)
	var i CampaignImport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.Fingerprint,
		&i.TotalBytes,
		&i.PartSize,
		&i.PartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLatestCampaignExport = `-- name: GetLatestCampaignExport :one
SELECT id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at FROM campaign_exports
WHERE campaign_id = $1 AND expires_at > $2
ORDER BY created_at DESC, id
LIMIT 1
`

type GetLatestCampaignExportParams struct {
	CampaignID string
	Now        time.Time
}

// The campaign's latest export that has not expired.
func (q *Queries) GetLatestCampaignExport(ctx context.Context, arg GetLatestCampaignExportParams) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, getLatestCampaignExport, arg.CampaignID, arg.Now)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRunningCampaignExport = `-- name: GetRunningCampaignExport :one
SELECT id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at FROM campaign_exports
WHERE campaign_id = $1 AND state = 'running'
ORDER BY created_at DESC, id
LIMIT 1
`

func (q *Queries) GetRunningCampaignExport(ctx context.Context, campaignID string) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, getRunningCampaignExport, campaignID)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertCampaignExport = `-- name: InsertCampaignExport :one

INSERT INTO campaign_exports (id, campaign_id, requested_by, state, create_key, create_hash, created_at, updated_at, expires_at)
VALUES ($1, $2, $3, 'running', $4, $5, $6, $6, $7)
ON CONFLICT (create_key) WHERE create_key IS NOT NULL DO NOTHING
RETURNING id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at
`

type InsertCampaignExportParams struct {
	ID          string
	CampaignID  string
	RequestedBy string
	CreateKey   *string
	CreateHash  *string
	Now         time.Time
	ExpiresAt   time.Time
}

// The campaign package's own tables: the exports and the uploads in progress
// (MR-050). What a package carries belongs to the other modules' tables, which
// their own queries read and write.
// A new export, running. create_key and create_hash are the idempotency key of
// StartCampaignExport; a retry with the same key reads the first export
// (GetCampaignExportByCreateKey).
func (q *Queries) InsertCampaignExport(ctx context.Context, arg InsertCampaignExportParams) (CampaignExport, error) {
	row := q.db.QueryRow(ctx, insertCampaignExport,
		arg.ID,
		arg.CampaignID,
		arg.RequestedBy,
		arg.CreateKey,
		arg.CreateHash,
		arg.Now,
		arg.ExpiresAt,
	)
	var i CampaignExport
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RequestedBy,
		&i.State,
		&i.Percent,
		&i.Failure,
		&i.FileName,
		&i.BlobKey,
		&i.ByteSize,
		&i.EntryCount,
		&i.CreateKey,
		&i.CreateHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertCampaignImport = `-- name: InsertCampaignImport :one
INSERT INTO campaign_imports (id, user_id, file_name, fingerprint, total_bytes, part_size, part_count, created_at, updated_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8, $9)
RETURNING id, user_id, file_name, fingerprint, total_bytes, part_size, part_count, created_at, updated_at, expires_at
`

type InsertCampaignImportParams struct {
	ID          string
	UserID      string
	FileName    string
	Fingerprint string
	TotalBytes  int64
	PartSize    int32
	PartCount   int32
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) InsertCampaignImport(ctx context.Context, arg InsertCampaignImportParams) (CampaignImport, error) {
	row := q.db.QueryRow(ctx, insertCampaignImport,
		arg.ID,
		arg.UserID,
		arg.FileName,
		arg.Fingerprint,
		arg.TotalBytes,
		arg.PartSize,
		arg.PartCount,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i CampaignImport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.Fingerprint,
		&i.TotalBytes,
		&i.PartSize,
		&i.PartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listCampaignExportsOfCampaign = `-- name: ListCampaignExportsOfCampaign :many
SELECT id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at FROM campaign_exports WHERE campaign_id = $1
`

func (q *Queries) ListCampaignExportsOfCampaign(ctx context.Context, campaignID string) ([]CampaignExport, error) {
	rows, err := q.db.Query(ctx, listCampaignExportsOfCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignExport
	for rows.Next() {
		var i CampaignExport
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.RequestedBy,
			&i.State,
			&i.Percent,
			&i.Failure,
			&i.FileName,
			&i.BlobKey,
			&i.ByteSize,
			&i.EntryCount,
			&i.CreateKey,
			&i.CreateHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignExportsOfUser = `-- name: ListCampaignExportsOfUser :many
SELECT id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at FROM campaign_exports WHERE requested_by = $1
`

func (q *Queries) ListCampaignExportsOfUser(ctx context.Context, requestedBy string) ([]CampaignExport, error) {
	rows, err := q.db.Query(ctx, listCampaignExportsOfUser, requestedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignExport
	for rows.Next() {
		var i CampaignExport
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.RequestedBy,
			&i.State,
			&i.Percent,
			&i.Failure,
			&i.FileName,
			&i.BlobKey,
			&i.ByteSize,
			&i.EntryCount,
			&i.CreateKey,
			&i.CreateHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignImportParts = `-- name: ListCampaignImportParts :many
SELECT import_id, part_number, byte_size, created_at FROM campaign_import_parts WHERE import_id = $1 ORDER BY part_number
`

func (q *Queries) ListCampaignImportParts(ctx context.Context, importID string) ([]CampaignImportPart, error) {
	rows, err := q.db.Query(ctx, listCampaignImportParts, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignImportPart
	for rows.Next() {
		var i CampaignImportPart
		if err := rows.Scan(
			&i.ImportID,
			&i.PartNumber,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignImportsOfUser = `-- name: ListCampaignImportsOfUser :many
SELECT id, user_id, file_name, fingerprint, total_bytes, part_size, part_count, created_at, updated_at, expires_at FROM campaign_imports WHERE user_id = $1
`

func (q *Queries) ListCampaignImportsOfUser(ctx context.Context, userID string) ([]CampaignImport, error) {
	rows, err := q.db.Query(ctx, listCampaignImportsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignImport
	for rows.Next() {
		var i CampaignImport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.Fingerprint,
			&i.TotalBytes,
			&i.PartSize,
			&i.PartCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredCampaignExports = `-- name: ListExpiredCampaignExports :many
SELECT id, campaign_id, requested_by, state, percent, failure, file_name, blob_key, byte_size, entry_count, create_key, create_hash, created_at, updated_at, finished_at, expires_at FROM campaign_exports WHERE expires_at <= $1 ORDER BY expires_at LIMIT $2
`

type ListExpiredCampaignExportsParams struct {
	ExpiresAt time.Time
	Limit     int32
}

func (q *Queries) ListExpiredCampaignExports(ctx context.Context, arg ListExpiredCampaignExportsParams) ([]CampaignExport, error) {
	rows, err := q.db.Query(ctx, listExpiredCampaignExports, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignExport
	for rows.Next() {
		var i CampaignExport
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.RequestedBy,
			&i.State,
			&i.Percent,
			&i.Failure,
			&i.FileName,
			&i.BlobKey,
			&i.ByteSize,
			&i.EntryCount,
			&i.CreateKey,
			&i.CreateHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredCampaignImports = `-- name: ListExpiredCampaignImports :many
SELECT id, user_id, file_name, fingerprint, total_bytes, part_size, part_count, created_at, updated_at, expires_at FROM campaign_imports WHERE expires_at <= $1 ORDER BY expires_at LIMIT $2
`

type ListExpiredCampaignImportsParams struct {
	ExpiresAt time.Time
	Limit     int32
}

func (q *Queries) ListExpiredCampaignImports(ctx context.Context, arg ListExpiredCampaignImportsParams) ([]CampaignImport, error) {
	rows, err := q.db.Query(ctx, listExpiredCampaignImports, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignImport
	for rows.Next() {
		var i CampaignImport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.Fingerprint,
			&i.TotalBytes,
			&i.PartSize,
			&i.PartCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCampaignExportProgress = `-- name: SetCampaignExportProgress :exec
UPDATE campaign_exports SET percent = $2, updated_at = $3
WHERE id = $1 AND state = 'running'
`

type SetCampaignExportProgressParams struct {
	ID        string
	Percent   int32
	UpdatedAt time.Time
}

func (q *Queries) SetCampaignExportProgress(ctx context.Context, arg SetCampaignExportProgressParams) error {
	_, err := q.db.Exec(ctx, setCampaignExportProgress, arg.ID, arg.Percent, arg.UpdatedAt)
	return err
}

const touchCampaignImport = `-- name: TouchCampaignImport :exec
UPDATE campaign_imports SET updated_at = $2, expires_at = $3 WHERE id = $1
`

type TouchCampaignImportParams struct {
	ID        string
	UpdatedAt time.Time
	ExpiresAt time.Time
}

// A part arrived: the parts are kept an hour from now.
func (q *Queries) TouchCampaignImport(ctx context.Context, arg TouchCampaignImportParams) error {
	_, err := q.db.Exec(ctx, touchCampaignImport, arg.ID, arg.UpdatedAt, arg.ExpiresAt)
	return err
}

const upsertCampaignImportPart = `-- name: UpsertCampaignImportPart :exec
INSERT INTO campaign_import_parts (import_id, part_number, byte_size, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (import_id, part_number) DO UPDATE SET byte_size = excluded.byte_size, created_at = excluded.created_at
`

type UpsertCampaignImportPartParams struct {
	ImportID   string
	PartNumber int32
	ByteSize   int32
	CreatedAt  time.Time
}

func (q *Queries) UpsertCampaignImportPart(ctx context.Context, arg UpsertCampaignImportPartParams) error {
	_, err := q.db.Exec(ctx, upsertCampaignImportPart,
		arg.ImportID,
		arg.PartNumber,
		arg.ByteSize,
		arg.CreatedAt,
	)
	return err
}
