// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mapsdb

import (
	"time"
)

type GalleryImage struct {
	ID          string
	CampaignID  string
	UploadedBy  *string
	Name        string
	ContentType string
	Width       int32
	Height      int32
	ByteSize    int32
	CreatedAt   time.Time
}

type Map struct {
	ID         string
	CampaignID string
	Name       string
	ImageID    string
	RevealedAt *time.Time
	Revision   int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type MapPoint struct {
	ID          string
	MapID       string
	Kind        string
	Name        string
	Description string
	XBp         int32
	YBp         int32
	TargetMapID *string
	RevealedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MapToken struct {
	MapID       string
	CharacterID string
	XBp         int32
	YBp         int32
	Hidden      bool
	UpdatedAt   time.Time
}
