// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package mapsdb

import (
	"context"
	"time"
)

const deleteGalleryImage = `-- name: DeleteGalleryImage :one
DELETE FROM gallery_images
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at
`

type DeleteGalleryImageParams struct {
	CampaignID string
	ID         string
}

// The row goes first; the caller deletes the files after the commit.
func (q *Queries) DeleteGalleryImage(ctx context.Context, arg DeleteGalleryImageParams) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, deleteGalleryImage, arg.CampaignID, arg.ID)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getGalleryImage = `-- name: GetGalleryImage :one
SELECT id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at FROM gallery_images
WHERE id = $1
`

// An image by its ID alone, to serve it: the caller's membership in its
// campaign is checked right after.
func (q *Queries) GetGalleryImage(ctx context.Context, id string) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, getGalleryImage, id)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getGalleryUsage = `-- name: GetGalleryUsage :one
SELECT
    count(*)::INT4 AS image_count,
    COALESCE(sum(byte_size), 0)::INT8 AS byte_count
FROM gallery_images
WHERE campaign_id = $1
`

type GetGalleryUsageRow struct {
	ImageCount int32
	ByteCount  int64
}

// How much of the quota the campaign uses: its images and their bytes.
// Upload reads it inside the transaction that inserts the new row, so two
// uploads racing cannot both squeeze under the limit: CockroachDB's
// SERIALIZABLE isolation makes one of them retry and count again.
func (q *Queries) GetGalleryUsage(ctx context.Context, campaignID string) (GetGalleryUsageRow, error) {
	row := q.db.QueryRow(ctx, getGalleryUsage, campaignID)
	var i GetGalleryUsageRow
	err := row.Scan(&i.ImageCount, &i.ByteCount)
	return i, err
}

const insertGalleryImage = `-- name: InsertGalleryImage :one
INSERT INTO gallery_images (id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at
`

type InsertGalleryImageParams struct {
	ID          string
	CampaignID  string
	UploadedBy  *string
	Name        string
	ContentType string
	Width       int32
	Height      int32
	ByteSize    int32
	CreatedAt   time.Time
}

func (q *Queries) InsertGalleryImage(ctx context.Context, arg InsertGalleryImageParams) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, insertGalleryImage,
		arg.ID,
		arg.CampaignID,
		arg.UploadedBy,
		arg.Name,
		arg.ContentType,
		arg.Width,
		arg.Height,
		arg.ByteSize,
		arg.CreatedAt,
	)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const listGalleryImages = `-- name: ListGalleryImages :many
SELECT id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at FROM gallery_images
WHERE campaign_id = $1
ORDER BY created_at DESC, id DESC
`

// Newest first; id breaks ties, so the order never changes between calls.
func (q *Queries) ListGalleryImages(ctx context.Context, campaignID string) ([]GalleryImage, error) {
	rows, err := q.db.Query(ctx, listGalleryImages, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GalleryImage
	for rows.Next() {
		var i GalleryImage
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.UploadedBy,
			&i.Name,
			&i.ContentType,
			&i.Width,
			&i.Height,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameGalleryImage = `-- name: RenameGalleryImage :one
UPDATE gallery_images
SET name = $3
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at
`

type RenameGalleryImageParams struct {
	CampaignID string
	ID         string
	Name       string
}

func (q *Queries) RenameGalleryImage(ctx context.Context, arg RenameGalleryImageParams) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, renameGalleryImage, arg.CampaignID, arg.ID, arg.Name)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}
