// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package mapsdb

import (
	"context"
	"time"
)

const bumpMapLayersRevision = `-- name: BumpMapLayersRevision :one
UPDATE maps
SET layers_revision = layers_revision + 1
WHERE id = $1
RETURNING layers_revision
`

// A painted layer changed, or all of them were cleared: readers must read them
// again. It leaves updated_at and revision (the name and image's guard) alone.
func (q *Queries) BumpMapLayersRevision(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, bumpMapLayersRevision, id)
	var layers_revision int32
	err := row.Scan(&layers_revision)
	return layers_revision, err
}

const bumpMapLightRevision = `-- name: BumpMapLightRevision :one
UPDATE maps
SET light_revision = light_revision + 1
WHERE id = $1
RETURNING light_revision
`

// The painted light changed. No player reads the light, so this is not the
// number they see: the master reads layers_revision + light_revision.
func (q *Queries) BumpMapLightRevision(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, bumpMapLightRevision, id)
	var light_revision int32
	err := row.Scan(&light_revision)
	return light_revision, err
}

const clearMapVisionMemory = `-- name: ClearMapVisionMemory :execrows
UPDATE maps SET vision_epoch = vision_epoch + 1
WHERE id = $1
`

// "Esquecer o que foi visto", and a new grid or image: every player forgets. The
// epoch goes up, so a refresh that was already running cannot write the old bitmap.
func (q *Queries) ClearMapVisionMemory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, clearMapVisionMemory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearTreasureFound = `-- name: ClearTreasureFound :one
UPDATE map_points
SET treasure_found_at = NULL, treasure_session_id = NULL, updated_at = $1
WHERE map_id = $2 AND id = $3 AND kind = 'treasure'
RETURNING id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft
`

type ClearTreasureFoundParams struct {
	Now   time.Time
	MapID string
	ID    string
}

// Takes the found mark off a treasure.
func (q *Queries) ClearTreasureFound(ctx context.Context, arg ClearTreasureFoundParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, clearTreasureFound, arg.Now, arg.MapID, arg.ID)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const countMapPoints = `-- name: CountMapPoints :one
SELECT count(*)::INT4 AS point_count FROM map_points
WHERE map_id = $1
`

// The map's points, for the limit, inside the transaction that inserts one.
func (q *Queries) CountMapPoints(ctx context.Context, mapID string) (int32, error) {
	row := q.db.QueryRow(ctx, countMapPoints, mapID)
	var point_count int32
	err := row.Scan(&point_count)
	return point_count, err
}

const countMaps = `-- name: CountMaps :one
SELECT count(*)::INT4 AS map_count FROM maps
WHERE campaign_id = $1
`

// The campaign's maps, for the limit. Read inside the transaction that
// inserts a map, as GetGalleryUsage.
func (q *Queries) CountMaps(ctx context.Context, campaignID string) (int32, error) {
	row := q.db.QueryRow(ctx, countMaps, campaignID)
	var map_count int32
	err := row.Scan(&map_count)
	return map_count, err
}

const countSceneActions = `-- name: CountSceneActions :one
SELECT count(*)::INT4 AS action_count FROM scene_actions
WHERE point_id = $1
`

func (q *Queries) CountSceneActions(ctx context.Context, pointID string) (int32, error) {
	row := q.db.QueryRow(ctx, countSceneActions, pointID)
	var action_count int32
	err := row.Scan(&action_count)
	return action_count, err
}

const deleteGalleryImage = `-- name: DeleteGalleryImage :one
DELETE FROM gallery_images
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at
`

type DeleteGalleryImageParams struct {
	CampaignID string
	ID         string
}

// The row goes first; the caller deletes the files after the commit.
func (q *Queries) DeleteGalleryImage(ctx context.Context, arg DeleteGalleryImageParams) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, deleteGalleryImage, arg.CampaignID, arg.ID)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMap = `-- name: DeleteMap :one
DELETE FROM maps
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch
`

type DeleteMapParams struct {
	CampaignID string
	ID         string
}

// Points and tokens go with the map (CASCADE); submap points of other maps
// lose their target, and a session's current map is unset (SET NULL).
func (q *Queries) DeleteMap(ctx context.Context, arg DeleteMapParams) (Map, error) {
	row := q.db.QueryRow(ctx, deleteMap, arg.CampaignID, arg.ID)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const deleteMapCreatureToken = `-- name: DeleteMapCreatureToken :one
DELETE FROM map_creature_tokens
WHERE map_id = $1 AND creature_id = $2
RETURNING map_id, creature_id, x_bp, y_bp, updated_at
`

type DeleteMapCreatureTokenParams struct {
	MapID      string
	CreatureID string
}

func (q *Queries) DeleteMapCreatureToken(ctx context.Context, arg DeleteMapCreatureTokenParams) (MapCreatureToken, error) {
	row := q.db.QueryRow(ctx, deleteMapCreatureToken, arg.MapID, arg.CreatureID)
	var i MapCreatureToken
	err := row.Scan(
		&i.MapID,
		&i.CreatureID,
		&i.XBp,
		&i.YBp,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMapLayers = `-- name: DeleteMapLayers :execrows
DELETE FROM map_layers
WHERE map_id = $1
`

// Clears every layer of the map: the grid's columns or the image changed.
func (q *Queries) DeleteMapLayers(ctx context.Context, mapID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMapLayers, mapID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMapPoint = `-- name: DeleteMapPoint :one
DELETE FROM map_points
WHERE map_id = $1 AND id = $2
RETURNING id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft
`

type DeleteMapPointParams struct {
	MapID string
	ID    string
}

func (q *Queries) DeleteMapPoint(ctx context.Context, arg DeleteMapPointParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, deleteMapPoint, arg.MapID, arg.ID)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const deleteMapToken = `-- name: DeleteMapToken :one
DELETE FROM map_tokens
WHERE map_id = $1 AND character_id = $2
RETURNING map_id, character_id, x_bp, y_bp, hidden, updated_at, carried_light
`

type DeleteMapTokenParams struct {
	MapID       string
	CharacterID string
}

func (q *Queries) DeleteMapToken(ctx context.Context, arg DeleteMapTokenParams) (MapToken, error) {
	row := q.db.QueryRow(ctx, deleteMapToken, arg.MapID, arg.CharacterID)
	var i MapToken
	err := row.Scan(
		&i.MapID,
		&i.CharacterID,
		&i.XBp,
		&i.YBp,
		&i.Hidden,
		&i.UpdatedAt,
		&i.CarriedLight,
	)
	return i, err
}

const deleteMapVisionMemory = `-- name: DeleteMapVisionMemory :execrows
DELETE FROM map_vision_memory
WHERE map_id = $1
`

// The rows of the cleared epochs (they already read as empty); tidying only.
func (q *Queries) DeleteMapVisionMemory(ctx context.Context, mapID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMapVisionMemory, mapID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePointReveals = `-- name: DeletePointReveals :exec
DELETE FROM map_point_reveals
WHERE point_id = $1
`

// A point that stops being a trap tells nobody anything.
func (q *Queries) DeletePointReveals(ctx context.Context, pointID string) error {
	_, err := q.db.Exec(ctx, deletePointReveals, pointID)
	return err
}

const deleteSceneAction = `-- name: DeleteSceneAction :execrows
DELETE FROM scene_actions
WHERE point_id = $1 AND id = $2
`

type DeleteSceneActionParams struct {
	PointID string
	ID      string
}

func (q *Queries) DeleteSceneAction(ctx context.Context, arg DeleteSceneActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSceneAction, arg.PointID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSceneActionsOfPoint = `-- name: DeleteSceneActionsOfPoint :exec
DELETE FROM scene_actions
WHERE point_id = $1
`

// A point that stops being a scene has no actions.
func (q *Queries) DeleteSceneActionsOfPoint(ctx context.Context, pointID string) error {
	_, err := q.db.Exec(ctx, deleteSceneActionsOfPoint, pointID)
	return err
}

const deleteSceneClue = `-- name: DeleteSceneClue :execrows
DELETE FROM scene_clues
WHERE point_id = $1 AND id = $2
`

type DeleteSceneClueParams struct {
	PointID string
	ID      string
}

func (q *Queries) DeleteSceneClue(ctx context.Context, arg DeleteSceneClueParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSceneClue, arg.PointID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSceneCluesOfPoint = `-- name: DeleteSceneCluesOfPoint :exec
DELETE FROM scene_clues
WHERE point_id = $1
`

// A point that stops being a scene has no clues. What players already
// received stays (scene_clue_reveals keeps its own copy of the text).
func (q *Queries) DeleteSceneCluesOfPoint(ctx context.Context, pointID string) error {
	_, err := q.db.Exec(ctx, deleteSceneCluesOfPoint, pointID)
	return err
}

const deleteTreasureFinders = `-- name: DeleteTreasureFinders :exec
DELETE FROM map_treasure_finders
WHERE point_id = $1
`

func (q *Queries) DeleteTreasureFinders(ctx context.Context, pointID string) error {
	_, err := q.db.Exec(ctx, deleteTreasureFinders, pointID)
	return err
}

const getGalleryImage = `-- name: GetGalleryImage :one
SELECT id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at FROM gallery_images
WHERE id = $1
`

// An image by its ID alone, to serve it: the caller's membership in its
// campaign is checked right after.
func (q *Queries) GetGalleryImage(ctx context.Context, id string) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, getGalleryImage, id)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getGalleryImageInCampaign = `-- name: GetGalleryImageInCampaign :one

SELECT id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at FROM gallery_images
WHERE campaign_id = $1 AND id = $2
`

type GetGalleryImageInCampaignParams struct {
	CampaignID string
	ID         string
}

// Maps (MR-008, MR-009, MR-012). Every query names the campaign next to the
// map, or runs after a query that did: a map of another campaign matches no
// row, which the handlers answer as "not found".
// The image a map is made of must be one of the campaign's.
func (q *Queries) GetGalleryImageInCampaign(ctx context.Context, arg GetGalleryImageInCampaignParams) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, getGalleryImageInCampaign, arg.CampaignID, arg.ID)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getGalleryUsage = `-- name: GetGalleryUsage :one
SELECT
    count(*)::INT4 AS image_count,
    COALESCE(sum(byte_size), 0)::INT8 AS byte_count
FROM gallery_images
WHERE campaign_id = $1
`

type GetGalleryUsageRow struct {
	ImageCount int32
	ByteCount  int64
}

// How much of the quota the campaign uses: its images and their bytes.
// Upload reads it inside the transaction that inserts the new row, so two
// uploads racing cannot both squeeze under the limit: CockroachDB's
// SERIALIZABLE isolation makes one of them retry and count again.
func (q *Queries) GetGalleryUsage(ctx context.Context, campaignID string) (GetGalleryUsageRow, error) {
	row := q.db.QueryRow(ctx, getGalleryUsage, campaignID)
	var i GetGalleryUsageRow
	err := row.Scan(&i.ImageCount, &i.ByteCount)
	return i, err
}

const getMap = `-- name: GetMap :one
SELECT id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch FROM maps
WHERE campaign_id = $1 AND id = $2
`

type GetMapParams struct {
	CampaignID string
	ID         string
}

func (q *Queries) GetMap(ctx context.Context, arg GetMapParams) (Map, error) {
	row := q.db.QueryRow(ctx, getMap, arg.CampaignID, arg.ID)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const getMapForUpdate = `-- name: GetMapForUpdate :one
SELECT id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch FROM maps
WHERE campaign_id = $1 AND id = $2
FOR UPDATE
`

type GetMapForUpdateParams struct {
	CampaignID string
	ID         string
}

// FOR UPDATE locks the map's row until the transaction ends, so two edits of
// the same map wait for each other instead of both reading the same
// revision.
func (q *Queries) GetMapForUpdate(ctx context.Context, arg GetMapForUpdateParams) (Map, error) {
	row := q.db.QueryRow(ctx, getMapForUpdate, arg.CampaignID, arg.ID)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const getMapGrid = `-- name: GetMapGrid :one
SELECT m.grid_columns, g.width AS image_width, g.height AS image_height
FROM maps AS m
JOIN gallery_images AS g ON g.id = m.image_id
WHERE m.campaign_id = $1 AND m.id = $2
`

type GetMapGridParams struct {
	CampaignID string
	ID         string
}

type GetMapGridRow struct {
	GridColumns *int32
	ImageWidth  int32
	ImageHeight int32
}

// A map's grid and its image's size, for the rows (package play, through
// SessionMaps).
func (q *Queries) GetMapGrid(ctx context.Context, arg GetMapGridParams) (GetMapGridRow, error) {
	row := q.db.QueryRow(ctx, getMapGrid, arg.CampaignID, arg.ID)
	var i GetMapGridRow
	err := row.Scan(&i.GridColumns, &i.ImageWidth, &i.ImageHeight)
	return i, err
}

const getMapLayers = `-- name: GetMapLayers :one
SELECT map_id, difficult_terrain, walls, cover, light, updated_at, doors FROM map_layers
WHERE map_id = $1
`

// The map's painted layers; no row means nothing is painted.
func (q *Queries) GetMapLayers(ctx context.Context, mapID string) (MapLayer, error) {
	row := q.db.QueryRow(ctx, getMapLayers, mapID)
	var i MapLayer
	err := row.Scan(
		&i.MapID,
		&i.DifficultTerrain,
		&i.Walls,
		&i.Cover,
		&i.Light,
		&i.UpdatedAt,
		&i.Doors,
	)
	return i, err
}

const getMapPoint = `-- name: GetMapPoint :one
SELECT id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft FROM map_points
WHERE map_id = $1 AND id = $2
`

type GetMapPointParams struct {
	MapID string
	ID    string
}

// One point of a map, without locking it.
func (q *Queries) GetMapPoint(ctx context.Context, arg GetMapPointParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, getMapPoint, arg.MapID, arg.ID)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const getMapPointForUpdate = `-- name: GetMapPointForUpdate :one
SELECT id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft FROM map_points
WHERE map_id = $1 AND id = $2
FOR UPDATE
`

type GetMapPointForUpdateParams struct {
	MapID string
	ID    string
}

// The caller checked first that the map is the campaign's.
func (q *Queries) GetMapPointForUpdate(ctx context.Context, arg GetMapPointForUpdateParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, getMapPointForUpdate, arg.MapID, arg.ID)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const getMapPointInCampaign = `-- name: GetMapPointInCampaign :one
SELECT p.id, p.map_id, p.kind, p.name, p.description, p.x_bp, p.y_bp, p.target_map_id, p.revealed_at, p.created_at, p.updated_at, p.hooks, p.show_dc, p.trap, p.trap_state, p.trap_triggered_at, p.treasure_value_po, p.treasure_found_at, p.treasure_session_id, p.treasure_converted_award_id, p.light_preset, p.light_bright_ft, p.light_dim_ft FROM map_points AS p
JOIN maps AS m ON m.id = p.map_id
WHERE m.campaign_id = $1 AND p.id = $2
`

type GetMapPointInCampaignParams struct {
	CampaignID string
	ID         string
}

// A point by its ID alone, if it is on one of the campaign's maps: the
// battle point a combat starts from.
func (q *Queries) GetMapPointInCampaign(ctx context.Context, arg GetMapPointInCampaignParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, getMapPointInCampaign, arg.CampaignID, arg.ID)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const getMapTileInfo = `-- name: GetMapTileInfo :one
SELECT m.id, m.campaign_id, m.image_id, m.revealed_at, m.grid_columns, m.fog_enabled,
       g.width AS image_width, g.height AS image_height, g.content_type AS image_content_type
FROM maps AS m
JOIN gallery_images AS g ON g.id = m.image_id
WHERE m.id = $1
`

type GetMapTileInfoRow struct {
	ID               string
	CampaignID       string
	ImageID          string
	RevealedAt       *time.Time
	GridColumns      *int32
	FogEnabled       bool
	ImageWidth       int32
	ImageHeight      int32
	ImageContentType string
}

// What the tile route needs of a map, in one read, from the map's ID alone: its
// campaign, whether players see it, the fog and grid, and its image's size and type.
func (q *Queries) GetMapTileInfo(ctx context.Context, id string) (GetMapTileInfoRow, error) {
	row := q.db.QueryRow(ctx, getMapTileInfo, id)
	var i GetMapTileInfoRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ImageID,
		&i.RevealedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.ImageContentType,
	)
	return i, err
}

const getMapTokenForUpdate = `-- name: GetMapTokenForUpdate :one
SELECT map_id, character_id, x_bp, y_bp, hidden, updated_at, carried_light FROM map_tokens
WHERE map_id = $1 AND character_id = $2
FOR UPDATE
`

type GetMapTokenForUpdateParams struct {
	MapID       string
	CharacterID string
}

func (q *Queries) GetMapTokenForUpdate(ctx context.Context, arg GetMapTokenForUpdateParams) (MapToken, error) {
	row := q.db.QueryRow(ctx, getMapTokenForUpdate, arg.MapID, arg.CharacterID)
	var i MapToken
	err := row.Scan(
		&i.MapID,
		&i.CharacterID,
		&i.XBp,
		&i.YBp,
		&i.Hidden,
		&i.UpdatedAt,
		&i.CarriedLight,
	)
	return i, err
}

const getMapTreasureLocks = `-- name: GetMapTreasureLocks :one
SELECT (count(*) FILTER (WHERE treasure_found_at IS NOT NULL))::INT4 AS found,
       (count(*) FILTER (WHERE treasure_converted_award_id IS NOT NULL))::INT4 AS converted
FROM map_points
WHERE map_id = $1 AND kind = 'treasure'
`

type GetMapTreasureLocksRow struct {
	Found     int32
	Converted int32
}

// Whether the map holds a treasure that was found or converted: such a map
// cannot be deleted, so a found treasure never vanishes from a session's summary.
func (q *Queries) GetMapTreasureLocks(ctx context.Context, mapID string) (GetMapTreasureLocksRow, error) {
	row := q.db.QueryRow(ctx, getMapTreasureLocks, mapID)
	var i GetMapTreasureLocksRow
	err := row.Scan(&i.Found, &i.Converted)
	return i, err
}

const getMapVisionMemory = `-- name: GetMapVisionMemory :one

SELECT seen, epoch FROM map_vision_memory
WHERE map_id = $1 AND user_id = $2
`

type GetMapVisionMemoryParams struct {
	MapID  string
	UserID string
}

type GetMapVisionMemoryRow struct {
	Seen  []byte
	Epoch int32
}

// What each player saw of a map with the fog of war on (MR-036, D6). The bytes are
// a packed bitmap in package rules/grid's layout; the handlers size them by the
// map's grid.
// One player's memory of a map; no row means they have seen nothing yet. The
// caller compares epoch with the map's vision_epoch: an older one reads as empty.
func (q *Queries) GetMapVisionMemory(ctx context.Context, arg GetMapVisionMemoryParams) (GetMapVisionMemoryRow, error) {
	row := q.db.QueryRow(ctx, getMapVisionMemory, arg.MapID, arg.UserID)
	var i GetMapVisionMemoryRow
	err := row.Scan(&i.Seen, &i.Epoch)
	return i, err
}

const getSceneActionForUpdate = `-- name: GetSceneActionForUpdate :one
SELECT id, point_id, position, key, name, dc, created_at, updated_at, max_attempts FROM scene_actions
WHERE point_id = $1 AND id = $2
FOR UPDATE
`

type GetSceneActionForUpdateParams struct {
	PointID string
	ID      string
}

func (q *Queries) GetSceneActionForUpdate(ctx context.Context, arg GetSceneActionForUpdateParams) (SceneAction, error) {
	row := q.db.QueryRow(ctx, getSceneActionForUpdate, arg.PointID, arg.ID)
	var i SceneAction
	err := row.Scan(
		&i.ID,
		&i.PointID,
		&i.Position,
		&i.Key,
		&i.Name,
		&i.Dc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAttempts,
	)
	return i, err
}

const getSceneClueForUpdate = `-- name: GetSceneClueForUpdate :one
SELECT id, point_id, position, text, created_at, updated_at FROM scene_clues
WHERE point_id = $1 AND id = $2
FOR UPDATE
`

type GetSceneClueForUpdateParams struct {
	PointID string
	ID      string
}

func (q *Queries) GetSceneClueForUpdate(ctx context.Context, arg GetSceneClueForUpdateParams) (SceneClue, error) {
	row := q.db.QueryRow(ctx, getSceneClueForUpdate, arg.PointID, arg.ID)
	var i SceneClue
	err := row.Scan(
		&i.ID,
		&i.PointID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSceneClueInCampaign = `-- name: GetSceneClueInCampaign :one
SELECT c.id, c.point_id, c.position, c.text, c.created_at, c.updated_at FROM scene_clues AS c
JOIN map_points AS p ON p.id = c.point_id
JOIN maps AS m ON m.id = p.map_id
WHERE m.campaign_id = $1 AND c.id = $2
`

type GetSceneClueInCampaignParams struct {
	CampaignID string
	ID         string
}

// A clue by its ID alone, if it is on a point of the campaign's maps: the one
// the master reveals.
func (q *Queries) GetSceneClueInCampaign(ctx context.Context, arg GetSceneClueInCampaignParams) (SceneClue, error) {
	row := q.db.QueryRow(ctx, getSceneClueInCampaign, arg.CampaignID, arg.ID)
	var i SceneClue
	err := row.Scan(
		&i.ID,
		&i.PointID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScenePoint = `-- name: GetScenePoint :one
SELECT p.id, p.map_id, p.kind, p.name, p.description, p.x_bp, p.y_bp, p.target_map_id, p.revealed_at, p.created_at, p.updated_at, p.hooks, p.show_dc, p.trap, p.trap_state, p.trap_triggered_at, p.treasure_value_po, p.treasure_found_at, p.treasure_session_id, p.treasure_converted_award_id, p.light_preset, p.light_bright_ft, p.light_dim_ft FROM map_points AS p
JOIN maps AS m ON m.id = p.map_id
WHERE m.campaign_id = $1 AND p.id = $2 AND p.kind = 'scene'
`

type GetScenePointParams struct {
	CampaignID string
	ID         string
}

// A SCENE point of the campaign's maps by its ID alone, hidden or not: the one
// the master opens in a session (package play, through SessionMaps).
func (q *Queries) GetScenePoint(ctx context.Context, arg GetScenePointParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, getScenePoint, arg.CampaignID, arg.ID)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const imageIsLeft = `-- name: ImageIsLeft :one
SELECT EXISTS (
    SELECT 1 FROM campaign_left_images
    WHERE campaign_id = $1 AND image_id = $2
)
`

type ImageIsLeftParams struct {
	CampaignID string
	ImageID    string
}

// Whether the image is left with the players. The image route asks it for a
// player (RN-10).
func (q *Queries) ImageIsLeft(ctx context.Context, arg ImageIsLeftParams) (bool, error) {
	row := q.db.QueryRow(ctx, imageIsLeft, arg.CampaignID, arg.ImageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const imageIsOnAFogMap = `-- name: ImageIsOnAFogMap :one
SELECT EXISTS (
    SELECT 1 FROM maps
    WHERE campaign_id = $1 AND image_id = $2 AND fog_enabled
)
`

type ImageIsOnAFogMapParams struct {
	CampaignID string
	ImageID    string
}

// Whether the image is the background of a map with the fog of war on: a player
// never receives it, whatever else shows it (RN-10, MR-036). The image route asks
// it for a player. A map's image is found by maps_image_id_idx.
func (q *Queries) ImageIsOnAFogMap(ctx context.Context, arg ImageIsOnAFogMapParams) (bool, error) {
	row := q.db.QueryRow(ctx, imageIsOnAFogMap, arg.CampaignID, arg.ImageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const imageIsOnAVisibleMap = `-- name: ImageIsOnAVisibleMap :one
SELECT EXISTS (
    SELECT 1 FROM maps
    WHERE campaign_id = $1 AND image_id = $2
      AND (revealed_at IS NOT NULL OR id = $3::UUID)
)
`

type ImageIsOnAVisibleMapParams struct {
	CampaignID   string
	ImageID      string
	CurrentMapID *string
}

// Whether the image is the background of a map the players see now: a
// revealed map, or the open session's current map (NULL when none). The
// image route asks it for a player (RN-10); maps_image_id_idx finds the
// maps.
func (q *Queries) ImageIsOnAVisibleMap(ctx context.Context, arg ImageIsOnAVisibleMapParams) (bool, error) {
	row := q.db.QueryRow(ctx, imageIsOnAVisibleMap, arg.CampaignID, arg.ImageID, arg.CurrentMapID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const imageIsUsedElsewhere = `-- name: ImageIsUsedElsewhere :one
SELECT (
    EXISTS (
        SELECT 1 FROM maps AS m
        WHERE m.campaign_id = $1 AND m.image_id = $2 AND m.id <> $3
    )
    OR EXISTS (
        SELECT 1 FROM campaign_left_images AS l
        WHERE l.campaign_id = $1 AND l.image_id = $2
    )
)::BOOL AS used
`

type ImageIsUsedElsewhereParams struct {
	CampaignID string
	ImageID    string
	MapID      string
}

// Whether the image is also used another way than as the background of the
// given map: the background of any other map, or an image the campaign left with
// the players. Turning the fog on copies such an image first, so the fog map's
// image is its own.
func (q *Queries) ImageIsUsedElsewhere(ctx context.Context, arg ImageIsUsedElsewhereParams) (bool, error) {
	row := q.db.QueryRow(ctx, imageIsUsedElsewhere, arg.CampaignID, arg.ImageID, arg.MapID)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const insertClueReveal = `-- name: InsertClueReveal :execrows
INSERT INTO scene_clue_reveals (campaign_id, clue_id, point_id, user_id, character_id, text, revealed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (clue_id, user_id) DO NOTHING
`

type InsertClueRevealParams struct {
	CampaignID  string
	ClueID      *string
	PointID     *string
	UserID      string
	CharacterID *string
	Text        string
	Now         time.Time
}

// Gives a clue to a player, once: the unique index on (clue_id, user_id) turns
// a second reveal into no row at all. It copies the clue's text, so what the
// player received stays as it was said.
func (q *Queries) InsertClueReveal(ctx context.Context, arg InsertClueRevealParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertClueReveal,
		arg.CampaignID,
		arg.ClueID,
		arg.PointID,
		arg.UserID,
		arg.CharacterID,
		arg.Text,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGalleryImage = `-- name: InsertGalleryImage :one
INSERT INTO gallery_images (id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at
`

type InsertGalleryImageParams struct {
	ID          string
	CampaignID  string
	UploadedBy  *string
	Name        string
	ContentType string
	Width       int32
	Height      int32
	ByteSize    int32
	CreatedAt   time.Time
}

func (q *Queries) InsertGalleryImage(ctx context.Context, arg InsertGalleryImageParams) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, insertGalleryImage,
		arg.ID,
		arg.CampaignID,
		arg.UploadedBy,
		arg.Name,
		arg.ContentType,
		arg.Width,
		arg.Height,
		arg.ByteSize,
		arg.CreatedAt,
	)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const insertMap = `-- name: InsertMap :one
INSERT INTO maps (campaign_id, name, image_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch
`

type InsertMapParams struct {
	CampaignID string
	Name       string
	ImageID    string
	Now        time.Time
}

// A new map starts hidden (revealed_at NULL).
func (q *Queries) InsertMap(ctx context.Context, arg InsertMapParams) (Map, error) {
	row := q.db.QueryRow(ctx, insertMap,
		arg.CampaignID,
		arg.Name,
		arg.ImageID,
		arg.Now,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const insertMapPoint = `-- name: InsertMapPoint :one
INSERT INTO map_points (
    map_id, kind, name, description, hooks, show_dc, x_bp, y_bp, target_map_id,
    trap, trap_state, trap_triggered_at, treasure_value_po, light_preset, light_bright_ft, light_dim_ft, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $17
)
RETURNING id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft
`

type InsertMapPointParams struct {
	MapID           string
	Kind            string
	Name            string
	Description     string
	Hooks           string
	ShowDc          bool
	XBp             int32
	YBp             int32
	TargetMapID     *string
	Trap            []byte
	TrapState       *string
	TrapTriggeredAt *time.Time
	TreasureValuePo *int32
	LightPreset     *string
	LightBrightFt   *int32
	LightDimFt      *int32
	Now             time.Time
}

// A new point starts hidden (revealed_at NULL).
func (q *Queries) InsertMapPoint(ctx context.Context, arg InsertMapPointParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, insertMapPoint,
		arg.MapID,
		arg.Kind,
		arg.Name,
		arg.Description,
		arg.Hooks,
		arg.ShowDc,
		arg.XBp,
		arg.YBp,
		arg.TargetMapID,
		arg.Trap,
		arg.TrapState,
		arg.TrapTriggeredAt,
		arg.TreasureValuePo,
		arg.LightPreset,
		arg.LightBrightFt,
		arg.LightDimFt,
		arg.Now,
	)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const insertMapToken = `-- name: InsertMapToken :one
INSERT INTO map_tokens (map_id, character_id, x_bp, y_bp, hidden, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING map_id, character_id, x_bp, y_bp, hidden, updated_at, carried_light
`

type InsertMapTokenParams struct {
	MapID       string
	CharacterID string
	XBp         int32
	YBp         int32
	Hidden      bool
	UpdatedAt   time.Time
}

func (q *Queries) InsertMapToken(ctx context.Context, arg InsertMapTokenParams) (MapToken, error) {
	row := q.db.QueryRow(ctx, insertMapToken,
		arg.MapID,
		arg.CharacterID,
		arg.XBp,
		arg.YBp,
		arg.Hidden,
		arg.UpdatedAt,
	)
	var i MapToken
	err := row.Scan(
		&i.MapID,
		&i.CharacterID,
		&i.XBp,
		&i.YBp,
		&i.Hidden,
		&i.UpdatedAt,
		&i.CarriedLight,
	)
	return i, err
}

const insertPointReveal = `-- name: InsertPointReveal :execrows
INSERT INTO map_point_reveals (point_id, character_id, how, at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (point_id, character_id) DO NOTHING
`

type InsertPointRevealParams struct {
	PointID     string
	CharacterID string
	How         string
	At          time.Time
}

// Tells a character about a trap, once: a second reveal inserts nothing.
func (q *Queries) InsertPointReveal(ctx context.Context, arg InsertPointRevealParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPointReveal,
		arg.PointID,
		arg.CharacterID,
		arg.How,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSceneAction = `-- name: InsertSceneAction :one
INSERT INTO scene_actions (point_id, position, key, name, dc, max_attempts, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, point_id, position, key, name, dc, created_at, updated_at, max_attempts
`

type InsertSceneActionParams struct {
	PointID     string
	Position    int32
	Key         string
	Name        string
	Dc          *int32
	MaxAttempts int32
	Now         time.Time
}

func (q *Queries) InsertSceneAction(ctx context.Context, arg InsertSceneActionParams) (SceneAction, error) {
	row := q.db.QueryRow(ctx, insertSceneAction,
		arg.PointID,
		arg.Position,
		arg.Key,
		arg.Name,
		arg.Dc,
		arg.MaxAttempts,
		arg.Now,
	)
	var i SceneAction
	err := row.Scan(
		&i.ID,
		&i.PointID,
		&i.Position,
		&i.Key,
		&i.Name,
		&i.Dc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAttempts,
	)
	return i, err
}

const insertSceneClue = `-- name: InsertSceneClue :one
INSERT INTO scene_clues (point_id, position, text, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, point_id, position, text, created_at, updated_at
`

type InsertSceneClueParams struct {
	PointID  string
	Position int32
	Text     string
	Now      time.Time
}

func (q *Queries) InsertSceneClue(ctx context.Context, arg InsertSceneClueParams) (SceneClue, error) {
	row := q.db.QueryRow(ctx, insertSceneClue,
		arg.PointID,
		arg.Position,
		arg.Text,
		arg.Now,
	)
	var i SceneClue
	err := row.Scan(
		&i.ID,
		&i.PointID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTreasureFinder = `-- name: InsertTreasureFinder :exec
INSERT INTO map_treasure_finders (point_id, character_id)
VALUES ($1, $2)
ON CONFLICT (point_id, character_id) DO NOTHING
`

type InsertTreasureFinderParams struct {
	PointID     string
	CharacterID string
}

func (q *Queries) InsertTreasureFinder(ctx context.Context, arg InsertTreasureFinderParams) error {
	_, err := q.db.Exec(ctx, insertTreasureFinder, arg.PointID, arg.CharacterID)
	return err
}

const leaveImage = `-- name: LeaveImage :execrows
INSERT INTO campaign_left_images (campaign_id, image_id, left_at)
SELECT g.campaign_id, g.id, $1::TIMESTAMPTZ FROM gallery_images g
WHERE g.campaign_id = $2 AND g.id = $3
ON CONFLICT (campaign_id, image_id) DO NOTHING
`

type LeaveImageParams struct {
	Now        time.Time
	CampaignID string
	ImageID    string
}

// Leaves the campaign's gallery image with the players (MR-028). Selecting
// from gallery_images makes an image deleted meanwhile, or another
// campaign's, insert nothing; an image already left keeps its left_at.
func (q *Queries) LeaveImage(ctx context.Context, arg LeaveImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaveImage, arg.Now, arg.CampaignID, arg.ImageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listClueRevealsOfMap = `-- name: ListClueRevealsOfMap :many
SELECT r.point_id, r.clue_id, r.character_id, r.revealed_at FROM scene_clue_reveals AS r
JOIN map_points AS p ON p.id = r.point_id
WHERE p.map_id = $1 AND r.clue_id IS NOT NULL
ORDER BY r.revealed_at, r.id
`

type ListClueRevealsOfMapRow struct {
	PointID     *string
	ClueID      *string
	CharacterID *string
	RevealedAt  time.Time
}

// Who has each clue of a map's points.
func (q *Queries) ListClueRevealsOfMap(ctx context.Context, mapID string) ([]ListClueRevealsOfMapRow, error) {
	rows, err := q.db.Query(ctx, listClueRevealsOfMap, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClueRevealsOfMapRow
	for rows.Next() {
		var i ListClueRevealsOfMapRow
		if err := rows.Scan(
			&i.PointID,
			&i.ClueID,
			&i.CharacterID,
			&i.RevealedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClueRevealsOfPoint = `-- name: ListClueRevealsOfPoint :many
SELECT clue_id, character_id, revealed_at FROM scene_clue_reveals
WHERE point_id = $1 AND clue_id IS NOT NULL
ORDER BY revealed_at, id
`

type ListClueRevealsOfPointRow struct {
	ClueID      *string
	CharacterID *string
	RevealedAt  time.Time
}

// Who has each clue of a point, oldest reveal first.
func (q *Queries) ListClueRevealsOfPoint(ctx context.Context, pointID *string) ([]ListClueRevealsOfPointRow, error) {
	rows, err := q.db.Query(ctx, listClueRevealsOfPoint, pointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClueRevealsOfPointRow
	for rows.Next() {
		var i ListClueRevealsOfPointRow
		if err := rows.Scan(&i.ClueID, &i.CharacterID, &i.RevealedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveredScenes = `-- name: ListDiscoveredScenes :many
SELECT p.id, p.name FROM scene_discoveries AS d
JOIN map_points AS p ON p.id = d.point_id
WHERE d.campaign_id = $1 AND p.kind = 'scene'
ORDER BY d.discovered_at, p.id
`

type ListDiscoveredScenesRow struct {
	ID   string
	Name string
}

// The scenes the group discovered, with their current names, oldest discovery
// first. A point that stopped being a scene is not listed.
func (q *Queries) ListDiscoveredScenes(ctx context.Context, campaignID string) ([]ListDiscoveredScenesRow, error) {
	rows, err := q.db.Query(ctx, listDiscoveredScenes, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscoveredScenesRow
	for rows.Next() {
		var i ListDiscoveredScenesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGalleryImages = `-- name: ListGalleryImages :many
SELECT id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at FROM gallery_images
WHERE campaign_id = $1
ORDER BY created_at DESC, id DESC
`

// Newest first; id breaks ties, so the order never changes between calls.
func (q *Queries) ListGalleryImages(ctx context.Context, campaignID string) ([]GalleryImage, error) {
	rows, err := q.db.Query(ctx, listGalleryImages, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GalleryImage
	for rows.Next() {
		var i GalleryImage
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.UploadedBy,
			&i.Name,
			&i.ContentType,
			&i.Width,
			&i.Height,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeftImages = `-- name: ListLeftImages :many
SELECT g.id, g.campaign_id, g.uploaded_by, g.name, g.content_type, g.width, g.height, g.byte_size, g.created_at FROM campaign_left_images l
JOIN gallery_images g ON g.id = l.image_id
WHERE l.campaign_id = $1
ORDER BY l.left_at, g.id
`

// The images left with the players, in the order they were left (id breaks
// ties).
func (q *Queries) ListLeftImages(ctx context.Context, campaignID string) ([]GalleryImage, error) {
	rows, err := q.db.Query(ctx, listLeftImages, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GalleryImage
	for rows.Next() {
		var i GalleryImage
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.UploadedBy,
			&i.Name,
			&i.ContentType,
			&i.Width,
			&i.Height,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapCreatureTokens = `-- name: ListMapCreatureTokens :many
SELECT map_id, creature_id, x_bp, y_bp, updated_at FROM map_creature_tokens
WHERE map_id = $1
`

// The creatures' tokens on the map (MR-037). The handler lists only the live
// creatures of living characters.
func (q *Queries) ListMapCreatureTokens(ctx context.Context, mapID string) ([]MapCreatureToken, error) {
	rows, err := q.db.Query(ctx, listMapCreatureTokens, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapCreatureToken
	for rows.Next() {
		var i MapCreatureToken
		if err := rows.Scan(
			&i.MapID,
			&i.CreatureID,
			&i.XBp,
			&i.YBp,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapDetails = `-- name: ListMapDetails :many
SELECT m.id, m.campaign_id, m.name, m.image_id, m.revealed_at, m.revision, m.created_at, m.updated_at, m.grid_columns,
       m.fog_enabled, m.base_light, m.group_vision, m.layers_revision, m.light_revision, m.vision_epoch,
       g.name AS image_name, g.width AS image_width, g.height AS image_height, g.content_type AS image_content_type,
       (SELECT count(*) FROM map_points AS p WHERE p.map_id = m.id)::INT4 AS point_count,
       (SELECT count(*) FROM map_points AS p
        WHERE p.map_id = m.id AND p.kind <> 'light'
          AND (p.revealed_at IS NOT NULL OR p.trap_triggered_at IS NOT NULL OR p.treasure_found_at IS NOT NULL))::INT4 AS revealed_point_count
FROM maps AS m
JOIN gallery_images AS g ON g.id = m.image_id
WHERE m.campaign_id = $1
ORDER BY m.created_at, m.id
`

type ListMapDetailsRow struct {
	ID                 string
	CampaignID         string
	Name               string
	ImageID            string
	RevealedAt         *time.Time
	Revision           int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	GridColumns        *int32
	FogEnabled         bool
	BaseLight          string
	GroupVision        bool
	LayersRevision     int32
	LightRevision      int32
	VisionEpoch        int32
	ImageName          string
	ImageWidth         int32
	ImageHeight        int32
	ImageContentType   string
	PointCount         int32
	RevealedPointCount int32
}

// The campaign's maps, oldest first, with what the lists show about each:
// its image's name and size, and how many points it has, in all and
// revealed. Campaigns have a few maps, so one query answers ListMaps and
// gives GetMap the names and states it needs (parents, submap targets).
//
// revealed_point_count is how many points every player sees: not a light, which
// no player ever receives, and either revealed, a triggered trap or a found
// treasure (a trap revealed to some characters only is the handler's to add).
func (q *Queries) ListMapDetails(ctx context.Context, campaignID string) ([]ListMapDetailsRow, error) {
	rows, err := q.db.Query(ctx, listMapDetails, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapDetailsRow
	for rows.Next() {
		var i ListMapDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.ImageID,
			&i.RevealedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GridColumns,
			&i.FogEnabled,
			&i.BaseLight,
			&i.GroupVision,
			&i.LayersRevision,
			&i.LightRevision,
			&i.VisionEpoch,
			&i.ImageName,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.ImageContentType,
			&i.PointCount,
			&i.RevealedPointCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapImageIDs = `-- name: ListMapImageIDs :many
SELECT id, name, image_id FROM maps
WHERE campaign_id = $1
ORDER BY created_at, id
`

type ListMapImageIDsRow struct {
	ID      string
	Name    string
	ImageID string
}

// Every map of the campaign with its image, oldest first: the gallery
// shows, on each image, the maps that use it.
func (q *Queries) ListMapImageIDs(ctx context.Context, campaignID string) ([]ListMapImageIDsRow, error) {
	rows, err := q.db.Query(ctx, listMapImageIDs, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapImageIDsRow
	for rows.Next() {
		var i ListMapImageIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ImageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapPoints = `-- name: ListMapPoints :many
SELECT id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft FROM map_points
WHERE map_id = $1
ORDER BY created_at, id
`

// The map's points, oldest first. The handler filters them for a player.
func (q *Queries) ListMapPoints(ctx context.Context, mapID string) ([]MapPoint, error) {
	rows, err := q.db.Query(ctx, listMapPoints, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapPoint
	for rows.Next() {
		var i MapPoint
		if err := rows.Scan(
			&i.ID,
			&i.MapID,
			&i.Kind,
			&i.Name,
			&i.Description,
			&i.XBp,
			&i.YBp,
			&i.TargetMapID,
			&i.RevealedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Hooks,
			&i.ShowDc,
			&i.Trap,
			&i.TrapState,
			&i.TrapTriggeredAt,
			&i.TreasureValuePo,
			&i.TreasureFoundAt,
			&i.TreasureSessionID,
			&i.TreasureConvertedAwardID,
			&i.LightPreset,
			&i.LightBrightFt,
			&i.LightDimFt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapTokens = `-- name: ListMapTokens :many
SELECT map_id, character_id, x_bp, y_bp, hidden, updated_at, carried_light FROM map_tokens
WHERE map_id = $1
`

// The map's tokens. The handler orders them by character and filters them
// for a player.
func (q *Queries) ListMapTokens(ctx context.Context, mapID string) ([]MapToken, error) {
	rows, err := q.db.Query(ctx, listMapTokens, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapToken
	for rows.Next() {
		var i MapToken
		if err := rows.Scan(
			&i.MapID,
			&i.CharacterID,
			&i.XBp,
			&i.YBp,
			&i.Hidden,
			&i.UpdatedAt,
			&i.CarriedLight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapVisionMemory = `-- name: ListMapVisionMemory :many
SELECT user_id, seen, epoch FROM map_vision_memory
WHERE map_id = $1
`

type ListMapVisionMemoryRow struct {
	UserID string
	Seen   []byte
	Epoch  int32
}

// Every player's memory of a map (a stream's hint needs each player's view).
func (q *Queries) ListMapVisionMemory(ctx context.Context, mapID string) ([]ListMapVisionMemoryRow, error) {
	rows, err := q.db.Query(ctx, listMapVisionMemory, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapVisionMemoryRow
	for rows.Next() {
		var i ListMapVisionMemoryRow
		if err := rows.Scan(&i.UserID, &i.Seen, &i.Epoch); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapsUsingImage = `-- name: ListMapsUsingImage :many
SELECT id, name FROM maps
WHERE campaign_id = $1 AND image_id = $2
ORDER BY created_at, id
`

type ListMapsUsingImageParams struct {
	CampaignID string
	ImageID    string
}

type ListMapsUsingImageRow struct {
	ID   string
	Name string
}

// The maps whose image this is, oldest first: DeleteGalleryImage names them
// (MR-019), and RenameGalleryImage returns them with the image.
func (q *Queries) ListMapsUsingImage(ctx context.Context, arg ListMapsUsingImageParams) ([]ListMapsUsingImageRow, error) {
	rows, err := q.db.Query(ctx, listMapsUsingImage, arg.CampaignID, arg.ImageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapsUsingImageRow
	for rows.Next() {
		var i ListMapsUsingImageRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointRevealCharacters = `-- name: ListPointRevealCharacters :many
SELECT r.point_id, r.character_id FROM map_point_reveals AS r
JOIN map_points AS p ON p.id = r.point_id
WHERE p.map_id = $1
`

type ListPointRevealCharactersRow struct {
	PointID     string
	CharacterID string
}

// The characters that know each trap of the map, for the noticing: one row per
// trap and character.
func (q *Queries) ListPointRevealCharacters(ctx context.Context, mapID string) ([]ListPointRevealCharactersRow, error) {
	rows, err := q.db.Query(ctx, listPointRevealCharacters, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPointRevealCharactersRow
	for rows.Next() {
		var i ListPointRevealCharactersRow
		if err := rows.Scan(&i.PointID, &i.CharacterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointRevealsOfCampaign = `-- name: ListPointRevealsOfCampaign :many
SELECT r.point_id, p.map_id, r.character_id,
       (p.revealed_at IS NOT NULL OR p.trap_triggered_at IS NOT NULL)::BOOL AS public
FROM map_point_reveals AS r
JOIN map_points AS p ON p.id = r.point_id
JOIN maps AS m ON m.id = p.map_id
WHERE m.campaign_id = $1
`

type ListPointRevealsOfCampaignRow struct {
	PointID     string
	MapID       string
	CharacterID string
	Public      bool
}

// Every trap reveal of the campaign's maps, with whether the trap is already
// visible to everyone: what a player's reads need to know which traps their
// characters know (RN-10).
func (q *Queries) ListPointRevealsOfCampaign(ctx context.Context, campaignID string) ([]ListPointRevealsOfCampaignRow, error) {
	rows, err := q.db.Query(ctx, listPointRevealsOfCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPointRevealsOfCampaignRow
	for rows.Next() {
		var i ListPointRevealsOfCampaignRow
		if err := rows.Scan(
			&i.PointID,
			&i.MapID,
			&i.CharacterID,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointRevealsOfMap = `-- name: ListPointRevealsOfMap :many
SELECT r.point_id, r.character_id, r.how, r.at FROM map_point_reveals AS r
JOIN map_points AS p ON p.id = r.point_id
WHERE p.map_id = $1
ORDER BY r.at, r.character_id
`

// Who knows each trap of a map, for the master's read.
func (q *Queries) ListPointRevealsOfMap(ctx context.Context, mapID string) ([]MapPointReveal, error) {
	rows, err := q.db.Query(ctx, listPointRevealsOfMap, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapPointReveal
	for rows.Next() {
		var i MapPointReveal
		if err := rows.Scan(
			&i.PointID,
			&i.CharacterID,
			&i.How,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointRevealsOfPoint = `-- name: ListPointRevealsOfPoint :many
SELECT point_id, character_id, how, at FROM map_point_reveals
WHERE point_id = $1
`

// Who knows one trap: the players to tell when it changes or goes away.
func (q *Queries) ListPointRevealsOfPoint(ctx context.Context, pointID string) ([]MapPointReveal, error) {
	rows, err := q.db.Query(ctx, listPointRevealsOfPoint, pointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapPointReveal
	for rows.Next() {
		var i MapPointReveal
		if err := rows.Scan(
			&i.PointID,
			&i.CharacterID,
			&i.How,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedClues = `-- name: ListReceivedClues :many
SELECT id, point_id, text, revealed_at FROM scene_clue_reveals
WHERE campaign_id = $1 AND user_id = $2
ORDER BY revealed_at DESC, id
`

type ListReceivedCluesParams struct {
	CampaignID string
	UserID     string
}

type ListReceivedCluesRow struct {
	ID         string
	PointID    *string
	Text       string
	RevealedAt time.Time
}

// The clues revealed to a player in a campaign, newest first.
func (q *Queries) ListReceivedClues(ctx context.Context, arg ListReceivedCluesParams) ([]ListReceivedCluesRow, error) {
	rows, err := q.db.Query(ctx, listReceivedClues, arg.CampaignID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivedCluesRow
	for rows.Next() {
		var i ListReceivedCluesRow
		if err := rows.Scan(
			&i.ID,
			&i.PointID,
			&i.Text,
			&i.RevealedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneActions = `-- name: ListSceneActions :many

SELECT id, point_id, position, key, name, dc, created_at, updated_at, max_attempts FROM scene_actions
WHERE point_id = $1
ORDER BY position, created_at, id
`

// The actions of an RP scene (MR-015). A scene point has at most 20; the
// handler counts them inside the transaction that inserts one.
// One point's actions, in order.
func (q *Queries) ListSceneActions(ctx context.Context, pointID string) ([]SceneAction, error) {
	rows, err := q.db.Query(ctx, listSceneActions, pointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SceneAction
	for rows.Next() {
		var i SceneAction
		if err := rows.Scan(
			&i.ID,
			&i.PointID,
			&i.Position,
			&i.Key,
			&i.Name,
			&i.Dc,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneActionsOfMap = `-- name: ListSceneActionsOfMap :many
SELECT a.id, a.point_id, a.position, a.key, a.name, a.dc, a.created_at, a.updated_at, a.max_attempts FROM scene_actions AS a
JOIN map_points AS p ON p.id = a.point_id
WHERE p.map_id = $1
ORDER BY a.point_id, a.position, a.created_at, a.id
`

// Every action of a map's points, for a map read: grouped by the handler,
// each point's in order.
func (q *Queries) ListSceneActionsOfMap(ctx context.Context, mapID string) ([]SceneAction, error) {
	rows, err := q.db.Query(ctx, listSceneActionsOfMap, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SceneAction
	for rows.Next() {
		var i SceneAction
		if err := rows.Scan(
			&i.ID,
			&i.PointID,
			&i.Position,
			&i.Key,
			&i.Name,
			&i.Dc,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneClues = `-- name: ListSceneClues :many
SELECT id, point_id, position, text, created_at, updated_at FROM scene_clues
WHERE point_id = $1
ORDER BY position, created_at, id
`

// A SCENE point's clues, in the master's order.
func (q *Queries) ListSceneClues(ctx context.Context, pointID string) ([]SceneClue, error) {
	rows, err := q.db.Query(ctx, listSceneClues, pointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SceneClue
	for rows.Next() {
		var i SceneClue
		if err := rows.Scan(
			&i.ID,
			&i.PointID,
			&i.Position,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneCluesOfMap = `-- name: ListSceneCluesOfMap :many
SELECT c.id, c.point_id, c.position, c.text, c.created_at, c.updated_at FROM scene_clues AS c
JOIN map_points AS p ON p.id = c.point_id
WHERE p.map_id = $1
ORDER BY c.point_id, c.position, c.created_at, c.id
`

// Every clue of a map's points, for the master's map read: grouped by the
// handler, each point's in order.
func (q *Queries) ListSceneCluesOfMap(ctx context.Context, mapID string) ([]SceneClue, error) {
	rows, err := q.db.Query(ctx, listSceneCluesOfMap, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SceneClue
	for rows.Next() {
		var i SceneClue
		if err := rows.Scan(
			&i.ID,
			&i.PointID,
			&i.Position,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmapLinks = `-- name: ListSubmapLinks :many
SELECT p.map_id, p.target_map_id::UUID AS target_map_id, (p.revealed_at IS NOT NULL)::BOOL AS revealed, p.x_bp, p.y_bp
FROM map_points AS p
JOIN maps AS m ON m.id = p.map_id
WHERE m.campaign_id = $1 AND p.kind = 'submap' AND p.target_map_id IS NOT NULL
ORDER BY p.created_at, p.id
`

type ListSubmapLinksRow struct {
	MapID       string
	TargetMapID string
	Revealed    bool
	XBp         int32
	YBp         int32
}

// Every submap point of the campaign that leads to a map: the map it is on,
// the map it leads to, and whether the point is revealed. It gives each map
// its parents ("Submapa de ...").
func (q *Queries) ListSubmapLinks(ctx context.Context, campaignID string) ([]ListSubmapLinksRow, error) {
	rows, err := q.db.Query(ctx, listSubmapLinks, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmapLinksRow
	for rows.Next() {
		var i ListSubmapLinksRow
		if err := rows.Scan(
			&i.MapID,
			&i.TargetMapID,
			&i.Revealed,
			&i.XBp,
			&i.YBp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrapNamesInCampaign = `-- name: ListTrapNamesInCampaign :many
SELECT p.id, p.name FROM map_points AS p
JOIN maps AS m ON m.id = p.map_id
WHERE m.campaign_id = $1 AND p.kind = 'trap' AND p.id = ANY($2::uuid[])
`

type ListTrapNamesInCampaignParams struct {
	CampaignID string
	Column2    []string
}

type ListTrapNamesInCampaignRow struct {
	ID   string
	Name string
}

// The names of traps by point ID, for the combat log: a trap that fired is
// public, so its name may be told (MR-035). A deleted point is simply absent.
func (q *Queries) ListTrapNamesInCampaign(ctx context.Context, arg ListTrapNamesInCampaignParams) ([]ListTrapNamesInCampaignRow, error) {
	rows, err := q.db.Query(ctx, listTrapNamesInCampaign, arg.CampaignID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrapNamesInCampaignRow
	for rows.Next() {
		var i ListTrapNamesInCampaignRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreasureFindersOfMap = `-- name: ListTreasureFindersOfMap :many
SELECT f.point_id, f.character_id FROM map_treasure_finders AS f
JOIN map_points AS p ON p.id = f.point_id
WHERE p.map_id = $1
`

// Who found each treasure of a map.
func (q *Queries) ListTreasureFindersOfMap(ctx context.Context, mapID string) ([]MapTreasureFinder, error) {
	rows, err := q.db.Query(ctx, listTreasureFindersOfMap, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapTreasureFinder
	for rows.Next() {
		var i MapTreasureFinder
		if err := rows.Scan(&i.PointID, &i.CharacterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreasureFindsOfSession = `-- name: ListTreasureFindsOfSession :many

SELECT p.id AS point_id, COALESCE(p.treasure_value_po, 0)::INT4 AS value_po, f.character_id
FROM map_points AS p
JOIN map_treasure_finders AS f ON f.point_id = p.id
WHERE p.kind = 'treasure' AND p.treasure_found_at IS NOT NULL AND p.treasure_session_id = $1::UUID
ORDER BY p.id, f.character_id
`

type ListTreasureFindsOfSessionRow struct {
	PointID     string
	ValuePo     int32
	CharacterID string
}

// Gold (slice 9.11, MR-032): the session summary's "Mais tesouro encontrado".
// One row per treasure and finder of the treasures found while the game session
// was open. A treasure unmarked later has no session and no finders.
func (q *Queries) ListTreasureFindsOfSession(ctx context.Context, sessionID string) ([]ListTreasureFindsOfSessionRow, error) {
	rows, err := q.db.Query(ctx, listTreasureFindsOfSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTreasureFindsOfSessionRow
	for rows.Next() {
		var i ListTreasureFindsOfSessionRow
		if err := rows.Scan(&i.PointID, &i.ValuePo, &i.CharacterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveMapCreatureToken = `-- name: MoveMapCreatureToken :exec
UPDATE map_creature_tokens
SET x_bp = $3, y_bp = $4, updated_at = $5
WHERE map_id = $1 AND creature_id = $2
`

type MoveMapCreatureTokenParams struct {
	MapID      string
	CreatureID string
	XBp        int32
	YBp        int32
	UpdatedAt  time.Time
}

// Where a creature ended its combat (package play): an existing token moves; a
// creature that has none gets none (the master places creature tokens).
func (q *Queries) MoveMapCreatureToken(ctx context.Context, arg MoveMapCreatureTokenParams) error {
	_, err := q.db.Exec(ctx, moveMapCreatureToken,
		arg.MapID,
		arg.CreatureID,
		arg.XBp,
		arg.YBp,
		arg.UpdatedAt,
	)
	return err
}

const moveMapToken = `-- name: MoveMapToken :one
UPDATE map_tokens
SET x_bp = $3, y_bp = $4, updated_at = $5
WHERE map_id = $1 AND character_id = $2
RETURNING map_id, character_id, x_bp, y_bp, hidden, updated_at, carried_light
`

type MoveMapTokenParams struct {
	MapID       string
	CharacterID string
	XBp         int32
	YBp         int32
	UpdatedAt   time.Time
}

func (q *Queries) MoveMapToken(ctx context.Context, arg MoveMapTokenParams) (MapToken, error) {
	row := q.db.QueryRow(ctx, moveMapToken,
		arg.MapID,
		arg.CharacterID,
		arg.XBp,
		arg.YBp,
		arg.UpdatedAt,
	)
	var i MapToken
	err := row.Scan(
		&i.MapID,
		&i.CharacterID,
		&i.XBp,
		&i.YBp,
		&i.Hidden,
		&i.UpdatedAt,
		&i.CarriedLight,
	)
	return i, err
}

const renameGalleryImage = `-- name: RenameGalleryImage :one
UPDATE gallery_images
SET name = $3
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, uploaded_by, name, content_type, width, height, byte_size, created_at
`

type RenameGalleryImageParams struct {
	CampaignID string
	ID         string
	Name       string
}

func (q *Queries) RenameGalleryImage(ctx context.Context, arg RenameGalleryImageParams) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, renameGalleryImage, arg.CampaignID, arg.ID, arg.Name)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.UploadedBy,
		&i.Name,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const setMapFog = `-- name: SetMapFog :one
UPDATE maps
SET fog_enabled = COALESCE($1::BOOL, fog_enabled),
    base_light = COALESCE($2::TEXT, base_light),
    group_vision = COALESCE($3::BOOL, group_vision),
    updated_at = CASE WHEN COALESCE($1::BOOL, fog_enabled) <> fog_enabled
                        OR COALESCE($3::BOOL, group_vision) <> group_vision
                      THEN $4::TIMESTAMPTZ ELSE updated_at END
WHERE campaign_id = $5 AND id = $6
RETURNING id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch
`

type SetMapFogParams struct {
	FogEnabled  *bool
	BaseLight   *string
	GroupVision *bool
	Now         time.Time
	CampaignID  string
	ID          string
}

// The fog of war's settings (MR-036): each one the handler sends replaces the
// current value, the others stay. updated_at moves only when something a
// player reads changes (the switch or "Visão do grupo"): the base light is the
// master's, and a player must not learn that it changed.
func (q *Queries) SetMapFog(ctx context.Context, arg SetMapFogParams) (Map, error) {
	row := q.db.QueryRow(ctx, setMapFog,
		arg.FogEnabled,
		arg.BaseLight,
		arg.GroupVision,
		arg.Now,
		arg.CampaignID,
		arg.ID,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const setMapGrid = `-- name: SetMapGrid :one
UPDATE maps
SET grid_columns = $1, fog_enabled = fog_enabled AND $1::INT4 IS NOT NULL,
    updated_at = $2
WHERE campaign_id = $3 AND id = $4
RETURNING id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch
`

type SetMapGridParams struct {
	GridColumns *int32
	Now         time.Time
	CampaignID  string
	ID          string
}

// The master's grid (MR-013): NULL clears it, and a map without a grid has no
// fog of war. It is a change to the map itself, so updated_at moves, but the
// revision (the name and the image's guard) does not.
func (q *Queries) SetMapGrid(ctx context.Context, arg SetMapGridParams) (Map, error) {
	row := q.db.QueryRow(ctx, setMapGrid,
		arg.GridColumns,
		arg.Now,
		arg.CampaignID,
		arg.ID,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const setMapImageOnly = `-- name: SetMapImageOnly :one
UPDATE maps
SET image_id = $1, revision = revision + 1, updated_at = $2
WHERE campaign_id = $3 AND id = $4
RETURNING id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch
`

type SetMapImageOnlyParams struct {
	ImageID    string
	Now        time.Time
	CampaignID string
	ID         string
}

// A new copy of the image becomes the map's, without touching the name or the
// revision's guard: the map's revision still moves, since the image changed.
func (q *Queries) SetMapImageOnly(ctx context.Context, arg SetMapImageOnlyParams) (Map, error) {
	row := q.db.QueryRow(ctx, setMapImageOnly,
		arg.ImageID,
		arg.Now,
		arg.CampaignID,
		arg.ID,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const setMapRevealed = `-- name: SetMapRevealed :one
UPDATE maps
SET revealed_at = CASE WHEN $1::BOOL THEN COALESCE(revealed_at, $2::TIMESTAMPTZ) ELSE NULL END,
    updated_at = CASE WHEN (revealed_at IS NOT NULL) = $1::BOOL THEN updated_at ELSE $2::TIMESTAMPTZ END
WHERE campaign_id = $3 AND id = $4
RETURNING id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch
`

type SetMapRevealedParams struct {
	Revealed   bool
	Now        time.Time
	CampaignID string
	ID         string
}

// Revealing keeps the first revealed_at, so revealing twice changes
// nothing; hiding clears it. PlayService.SetCurrentMap reveals through here
// too (SessionMaps).
func (q *Queries) SetMapRevealed(ctx context.Context, arg SetMapRevealedParams) (Map, error) {
	row := q.db.QueryRow(ctx, setMapRevealed,
		arg.Revealed,
		arg.Now,
		arg.CampaignID,
		arg.ID,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const setMapTokenCarriedLight = `-- name: SetMapTokenCarriedLight :one
UPDATE map_tokens
SET carried_light = $1, updated_at = $2
WHERE map_id = $3 AND character_id = $4
RETURNING map_id, character_id, x_bp, y_bp, hidden, updated_at, carried_light
`

type SetMapTokenCarriedLightParams struct {
	CarriedLight *string
	Now          time.Time
	MapID        string
	CharacterID  string
}

// The light a character carries (MR-036): a preset's key, NULL for none. Moving
// the token is a change to it (the master and the owner read it again).
func (q *Queries) SetMapTokenCarriedLight(ctx context.Context, arg SetMapTokenCarriedLightParams) (MapToken, error) {
	row := q.db.QueryRow(ctx, setMapTokenCarriedLight,
		arg.CarriedLight,
		arg.Now,
		arg.MapID,
		arg.CharacterID,
	)
	var i MapToken
	err := row.Scan(
		&i.MapID,
		&i.CharacterID,
		&i.XBp,
		&i.YBp,
		&i.Hidden,
		&i.UpdatedAt,
		&i.CarriedLight,
	)
	return i, err
}

const setMapTokenHidden = `-- name: SetMapTokenHidden :one
UPDATE map_tokens
SET hidden = $1, updated_at = CASE WHEN hidden = $1 THEN updated_at ELSE $2::TIMESTAMPTZ END
WHERE map_id = $3 AND character_id = $4
RETURNING map_id, character_id, x_bp, y_bp, hidden, updated_at, carried_light
`

type SetMapTokenHiddenParams struct {
	Hidden      bool
	Now         time.Time
	MapID       string
	CharacterID string
}

func (q *Queries) SetMapTokenHidden(ctx context.Context, arg SetMapTokenHiddenParams) (MapToken, error) {
	row := q.db.QueryRow(ctx, setMapTokenHidden,
		arg.Hidden,
		arg.Now,
		arg.MapID,
		arg.CharacterID,
	)
	var i MapToken
	err := row.Scan(
		&i.MapID,
		&i.CharacterID,
		&i.XBp,
		&i.YBp,
		&i.Hidden,
		&i.UpdatedAt,
		&i.CarriedLight,
	)
	return i, err
}

const setSceneActionPosition = `-- name: SetSceneActionPosition :exec
UPDATE scene_actions
SET position = $2
WHERE id = $1
`

type SetSceneActionPositionParams struct {
	ID       string
	Position int32
}

func (q *Queries) SetSceneActionPosition(ctx context.Context, arg SetSceneActionPositionParams) error {
	_, err := q.db.Exec(ctx, setSceneActionPosition, arg.ID, arg.Position)
	return err
}

const setSceneCluePosition = `-- name: SetSceneCluePosition :exec
UPDATE scene_clues SET position = $2 WHERE id = $1
`

type SetSceneCluePositionParams struct {
	ID       string
	Position int32
}

func (q *Queries) SetSceneCluePosition(ctx context.Context, arg SetSceneCluePositionParams) error {
	_, err := q.db.Exec(ctx, setSceneCluePosition, arg.ID, arg.Position)
	return err
}

const setTrapState = `-- name: SetTrapState :one
UPDATE map_points
SET trap_state = $1, trap_triggered_at = $2, updated_at = $3
WHERE map_id = $4 AND id = $5 AND kind = 'trap'
RETURNING id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft
`

type SetTrapStateParams struct {
	TrapState       *string
	TrapTriggeredAt *time.Time
	Now             time.Time
	MapID           string
	ID              string
}

// The live game changes a trap's state (MR-035, slice 9.8): it fires (state
// 'triggered', with when), the master disarms it, or an undo puts back what
// there was. The caller locked the point first.
func (q *Queries) SetTrapState(ctx context.Context, arg SetTrapStateParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, setTrapState,
		arg.TrapState,
		arg.TrapTriggeredAt,
		arg.Now,
		arg.MapID,
		arg.ID,
	)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const setTreasureFound = `-- name: SetTreasureFound :one
UPDATE map_points
SET treasure_found_at = COALESCE(treasure_found_at, $1::TIMESTAMPTZ),
    treasure_session_id = CASE WHEN treasure_found_at IS NULL THEN $2::UUID ELSE treasure_session_id END,
    updated_at = $3
WHERE map_id = $4 AND id = $5 AND kind = 'treasure'
RETURNING id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft
`

type SetTreasureFoundParams struct {
	FoundAt   time.Time
	SessionID *string
	Now       time.Time
	MapID     string
	ID        string
}

// Marks a treasure found (MR-041). The session is the one open at that time, or
// NULL. A treasure already found keeps its first time and session.
func (q *Queries) SetTreasureFound(ctx context.Context, arg SetTreasureFoundParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, setTreasureFound,
		arg.FoundAt,
		arg.SessionID,
		arg.Now,
		arg.MapID,
		arg.ID,
	)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const takeBackLeftImage = `-- name: TakeBackLeftImage :execrows
DELETE FROM campaign_left_images
WHERE campaign_id = $1 AND image_id = $2
`

type TakeBackLeftImageParams struct {
	CampaignID string
	ImageID    string
}

func (q *Queries) TakeBackLeftImage(ctx context.Context, arg TakeBackLeftImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, takeBackLeftImage, arg.CampaignID, arg.ImageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMap = `-- name: UpdateMap :one
UPDATE maps
SET name = $1, image_id = $2, revision = revision + 1, updated_at = $3
WHERE campaign_id = $4 AND id = $5 AND revision = $6
RETURNING id, campaign_id, name, image_id, revealed_at, revision, created_at, updated_at, grid_columns, fog_enabled, base_light, group_vision, layers_revision, light_revision, vision_epoch
`

type UpdateMapParams struct {
	Name       string
	ImageID    string
	Now        time.Time
	CampaignID string
	ID         string
	Revision   int32
}

// revision in the WHERE clause is a second guard: the handler already
// compared it under FOR UPDATE, so no row here means a stale revision.
func (q *Queries) UpdateMap(ctx context.Context, arg UpdateMapParams) (Map, error) {
	row := q.db.QueryRow(ctx, updateMap,
		arg.Name,
		arg.ImageID,
		arg.Now,
		arg.CampaignID,
		arg.ID,
		arg.Revision,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageID,
		&i.RevealedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GridColumns,
		&i.FogEnabled,
		&i.BaseLight,
		&i.GroupVision,
		&i.LayersRevision,
		&i.LightRevision,
		&i.VisionEpoch,
	)
	return i, err
}

const updateMapPoint = `-- name: UpdateMapPoint :one
UPDATE map_points
SET kind = $1, name = $2, description = $3, hooks = $4,
    show_dc = $5, x_bp = $6, y_bp = $7, target_map_id = $8,
    revealed_at = $9, trap = $10, trap_state = $11, trap_triggered_at = $12,
    treasure_value_po = $13, treasure_found_at = $14,
    treasure_session_id = $15, light_preset = $16,
    light_bright_ft = $17, light_dim_ft = $18, updated_at = $19
WHERE map_id = $20 AND id = $21
RETURNING id, map_id, kind, name, description, x_bp, y_bp, target_map_id, revealed_at, created_at, updated_at, hooks, show_dc, trap, trap_state, trap_triggered_at, treasure_value_po, treasure_found_at, treasure_session_id, treasure_converted_award_id, light_preset, light_bright_ft, light_dim_ft
`

type UpdateMapPointParams struct {
	Kind              string
	Name              string
	Description       string
	Hooks             string
	ShowDc            bool
	XBp               int32
	YBp               int32
	TargetMapID       *string
	RevealedAt        *time.Time
	Trap              []byte
	TrapState         *string
	TrapTriggeredAt   *time.Time
	TreasureValuePo   *int32
	TreasureFoundAt   *time.Time
	TreasureSessionID *string
	LightPreset       *string
	LightBrightFt     *int32
	LightDimFt        *int32
	Now               time.Time
	MapID             string
	ID                string
}

// Every column the API may change, with the values the handler worked out
// from the request and the current row.
func (q *Queries) UpdateMapPoint(ctx context.Context, arg UpdateMapPointParams) (MapPoint, error) {
	row := q.db.QueryRow(ctx, updateMapPoint,
		arg.Kind,
		arg.Name,
		arg.Description,
		arg.Hooks,
		arg.ShowDc,
		arg.XBp,
		arg.YBp,
		arg.TargetMapID,
		arg.RevealedAt,
		arg.Trap,
		arg.TrapState,
		arg.TrapTriggeredAt,
		arg.TreasureValuePo,
		arg.TreasureFoundAt,
		arg.TreasureSessionID,
		arg.LightPreset,
		arg.LightBrightFt,
		arg.LightDimFt,
		arg.Now,
		arg.MapID,
		arg.ID,
	)
	var i MapPoint
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.XBp,
		&i.YBp,
		&i.TargetMapID,
		&i.RevealedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hooks,
		&i.ShowDc,
		&i.Trap,
		&i.TrapState,
		&i.TrapTriggeredAt,
		&i.TreasureValuePo,
		&i.TreasureFoundAt,
		&i.TreasureSessionID,
		&i.TreasureConvertedAwardID,
		&i.LightPreset,
		&i.LightBrightFt,
		&i.LightDimFt,
	)
	return i, err
}

const updateSceneAction = `-- name: UpdateSceneAction :one
UPDATE scene_actions
SET key = $1, name = $2, dc = $3, max_attempts = $4, updated_at = $5
WHERE point_id = $6 AND id = $7
RETURNING id, point_id, position, key, name, dc, created_at, updated_at, max_attempts
`

type UpdateSceneActionParams struct {
	Key         string
	Name        string
	Dc          *int32
	MaxAttempts int32
	Now         time.Time
	PointID     string
	ID          string
}

func (q *Queries) UpdateSceneAction(ctx context.Context, arg UpdateSceneActionParams) (SceneAction, error) {
	row := q.db.QueryRow(ctx, updateSceneAction,
		arg.Key,
		arg.Name,
		arg.Dc,
		arg.MaxAttempts,
		arg.Now,
		arg.PointID,
		arg.ID,
	)
	var i SceneAction
	err := row.Scan(
		&i.ID,
		&i.PointID,
		&i.Position,
		&i.Key,
		&i.Name,
		&i.Dc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAttempts,
	)
	return i, err
}

const updateSceneClue = `-- name: UpdateSceneClue :one
UPDATE scene_clues
SET text = $1, updated_at = $2
WHERE point_id = $3 AND id = $4
RETURNING id, point_id, position, text, created_at, updated_at
`

type UpdateSceneClueParams struct {
	Text    string
	Now     time.Time
	PointID string
	ID      string
}

func (q *Queries) UpdateSceneClue(ctx context.Context, arg UpdateSceneClueParams) (SceneClue, error) {
	row := q.db.QueryRow(ctx, updateSceneClue,
		arg.Text,
		arg.Now,
		arg.PointID,
		arg.ID,
	)
	var i SceneClue
	err := row.Scan(
		&i.ID,
		&i.PointID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMapCreatureToken = `-- name: UpsertMapCreatureToken :one
INSERT INTO map_creature_tokens (map_id, creature_id, x_bp, y_bp, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (map_id, creature_id) DO UPDATE
SET x_bp = excluded.x_bp, y_bp = excluded.y_bp, updated_at = excluded.updated_at
RETURNING map_id, creature_id, x_bp, y_bp, updated_at
`

type UpsertMapCreatureTokenParams struct {
	MapID      string
	CreatureID string
	XBp        int32
	YBp        int32
	UpdatedAt  time.Time
}

// Places a creature's token, or moves it if it is on the map already.
func (q *Queries) UpsertMapCreatureToken(ctx context.Context, arg UpsertMapCreatureTokenParams) (MapCreatureToken, error) {
	row := q.db.QueryRow(ctx, upsertMapCreatureToken,
		arg.MapID,
		arg.CreatureID,
		arg.XBp,
		arg.YBp,
		arg.UpdatedAt,
	)
	var i MapCreatureToken
	err := row.Scan(
		&i.MapID,
		&i.CreatureID,
		&i.XBp,
		&i.YBp,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMapLayers = `-- name: UpsertMapLayers :exec
INSERT INTO map_layers (map_id, difficult_terrain, walls, cover, light, doors, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (map_id) DO UPDATE
SET difficult_terrain = excluded.difficult_terrain, walls = excluded.walls, cover = excluded.cover,
    light = excluded.light, doors = excluded.doors, updated_at = excluded.updated_at
`

type UpsertMapLayersParams struct {
	MapID            string
	DifficultTerrain []byte
	Walls            []byte
	Cover            []byte
	Light            []byte
	Doors            []byte
	Now              time.Time
}

// Writes the five layers of a map (NULL for a layer with nothing painted). The
// handler holds the map's row lock (GetMapForUpdate), so two batches of paint
// take turns.
func (q *Queries) UpsertMapLayers(ctx context.Context, arg UpsertMapLayersParams) error {
	_, err := q.db.Exec(ctx, upsertMapLayers,
		arg.MapID,
		arg.DifficultTerrain,
		arg.Walls,
		arg.Cover,
		arg.Light,
		arg.Doors,
		arg.Now,
	)
	return err
}

const upsertMapTokenPosition = `-- name: UpsertMapTokenPosition :exec
INSERT INTO map_tokens (map_id, character_id, x_bp, y_bp, hidden, updated_at)
VALUES ($1, $2, $3, $4, false, $5)
ON CONFLICT (map_id, character_id) DO UPDATE
SET x_bp = excluded.x_bp, y_bp = excluded.y_bp, updated_at = excluded.updated_at
`

type UpsertMapTokenPositionParams struct {
	MapID       string
	CharacterID string
	XBp         int32
	YBp         int32
	UpdatedAt   time.Time
}

// Where a combatant ended its combat (package play): the token moves, or is
// created visible (a player's character starts visible, like PlaceMapToken).
// An existing token keeps its hidden flag.
func (q *Queries) UpsertMapTokenPosition(ctx context.Context, arg UpsertMapTokenPositionParams) error {
	_, err := q.db.Exec(ctx, upsertMapTokenPosition,
		arg.MapID,
		arg.CharacterID,
		arg.XBp,
		arg.YBp,
		arg.UpdatedAt,
	)
	return err
}

const upsertMapVisionMemory = `-- name: UpsertMapVisionMemory :execrows
INSERT INTO map_vision_memory (map_id, user_id, seen, epoch, updated_at)
SELECT m.id, $1::UUID, $2::BYTEA, m.vision_epoch, $3::TIMESTAMPTZ
FROM maps AS m
WHERE m.id = $4 AND m.vision_epoch = $5
ON CONFLICT (map_id, user_id) DO UPDATE
SET seen = excluded.seen, epoch = excluded.epoch, updated_at = excluded.updated_at
`

type UpsertMapVisionMemoryParams struct {
	UserID    string
	Seen      []byte
	UpdatedAt time.Time
	MapID     string
	Epoch     int32
}

// The caller already merged the new squares into the old bytes, so the memory
// only grows. It writes only while the map is still in the epoch the bytes were
// built for: a clear that happened meanwhile bumped it, and nothing is written.
func (q *Queries) UpsertMapVisionMemory(ctx context.Context, arg UpsertMapVisionMemoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertMapVisionMemory,
		arg.UserID,
		arg.Seen,
		arg.UpdatedAt,
		arg.MapID,
		arg.Epoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSceneDiscovery = `-- name: UpsertSceneDiscovery :exec
INSERT INTO scene_discoveries (campaign_id, point_id, discovered_at)
VALUES ($1, $2, $3)
ON CONFLICT (campaign_id, point_id) DO NOTHING
`

type UpsertSceneDiscoveryParams struct {
	CampaignID   string
	PointID      string
	DiscoveredAt time.Time
}

// The group discovered a scene (MR-030): the first time wins.
func (q *Queries) UpsertSceneDiscovery(ctx context.Context, arg UpsertSceneDiscoveryParams) error {
	_, err := q.db.Exec(ctx, upsertSceneDiscovery, arg.CampaignID, arg.PointID, arg.DiscoveredAt)
	return err
}
