// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: combat_reserve.sql

package playdb

import (
	"context"
)

const characterIsInOpenCombat = `-- name: CharacterIsInOpenCombat :one
SELECT EXISTS (
    SELECT 1 FROM combatants AS cb
    JOIN encounters AS e ON e.id = cb.encounter_id
    JOIN game_sessions AS gs ON gs.id = e.game_session_id
    WHERE gs.campaign_id = $1::UUID
      AND e.status <> 'ended'
      AND cb.character_id = $2::UUID
)
`

type CharacterIsInOpenCombatParams struct {
	CampaignID  string
	CharacterID string
}

// Whether the character is a combatant (dismissed or not) of the campaign's combat that
// is not ended. A character cannot go back to the reserve (MR-049) while one is.
func (q *Queries) CharacterIsInOpenCombat(ctx context.Context, arg CharacterIsInOpenCombatParams) (bool, error) {
	row := q.db.QueryRow(ctx, characterIsInOpenCombat, arg.CampaignID, arg.CharacterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
