// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package playdb

import (
	"time"
)

type BattleEncounter struct {
	MapPointID string
	CampaignID string
	MapID      string
	Encounter  []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type CharacterEffect struct {
	ID                 string
	CampaignID         string
	CharacterID        string
	SourceCharacterID  *string
	GroupID            string
	SourceKey          string
	SourceKind         string
	Concentration      bool
	ConditionKeys      []string
	Modifiers          []byte
	DurationKind       string
	SecondsLeft        *int32
	EndSaveAbility     *string
	StartSaveAbility   *string
	SaveDc             *int32
	OnFailEffect       *string
	FollowsKey         *string
	TriggerDice        *string
	TriggerDamageType  *string
	TriggerMaxTriggers *int32
	TriggersFired      int32
	PlayerVisible      bool
	Audience           string
	PlayerLabel        *string
	CreatedAt          time.Time
}

type CombatContest struct {
	ID            string
	EncounterID   string
	Kind          string
	Purpose       string
	InitiatorID   string
	DefenderID    string
	Status        string
	EscapeDc      *int32
	InitiatorRoll []byte
	DefenderRoll  []byte
	Winner        *string
	ShoveOutcome  *string
	Round         int32
	CreatedAt     time.Time
	ResolvedAt    *time.Time
}

type CombatHelp struct {
	ID                string
	GameSessionID     string
	EncounterID       *string
	Kind              string
	HelperCharacterID string
	AllyCharacterID   string
	Task              *string
	TargetID          *string
	ExpiresRound      *int32
	CreatedRound      *int32
	CreatedAt         time.Time
	ConsumedAt        *time.Time
	ClearedAt         *time.Time
	HelperCombatantID *string
	AllyCombatantID   *string
}

type CombatHideAttempt struct {
	ID          string
	EncounterID string
	HiderID     string
	Status      string
	Roll        []byte
	Refusal     *string
	Round       int32
	CreatedAt   time.Time
	ResolvedAt  *time.Time
}

type CombatHiding struct {
	HiderID     string
	ObserverID  string
	EncounterID string
	Noticed     bool
	Total       int32
	Passive     int32
	CreatedAt   time.Time
}

type CombatHold struct {
	GrappledID  string
	EncounterID string
	GrapplerID  string
	EscapeDc    *int32
	CreatedAt   time.Time
}

type CombatReason struct {
	ID          string
	EncounterID string
	Kind        string
	Reason      string
	CreatedAt   time.Time
}

type CombatSurprised struct {
	CombatantID string
	EncounterID string
	CreatedAt   time.Time
}

type Combatant struct {
	ID                      string
	EncounterID             string
	CharacterID             string
	UserID                  *string
	Label                   string
	Kind                    string
	Hidden                  bool
	Initiative              *int32
	InitiativeBonus         int32
	InitiativeFace          *int32
	TieOrdered              bool
	OrderIndex              int32
	GridCol                 *int32
	GridRow                 *int32
	SpeedFt                 int32
	MovementUsedFt          int32
	Dashed                  bool
	ActionUsed              bool
	BonusActionUsed         bool
	ReactionUsed            bool
	HpCurrent               *int32
	HpMax                   *int32
	HpTemp                  *int32
	Defeated                bool
	DeathSuccesses          int32
	DeathFailures           int32
	Conditions              []string
	ConcentrationSpell      *string
	CreatedAt               time.Time
	AttacksMade             int32
	AcBonus                 int32
	DeathSaveRolled         bool
	XpValue                 int32
	TurnState               string
	MovementUsedDft         int32
	LastMoveDft             int32
	Side                    string
	Size                    string
	SpeedFlyFt              int32
	JumpLongDft             int32
	JumpHighDft             int32
	CoverMark               string
	Disengaged              bool
	CreatureID              *string
	MonsterKey              *string
	SummonAttack            *string
	SummonGroupID           *string
	Dismissed               bool
	ActionSurged            bool
	SpellCast               bool
	BonusSpellCast          bool
	ActionAttackKey         *string
	BonusAttacksLeft        int32
	HpMaxBonus              int32
	MageArmorAc             *int32
	AttackedHostile         bool
	TookDamage              bool
	RageEndPending          bool
	ConditionSources        []byte
	SneakAttackTurn         *string
	ColossusSlayerTurn      *string
	InspirationSides        *int32
	InspirationFrom         *string
	InspirationExpiresRound *int32
	SlotsUsed               []byte
	DeathRound              *int32
	DeathOrderIndex         *int32
	RevivifyBlocked         bool
	EffectConditions        []string
	EffectAcBonus           int32
	EffectSpeedPct          int32
	EffectSpeedAddFt        int32
	EffectNoAction          bool
	EffectNoMove            bool
	ExtraActionUsed         bool
	ExhaustionLevel         int32
	HpMaxBase               *int32
}

type CombatantState struct {
	ID                 string
	EncounterID        string
	CombatantID        string
	Kind               string
	SourceID           *string
	EndsCombatantID    *string
	EndsPhase          *string
	EndsRound          *int32
	StartedRound       int32
	Amount             int32
	CreatedAt          time.Time
	GroupID            *string
	SourceKey          *string
	SourceKind         *string
	Concentration      bool
	ConditionKeys      []string
	Modifiers          []byte
	DurationKind       *string
	EndSaveAbility     *string
	StartSaveAbility   *string
	SaveDc             *int32
	OnFailEffect       *string
	FollowsKey         *string
	TriggerDice        *string
	TriggerDamageType  *string
	TriggerMaxTriggers *int32
	TriggersFired      int32
	PlayerVisible      bool
	Audience           string
	PlayerLabel        *string
}

type Encounter struct {
	ID                 string
	GameSessionID      string
	MapID              *string
	MapPointID         *string
	Name               string
	Status             string
	Round              int32
	CurrentCombatantID *string
	GridColumns        int32
	GridRows           int32
	Revision           int32
	CreatedAt          time.Time
	StartedAt          *time.Time
	EndedAt            *time.Time
	Mode               string
}

type GameSession struct {
	ID               string
	CampaignID       string
	SessionNumber    int32
	StartedAt        time.Time
	EndedAt          *time.Time
	CurrentMapID     *string
	ShownImageID     *string
	ShownImageKeep   bool
	OpenScenePointID *string
	CreateKey        *string
	CreateHash       *string
}

type GroupCheck struct {
	ID            string
	GameSessionID string
	SkillKey      string
	Dc            *int32
	ShowDc        bool
	Status        string
	Passed        *bool
	CreatedAt     time.Time
	ClosedAt      *time.Time
}

type GroupCheckMember struct {
	GroupCheckID   string
	CharacterID    string
	Roll           []byte
	RolledByMaster bool
	RolledAt       *time.Time
}

type HiddenReveal struct {
	ID           string
	EncounterID  string
	CasterID     string
	SpellKey     string
	CombatantIds []string
	OriginCol    int32
	OriginRow    int32
	Squares      []int32
	Seq          int32
	State        string
	CreatedAt    time.Time
	AnsweredAt   *time.Time
}

type OpportunityOffer struct {
	ID              string
	EncounterID     string
	MoveID          string
	MoverID         string
	ReactorID       string
	LeftCol         *int32
	LeftRow         *int32
	State           string
	AttackPendingID *string
	CreatedAt       time.Time
	AnsweredAt      *time.Time
	Jumped          bool
}

type PendingDamage struct {
	ID               string
	EncounterID      string
	AttackerID       *string
	TargetID         string
	AttackKey        string
	Status           string
	Critical         bool
	DiceCount        int32
	DiceSides        int32
	DiceBonus        int32
	DamageType       string
	Faces            []int32
	Physical         bool
	Amount           *int32
	CreatedAt        time.Time
	ResolvedAt       *time.Time
	CastID           *string
	Healing          bool
	Half             bool
	AppliedAmount    *int32
	AttackTotal      *int32
	RollTotal        *int32
	AttackArmorClass *int32
	TrapPointID      *string
	CriticalMax      int32
	CriticalMaxRule  bool
	Taken            *int32
	ExtraDice        int32
	Parts            []byte
	PartRolls        []byte
	Steps            []byte
	LandedBefore     []byte
	AfterSteps       *int32
	EffectSourceKey  *string
}

type Puzzle struct {
	ID           string
	CampaignID   string
	Kind         string
	Name         string
	Config       []byte
	Solution     []byte
	Seed         int64
	Start        []byte
	MinimumMoves *int32
	Clue         string
	Hints        []byte
	SolveAction  string
	SolveTarget  []byte
	ArchivedAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	HintSkill    *string
	HintDc       *int32
	Parts        []byte
	OnWrong      []byte
	CreateKey    *string
	CreateHash   *string
}

type PuzzleHintTry struct {
	ID             string
	RunID          string
	UserID         *string
	CharacterID    *string
	IdempotencyKey string
	HintIndex      int32
	Passed         bool
	GrantedCount   *int32
	D20            int32
	Modifier       int32
	Total          int32
	Physical       bool
	CreatedAt      time.Time
	D20B           int32
	Counted        int32
	RollMode       string
}

type PuzzleMove struct {
	ID             string
	RunID          string
	Seq            int32
	UserID         *string
	CharacterID    *string
	IdempotencyKey string
	Move           []byte
	Revision       int32
	Solved         bool
	CreatedAt      time.Time
	Wrong          bool
}

type PuzzleRun struct {
	ID                   string
	GameSessionID        string
	PuzzleID             string
	Seed                 int64
	Start                []byte
	State                []byte
	ReleasedHints        int32
	ShownAt              *time.Time
	ClosedAt             *time.Time
	SolvedAt             *time.Time
	SolvedByCharacterID  *string
	SolveOutcome         *string
	LastMoverCharacterID *string
	LastMove             []byte
	LastMovedAt          *time.Time
	MovesMade            int32
	Revision             int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
	SolveMessage         *string
	Plays                int32
	PlayStartedAt        *time.Time
	RoundStartSeq        int32
	RoundStartedAt       *time.Time
}

type ReactionHold struct {
	ID            string
	EncounterID   string
	GroupID       string
	Kind          string
	ActorID       string
	ActorUserID   string
	ActorIsMaster bool
	Request       []byte
	Data          []byte
	State         string
	CreatedAt     time.Time
}

type ReactionWindow struct {
	ID              string
	EncounterID     string
	Seq             int64
	GroupID         string
	Kind            string
	Status          string
	ClosedReason    *string
	ReactorID       *string
	PendingDamageID *string
	HoldID          *string
	Step            int32
	Trigger         []byte
	Outcome         []byte
	CreatedAt       time.Time
	AnsweredAt      *time.Time
}

type RevivifyRequest struct {
	ID                string
	CampaignID        string
	GameSessionID     string
	CasterCharacterID string
	TargetCharacterID string
	RequestedByUserID *string
	SlotLevel         int32
	SlotPact          bool
	Status            string
	CreatedAt         time.Time
	AnsweredAt        *time.Time
	CreateKey         *string
	CreateHash        *string
	AnswerKey         *string
	AnswerHash        *string
}

type RollHold struct {
	ID             string
	EncounterID    string
	CombatantID    string
	IdempotencyKey string
	Request        []byte
	Face           int32
	Modifier       int32
	Round          int32
	AnswerKey      *string
	CreatedAt      time.Time
}

type RollModeRequest struct {
	ID            string
	EncounterID   string
	CombatantID   string
	TargetID      string
	AttackKey     string
	SuggestedMode string
	RequestedMode string
	DecidedMode   *string
	Status        string
	Reason        string
	CreatedAt     time.Time
	AnsweredAt    *time.Time
}

type SpellCast struct {
	ID                 string
	CampaignID         string
	GameSessionID      string
	CasterID           string
	SpellKey           string
	Ritual             bool
	SlotLevel          int32
	SlotPact           bool
	Status             string
	EndReason          *string
	Concentrating      bool
	CastingMinutes     int32
	Lasts              bool
	DurationSeconds    *int32
	RestEnds           *string
	Secret             bool
	Targets            []byte
	DiceCount          int32
	DiceSides          int32
	RollFaces          []int32
	RollTotal          int32
	Physical           bool
	CreatureIds        []string
	CarriedEncounterID *string
	StartedAt          time.Time
	CastAt             *time.Time
	EndedAt            *time.Time
}

type StageNpc struct {
	ID            string
	GameSessionID string
	CharacterID   string
	Position      int32
	Speaking      bool
	CreatedAt     time.Time
}

type TrapDamage struct {
	ID            string
	GameSessionID string
	TrapPointID   string
	FireID        string
	CharacterID   string
	Status        string
	Critical      bool
	DiceCount     int32
	DiceSides     int32
	DiceBonus     int32
	DamageType    string
	Faces         []int32
	RollTotal     int32
	Half          bool
	Amount        int32
	AppliedAmount *int32
	CreatedAt     time.Time
	ResolvedAt    *time.Time
	CriticalMax   int32
	SettleKey     *string
	SettleHash    *string
}
