// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package playdb

import (
	"time"
)

type Combatant struct {
	ID                 string
	EncounterID        string
	CharacterID        string
	UserID             *string
	Label              string
	Kind               string
	Hidden             bool
	Initiative         *int32
	InitiativeBonus    int32
	InitiativeFace     *int32
	TieOrdered         bool
	OrderIndex         int32
	GridCol            *int32
	GridRow            *int32
	SpeedFt            int32
	MovementUsedFt     int32
	Dashed             bool
	ActionUsed         bool
	BonusActionUsed    bool
	ReactionUsed       bool
	HpCurrent          *int32
	HpMax              *int32
	HpTemp             *int32
	Defeated           bool
	DeathSuccesses     int32
	DeathFailures      int32
	Conditions         []string
	ConcentrationSpell *string
	CreatedAt          time.Time
	AttacksMade        int32
	AcBonus            int32
	DeathSaveRolled    bool
}

type Encounter struct {
	ID                 string
	GameSessionID      string
	MapID              *string
	MapPointID         *string
	Name               string
	Status             string
	Round              int32
	CurrentCombatantID *string
	GridColumns        int32
	GridRows           int32
	Revision           int32
	CreatedAt          time.Time
	StartedAt          *time.Time
	EndedAt            *time.Time
}

type GameSession struct {
	ID               string
	CampaignID       string
	SessionNumber    int32
	StartedAt        time.Time
	EndedAt          *time.Time
	CurrentMapID     *string
	ShownImageID     *string
	ShownImageKeep   bool
	OpenScenePointID *string
}

type PendingDamage struct {
	ID            string
	EncounterID   string
	AttackerID    string
	TargetID      string
	AttackKey     string
	Status        string
	Critical      bool
	DiceCount     int32
	DiceSides     int32
	DiceBonus     int32
	DamageType    string
	Faces         []int32
	Physical      bool
	Amount        *int32
	CreatedAt     time.Time
	ResolvedAt    *time.Time
	CastID        *string
	Healing       bool
	Half          bool
	AppliedAmount *int32
	AttackTotal   *int32
	RollTotal     *int32
}
