// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package playdb

import (
	"time"
)

type GameSession struct {
	ID            string
	CampaignID    string
	SessionNumber int32
	StartedAt     time.Time
	EndedAt       *time.Time
}
