// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package playdb

import (
	"context"
	"time"
)

const endGameSession = `-- name: EndGameSession :one
UPDATE game_sessions
SET ended_at = COALESCE(ended_at, GREATEST($3::TIMESTAMPTZ, started_at))
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, session_number, started_at, ended_at
`

type EndGameSessionParams struct {
	CampaignID string
	ID         string
	Now        time.Time
}

// Ending a session twice keeps the first ended_at, so the call is
// idempotent. GREATEST keeps ended_at from being before started_at if two
// servers' clocks disagree by a little (game_sessions_ends_after_start).
func (q *Queries) EndGameSession(ctx context.Context, arg EndGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, endGameSession, arg.CampaignID, arg.ID, arg.Now)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getOpenGameSession = `-- name: GetOpenGameSession :one
SELECT id, campaign_id, session_number, started_at, ended_at FROM game_sessions
WHERE campaign_id = $1 AND ended_at IS NULL
`

// The campaign's open session, if any. The partial unique index
// game_sessions_one_open_per_campaign allows at most one.
func (q *Queries) GetOpenGameSession(ctx context.Context, campaignID string) (GameSession, error) {
	row := q.db.QueryRow(ctx, getOpenGameSession, campaignID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const insertGameSession = `-- name: InsertGameSession :one
INSERT INTO game_sessions (campaign_id, session_number, started_at)
VALUES ($1, $2, $3)
RETURNING id, campaign_id, session_number, started_at, ended_at
`

type InsertGameSessionParams struct {
	CampaignID    string
	SessionNumber int32
	StartedAt     time.Time
}

func (q *Queries) InsertGameSession(ctx context.Context, arg InsertGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, insertGameSession, arg.CampaignID, arg.SessionNumber, arg.StartedAt)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listGameSessions = `-- name: ListGameSessions :many
SELECT id, campaign_id, session_number, started_at, ended_at FROM game_sessions
WHERE campaign_id = $1
ORDER BY session_number DESC
`

// Newest first.
func (q *Queries) ListGameSessions(ctx context.Context, campaignID string) ([]GameSession, error) {
	rows, err := q.db.Query(ctx, listGameSessions, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SessionNumber,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSessionNumber = `-- name: NextSessionNumber :one
SELECT (COALESCE(max(session_number), 0) + 1)::INT4 AS next
FROM game_sessions
WHERE campaign_id = $1
`

// Sessions count from 1. Two starts racing both read the same number;
// CockroachDB's SERIALIZABLE isolation makes one of them retry, and the
// UNIQUE (campaign_id, session_number) constraint is the backstop.
func (q *Queries) NextSessionNumber(ctx context.Context, campaignID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSessionNumber, campaignID)
	var next int32
	err := row.Scan(&next)
	return next, err
}
