// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_casting.sql

package playdb

import (
	"context"
	"time"
)

const clearMageArmorACOfCharacter = `-- name: ClearMageArmorACOfCharacter :exec
UPDATE combatants
SET mage_armor_ac = NULL
WHERE character_id = $1 AND mage_armor_ac IS NOT NULL
  AND encounter_id IN (SELECT id FROM encounters WHERE status <> 'ended')
`

// Mage Armor ended: take it off the character's combatants in the combats that are not ended.
func (q *Queries) ClearMageArmorACOfCharacter(ctx context.Context, characterID string) error {
	_, err := q.db.Exec(ctx, clearMageArmorACOfCharacter, characterID)
	return err
}

const endSpellCast = `-- name: EndSpellCast :one
UPDATE spell_casts
SET status = $2, end_reason = $3, ended_at = $4, concentrating = false, carried_encounter_id = NULL
WHERE id = $1
RETURNING id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at
`

type EndSpellCastParams struct {
	ID        string
	Status    string
	EndReason *string
	EndedAt   *time.Time
}

// A cast is over: ended (it took effect) or failed (it did not finish).
func (q *Queries) EndSpellCast(ctx context.Context, arg EndSpellCastParams) (SpellCast, error) {
	row := q.db.QueryRow(ctx, endSpellCast,
		arg.ID,
		arg.Status,
		arg.EndReason,
		arg.EndedAt,
	)
	var i SpellCast
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GameSessionID,
		&i.CasterID,
		&i.SpellKey,
		&i.Ritual,
		&i.SlotLevel,
		&i.SlotPact,
		&i.Status,
		&i.EndReason,
		&i.Concentrating,
		&i.CastingMinutes,
		&i.Lasts,
		&i.DurationSeconds,
		&i.RestEnds,
		&i.Secret,
		&i.Targets,
		&i.DiceCount,
		&i.DiceSides,
		&i.RollFaces,
		&i.RollTotal,
		&i.Physical,
		&i.CreatureIds,
		&i.CarriedEncounterID,
		&i.StartedAt,
		&i.CastAt,
		&i.EndedAt,
	)
	return i, err
}

const finishSpellCast = `-- name: FinishSpellCast :one
UPDATE spell_casts
SET status = $2, end_reason = $3, ended_at = $4, concentrating = $5, targets = $6,
    dice_count = $7, dice_sides = $8, roll_faces = $9, roll_total = $10, physical = $11,
    creature_ids = $12, cast_at = $13, slot_level = $14, slot_pact = $15
WHERE id = $1
RETURNING id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at
`

type FinishSpellCastParams struct {
	ID            string
	Status        string
	EndReason     *string
	EndedAt       *time.Time
	Concentrating bool
	Targets       []byte
	DiceCount     int32
	DiceSides     int32
	RollFaces     []int32
	RollTotal     int32
	Physical      bool
	CreatureIds   []string
	CastAt        *time.Time
	SlotLevel     int32
	SlotPact      bool
}

// The casting is done and the spell took effect: it lasts (active) or it is over
// (ended), with what it did.
func (q *Queries) FinishSpellCast(ctx context.Context, arg FinishSpellCastParams) (SpellCast, error) {
	row := q.db.QueryRow(ctx, finishSpellCast,
		arg.ID,
		arg.Status,
		arg.EndReason,
		arg.EndedAt,
		arg.Concentrating,
		arg.Targets,
		arg.DiceCount,
		arg.DiceSides,
		arg.RollFaces,
		arg.RollTotal,
		arg.Physical,
		arg.CreatureIds,
		arg.CastAt,
		arg.SlotLevel,
		arg.SlotPact,
	)
	var i SpellCast
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GameSessionID,
		&i.CasterID,
		&i.SpellKey,
		&i.Ritual,
		&i.SlotLevel,
		&i.SlotPact,
		&i.Status,
		&i.EndReason,
		&i.Concentrating,
		&i.CastingMinutes,
		&i.Lasts,
		&i.DurationSeconds,
		&i.RestEnds,
		&i.Secret,
		&i.Targets,
		&i.DiceCount,
		&i.DiceSides,
		&i.RollFaces,
		&i.RollTotal,
		&i.Physical,
		&i.CreatureIds,
		&i.CarriedEncounterID,
		&i.StartedAt,
		&i.CastAt,
		&i.EndedAt,
	)
	return i, err
}

const getSpellCast = `-- name: GetSpellCast :one
SELECT id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at FROM spell_casts
WHERE id = $1 AND campaign_id = $2
`

type GetSpellCastParams struct {
	ID         string
	CampaignID string
}

func (q *Queries) GetSpellCast(ctx context.Context, arg GetSpellCastParams) (SpellCast, error) {
	row := q.db.QueryRow(ctx, getSpellCast, arg.ID, arg.CampaignID)
	var i SpellCast
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GameSessionID,
		&i.CasterID,
		&i.SpellKey,
		&i.Ritual,
		&i.SlotLevel,
		&i.SlotPact,
		&i.Status,
		&i.EndReason,
		&i.Concentrating,
		&i.CastingMinutes,
		&i.Lasts,
		&i.DurationSeconds,
		&i.RestEnds,
		&i.Secret,
		&i.Targets,
		&i.DiceCount,
		&i.DiceSides,
		&i.RollFaces,
		&i.RollTotal,
		&i.Physical,
		&i.CreatureIds,
		&i.CarriedEncounterID,
		&i.StartedAt,
		&i.CastAt,
		&i.EndedAt,
	)
	return i, err
}

const insertSpellCast = `-- name: InsertSpellCast :one

INSERT INTO spell_casts (
    campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, concentrating,
    casting_minutes, lasts, duration_seconds, rest_ends, secret, started_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15
)
RETURNING id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at
`

type InsertSpellCastParams struct {
	CampaignID      string
	GameSessionID   string
	CasterID        string
	SpellKey        string
	Ritual          bool
	SlotLevel       int32
	SlotPact        bool
	Status          string
	Concentrating   bool
	CastingMinutes  int32
	Lasts           bool
	DurationSeconds *int32
	RestEnds        *string
	Secret          bool
	StartedAt       time.Time
}

// The spells cast outside a combat (casting.go). Every write below runs after the
// caller locked the open session's row.
func (q *Queries) InsertSpellCast(ctx context.Context, arg InsertSpellCastParams) (SpellCast, error) {
	row := q.db.QueryRow(ctx, insertSpellCast,
		arg.CampaignID,
		arg.GameSessionID,
		arg.CasterID,
		arg.SpellKey,
		arg.Ritual,
		arg.SlotLevel,
		arg.SlotPact,
		arg.Status,
		arg.Concentrating,
		arg.CastingMinutes,
		arg.Lasts,
		arg.DurationSeconds,
		arg.RestEnds,
		arg.Secret,
		arg.StartedAt,
	)
	var i SpellCast
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.GameSessionID,
		&i.CasterID,
		&i.SpellKey,
		&i.Ritual,
		&i.SlotLevel,
		&i.SlotPact,
		&i.Status,
		&i.EndReason,
		&i.Concentrating,
		&i.CastingMinutes,
		&i.Lasts,
		&i.DurationSeconds,
		&i.RestEnds,
		&i.Secret,
		&i.Targets,
		&i.DiceCount,
		&i.DiceSides,
		&i.RollFaces,
		&i.RollTotal,
		&i.Physical,
		&i.CreatureIds,
		&i.CarriedEncounterID,
		&i.StartedAt,
		&i.CastAt,
		&i.EndedAt,
	)
	return i, err
}

const listCarriedSpellCasts = `-- name: ListCarriedSpellCasts :many
SELECT id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at FROM spell_casts
WHERE carried_encounter_id = $1 AND status IN ('casting', 'active')
`

// The casts whose concentration a combat's combatants hold now.
func (q *Queries) ListCarriedSpellCasts(ctx context.Context, carriedEncounterID *string) ([]SpellCast, error) {
	rows, err := q.db.Query(ctx, listCarriedSpellCasts, carriedEncounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellCast
	for rows.Next() {
		var i SpellCast
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GameSessionID,
			&i.CasterID,
			&i.SpellKey,
			&i.Ritual,
			&i.SlotLevel,
			&i.SlotPact,
			&i.Status,
			&i.EndReason,
			&i.Concentrating,
			&i.CastingMinutes,
			&i.Lasts,
			&i.DurationSeconds,
			&i.RestEnds,
			&i.Secret,
			&i.Targets,
			&i.DiceCount,
			&i.DiceSides,
			&i.RollFaces,
			&i.RollTotal,
			&i.Physical,
			&i.CreatureIds,
			&i.CarriedEncounterID,
			&i.StartedAt,
			&i.CastAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSpellCasts = `-- name: ListLiveSpellCasts :many
SELECT id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at FROM spell_casts
WHERE campaign_id = $1 AND status IN ('casting', 'active')
ORDER BY started_at, id
`

// The casts going or lasting in the campaign, oldest first. They last from one session
// to the next, until something ends them.
func (q *Queries) ListLiveSpellCasts(ctx context.Context, campaignID string) ([]SpellCast, error) {
	rows, err := q.db.Query(ctx, listLiveSpellCasts, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellCast
	for rows.Next() {
		var i SpellCast
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GameSessionID,
			&i.CasterID,
			&i.SpellKey,
			&i.Ritual,
			&i.SlotLevel,
			&i.SlotPact,
			&i.Status,
			&i.EndReason,
			&i.Concentrating,
			&i.CastingMinutes,
			&i.Lasts,
			&i.DurationSeconds,
			&i.RestEnds,
			&i.Secret,
			&i.Targets,
			&i.DiceCount,
			&i.DiceSides,
			&i.RollFaces,
			&i.RollTotal,
			&i.Physical,
			&i.CreatureIds,
			&i.CarriedEncounterID,
			&i.StartedAt,
			&i.CastAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSpellCastsOfCaster = `-- name: ListLiveSpellCastsOfCaster :many
SELECT id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at FROM spell_casts
WHERE caster_id = $1 AND status IN ('casting', 'active')
ORDER BY started_at, id
`

func (q *Queries) ListLiveSpellCastsOfCaster(ctx context.Context, casterID string) ([]SpellCast, error) {
	rows, err := q.db.Query(ctx, listLiveSpellCastsOfCaster, casterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellCast
	for rows.Next() {
		var i SpellCast
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GameSessionID,
			&i.CasterID,
			&i.SpellKey,
			&i.Ritual,
			&i.SlotLevel,
			&i.SlotPact,
			&i.Status,
			&i.EndReason,
			&i.Concentrating,
			&i.CastingMinutes,
			&i.Lasts,
			&i.DurationSeconds,
			&i.RestEnds,
			&i.Secret,
			&i.Targets,
			&i.DiceCount,
			&i.DiceSides,
			&i.RollFaces,
			&i.RollTotal,
			&i.Physical,
			&i.CreatureIds,
			&i.CarriedEncounterID,
			&i.StartedAt,
			&i.CastAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSpellCastsOfCasters = `-- name: ListLiveSpellCastsOfCasters :many
SELECT id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at FROM spell_casts
WHERE caster_id = ANY($1::UUID[]) AND status IN ('casting', 'active')
ORDER BY started_at, id
`

// The live casts of several casters: what a combat's start carries.
func (q *Queries) ListLiveSpellCastsOfCasters(ctx context.Context, casterIds []string) ([]SpellCast, error) {
	rows, err := q.db.Query(ctx, listLiveSpellCastsOfCasters, casterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellCast
	for rows.Next() {
		var i SpellCast
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GameSessionID,
			&i.CasterID,
			&i.SpellKey,
			&i.Ritual,
			&i.SlotLevel,
			&i.SlotPact,
			&i.Status,
			&i.EndReason,
			&i.Concentrating,
			&i.CastingMinutes,
			&i.Lasts,
			&i.DurationSeconds,
			&i.RestEnds,
			&i.Secret,
			&i.Targets,
			&i.DiceCount,
			&i.DiceSides,
			&i.RollFaces,
			&i.RollTotal,
			&i.Physical,
			&i.CreatureIds,
			&i.CarriedEncounterID,
			&i.StartedAt,
			&i.CastAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSpellCastsOnTarget = `-- name: ListLiveSpellCastsOnTarget :many
SELECT id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at FROM spell_casts
WHERE campaign_id = $1 AND status = 'active' AND targets @> $2::JSONB
ORDER BY started_at, id
`

type ListLiveSpellCastsOnTargetParams struct {
	CampaignID string
	Target     []byte
}

// The live casts that name the character among their targets (Mage Armor, Aid): what
// is still on a target when one of them ends.
func (q *Queries) ListLiveSpellCastsOnTarget(ctx context.Context, arg ListLiveSpellCastsOnTargetParams) ([]SpellCast, error) {
	rows, err := q.db.Query(ctx, listLiveSpellCastsOnTarget, arg.CampaignID, arg.Target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellCast
	for rows.Next() {
		var i SpellCast
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GameSessionID,
			&i.CasterID,
			&i.SpellKey,
			&i.Ritual,
			&i.SlotLevel,
			&i.SlotPact,
			&i.Status,
			&i.EndReason,
			&i.Concentrating,
			&i.CastingMinutes,
			&i.Lasts,
			&i.DurationSeconds,
			&i.RestEnds,
			&i.Secret,
			&i.Targets,
			&i.DiceCount,
			&i.DiceSides,
			&i.RollFaces,
			&i.RollTotal,
			&i.Physical,
			&i.CreatureIds,
			&i.CarriedEncounterID,
			&i.StartedAt,
			&i.CastAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSpellCasts = `-- name: ListSessionSpellCasts :many
SELECT id, campaign_id, game_session_id, caster_id, spell_key, ritual, slot_level, slot_pact, status, end_reason, concentrating, casting_minutes, lasts, duration_seconds, rest_ends, secret, targets, dice_count, dice_sides, roll_faces, roll_total, physical, creature_ids, carried_encounter_id, started_at, cast_at, ended_at FROM spell_casts
WHERE game_session_id = $1
ORDER BY started_at DESC, id DESC
LIMIT $2
`

type ListSessionSpellCastsParams struct {
	GameSessionID string
	Limit         int32
}

// The session's casts, newest first: the log.
func (q *Queries) ListSessionSpellCasts(ctx context.Context, arg ListSessionSpellCastsParams) ([]SpellCast, error) {
	rows, err := q.db.Query(ctx, listSessionSpellCasts, arg.GameSessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellCast
	for rows.Next() {
		var i SpellCast
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.GameSessionID,
			&i.CasterID,
			&i.SpellKey,
			&i.Ritual,
			&i.SlotLevel,
			&i.SlotPact,
			&i.Status,
			&i.EndReason,
			&i.Concentrating,
			&i.CastingMinutes,
			&i.Lasts,
			&i.DurationSeconds,
			&i.RestEnds,
			&i.Secret,
			&i.Targets,
			&i.DiceCount,
			&i.DiceSides,
			&i.RollFaces,
			&i.RollTotal,
			&i.Physical,
			&i.CreatureIds,
			&i.CarriedEncounterID,
			&i.StartedAt,
			&i.CastAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCombatantMageArmorAC = `-- name: SetCombatantMageArmorAC :exec
UPDATE combatants SET mage_armor_ac = $2 WHERE id = $1
`

type SetCombatantMageArmorACParams struct {
	ID          string
	MageArmorAc *int32
}

func (q *Queries) SetCombatantMageArmorAC(ctx context.Context, arg SetCombatantMageArmorACParams) error {
	_, err := q.db.Exec(ctx, setCombatantMageArmorAC, arg.ID, arg.MageArmorAc)
	return err
}

const setMageArmorACOfCharacter = `-- name: SetMageArmorACOfCharacter :exec
UPDATE combatants
SET mage_armor_ac = $2
WHERE character_id = $1
  AND encounter_id IN (SELECT id FROM encounters WHERE status <> 'ended')
`

type SetMageArmorACOfCharacterParams struct {
	CharacterID string
	MageArmorAc *int32
}

// Mage Armor is on the character: put it on its combatants in the combats that are not ended.
func (q *Queries) SetMageArmorACOfCharacter(ctx context.Context, arg SetMageArmorACOfCharacterParams) error {
	_, err := q.db.Exec(ctx, setMageArmorACOfCharacter, arg.CharacterID, arg.MageArmorAc)
	return err
}

const setSpellCastConcentration = `-- name: SetSpellCastConcentration :exec
UPDATE spell_casts
SET concentrating = $2, carried_encounter_id = $3
WHERE id = $1
`

type SetSpellCastConcentrationParams struct {
	ID                 string
	Concentrating      bool
	CarriedEncounterID *string
}

// Who holds the concentration: the cast (carried NULL) or the combatant of a combat.
func (q *Queries) SetSpellCastConcentration(ctx context.Context, arg SetSpellCastConcentrationParams) error {
	_, err := q.db.Exec(ctx, setSpellCastConcentration, arg.ID, arg.Concentrating, arg.CarriedEncounterID)
	return err
}

const setSpellCastDuration = `-- name: SetSpellCastDuration :exec
UPDATE spell_casts SET duration_seconds = $2 WHERE id = $1
`

type SetSpellCastDurationParams struct {
	ID              string
	DurationSeconds *int32
}

// The game time a cast has left, when a combat gives back the rounds an effect had left
// (6 seconds each).
func (q *Queries) SetSpellCastDuration(ctx context.Context, arg SetSpellCastDurationParams) error {
	_, err := q.db.Exec(ctx, setSpellCastDuration, arg.ID, arg.DurationSeconds)
	return err
}

const setSpellCastTargets = `-- name: SetSpellCastTargets :exec
UPDATE spell_casts SET targets = $2 WHERE id = $1
`

type SetSpellCastTargetsParams struct {
	ID      string
	Targets []byte
}

func (q *Queries) SetSpellCastTargets(ctx context.Context, arg SetSpellCastTargetsParams) error {
	_, err := q.db.Exec(ctx, setSpellCastTargets, arg.ID, arg.Targets)
	return err
}
