// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package playdb

import (
	"context"
	"time"
)

const clearPendingDamageRoll = `-- name: ClearPendingDamageRoll :one
UPDATE pending_damages
SET status = 'awaiting_roll', faces = '{}', physical = false, amount = NULL, resolved_at = NULL
WHERE id = $1
RETURNING id, encounter_id, attacker_id, target_id, attack_key, status, critical, dice_count, dice_sides, dice_bonus, damage_type, faces, physical, amount, created_at, resolved_at
`

// An undo of the damage roll: it waits to be rolled again.
func (q *Queries) ClearPendingDamageRoll(ctx context.Context, id string) (PendingDamage, error) {
	row := q.db.QueryRow(ctx, clearPendingDamageRoll, id)
	var i PendingDamage
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.AttackerID,
		&i.TargetID,
		&i.AttackKey,
		&i.Status,
		&i.Critical,
		&i.DiceCount,
		&i.DiceSides,
		&i.DiceBonus,
		&i.DamageType,
		&i.Faces,
		&i.Physical,
		&i.Amount,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const deleteCombatant = `-- name: DeleteCombatant :exec
DELETE FROM combatants
WHERE id = $1
`

func (q *Queries) DeleteCombatant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCombatant, id)
	return err
}

const deletePendingDamage = `-- name: DeletePendingDamage :exec
DELETE FROM pending_damages
WHERE id = $1
`

func (q *Queries) DeletePendingDamage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePendingDamage, id)
	return err
}

const endGameSession = `-- name: EndGameSession :one
UPDATE game_sessions
SET ended_at = COALESCE(ended_at, GREATEST($3::TIMESTAMPTZ, started_at))
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep
`

type EndGameSessionParams struct {
	CampaignID string
	ID         string
	Now        time.Time
}

// Ending a session twice keeps the first ended_at, so the call is
// idempotent. GREATEST keeps ended_at from being before started_at if two
// servers' clocks disagree by a little (game_sessions_ends_after_start).
func (q *Queries) EndGameSession(ctx context.Context, arg EndGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, endGameSession, arg.CampaignID, arg.ID, arg.Now)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
		&i.ShownImageKeep,
	)
	return i, err
}

const getEncounterInSession = `-- name: GetEncounterInSession :one
SELECT id, game_session_id, map_id, map_point_id, name, status, round, current_combatant_id, grid_columns, grid_rows, revision, created_at, started_at, ended_at FROM encounters
WHERE game_session_id = $1 AND id = $2
`

type GetEncounterInSessionParams struct {
	GameSessionID string
	ID            string
}

// A combat by its ID, if it is in the session (so a combat of another
// campaign matches no row).
func (q *Queries) GetEncounterInSession(ctx context.Context, arg GetEncounterInSessionParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, getEncounterInSession, arg.GameSessionID, arg.ID)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.GameSessionID,
		&i.MapID,
		&i.MapPointID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.CurrentCombatantID,
		&i.GridColumns,
		&i.GridRows,
		&i.Revision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getGameSessionForUpdate = `-- name: GetGameSessionForUpdate :one
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep FROM game_sessions
WHERE campaign_id = $1 AND id = $2
FOR UPDATE
`

type GetGameSessionForUpdateParams struct {
	CampaignID string
	ID         string
}

// One session of the campaign, locked until the transaction ends.
func (q *Queries) GetGameSessionForUpdate(ctx context.Context, arg GetGameSessionForUpdateParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, getGameSessionForUpdate, arg.CampaignID, arg.ID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
		&i.ShownImageKeep,
	)
	return i, err
}

const getLatestEncounter = `-- name: GetLatestEncounter :one

SELECT id, game_session_id, map_id, map_point_id, name, status, round, current_combatant_id, grid_columns, grid_rows, revision, created_at, started_at, ended_at FROM encounters
WHERE game_session_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Combat (MR-013). Every write below runs after the caller locked the open
// session's row (GetOpenGameSessionForUpdate), so two changes to a combat take
// turns, as for the vitals.
// The session's latest combat, ended or not: GetEncounter shows it, so the app
// can also show the end of a combat that just ended.
func (q *Queries) GetLatestEncounter(ctx context.Context, gameSessionID string) (Encounter, error) {
	row := q.db.QueryRow(ctx, getLatestEncounter, gameSessionID)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.GameSessionID,
		&i.MapID,
		&i.MapPointID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.CurrentCombatantID,
		&i.GridColumns,
		&i.GridRows,
		&i.Revision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getOnScreen = `-- name: GetOnScreen :one
SELECT current_map_id, shown_image_id FROM game_sessions
WHERE campaign_id = $1 AND ended_at IS NULL
`

type GetOnScreenRow struct {
	CurrentMapID *string
	ShownImageID *string
}

// What the open session shows: its current map and the image the master
// shows (either NULL when none). No row: no open session.
func (q *Queries) GetOnScreen(ctx context.Context, campaignID string) (GetOnScreenRow, error) {
	row := q.db.QueryRow(ctx, getOnScreen, campaignID)
	var i GetOnScreenRow
	err := row.Scan(&i.CurrentMapID, &i.ShownImageID)
	return i, err
}

const getOpenEncounter = `-- name: GetOpenEncounter :one
SELECT id, game_session_id, map_id, map_point_id, name, status, round, current_combatant_id, grid_columns, grid_rows, revision, created_at, started_at, ended_at FROM encounters
WHERE game_session_id = $1 AND status <> 'ended'
`

// The session's combat that is not ended, if any. The partial unique index
// encounters_one_open_per_session allows at most one.
func (q *Queries) GetOpenEncounter(ctx context.Context, gameSessionID string) (Encounter, error) {
	row := q.db.QueryRow(ctx, getOpenEncounter, gameSessionID)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.GameSessionID,
		&i.MapID,
		&i.MapPointID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.CurrentCombatantID,
		&i.GridColumns,
		&i.GridRows,
		&i.Revision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getOpenGameSession = `-- name: GetOpenGameSession :one
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep FROM game_sessions
WHERE campaign_id = $1 AND ended_at IS NULL
`

// The campaign's open session, if any. The partial unique index
// game_sessions_one_open_per_campaign allows at most one.
func (q *Queries) GetOpenGameSession(ctx context.Context, campaignID string) (GameSession, error) {
	row := q.db.QueryRow(ctx, getOpenGameSession, campaignID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
		&i.ShownImageKeep,
	)
	return i, err
}

const getOpenGameSessionForUpdate = `-- name: GetOpenGameSessionForUpdate :one
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep FROM game_sessions
WHERE campaign_id = $1 AND ended_at IS NULL
FOR UPDATE
`

// GetOpenGameSession, locking the session's row until the transaction ends.
// Every change made during a session locks it first, so two changes at
// once take turns: each one reads the next event number after the other
// wrote its own, and EndGameSession waits for a change in progress.
func (q *Queries) GetOpenGameSessionForUpdate(ctx context.Context, campaignID string) (GameSession, error) {
	row := q.db.QueryRow(ctx, getOpenGameSessionForUpdate, campaignID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
		&i.ShownImageKeep,
	)
	return i, err
}

const getPendingDamage = `-- name: GetPendingDamage :one
SELECT id, encounter_id, attacker_id, target_id, attack_key, status, critical, dice_count, dice_sides, dice_bonus, damage_type, faces, physical, amount, created_at, resolved_at FROM pending_damages
WHERE encounter_id = $1 AND id = $2
`

type GetPendingDamageParams struct {
	EncounterID string
	ID          string
}

// A pending damage by its ID, if it is in the combat.
func (q *Queries) GetPendingDamage(ctx context.Context, arg GetPendingDamageParams) (PendingDamage, error) {
	row := q.db.QueryRow(ctx, getPendingDamage, arg.EncounterID, arg.ID)
	var i PendingDamage
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.AttackerID,
		&i.TargetID,
		&i.AttackKey,
		&i.Status,
		&i.Critical,
		&i.DiceCount,
		&i.DiceSides,
		&i.DiceBonus,
		&i.DamageType,
		&i.Faces,
		&i.Physical,
		&i.Amount,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getSessionEventByIdempotencyKey = `-- name: GetSessionEventByIdempotencyKey :one
SELECT id, seq, kind, character_id, payload FROM session_events
WHERE game_session_id = $1 AND idempotency_key = $2
`

type GetSessionEventByIdempotencyKeyParams struct {
	GameSessionID  string
	IdempotencyKey *string
}

type GetSessionEventByIdempotencyKeyRow struct {
	ID          string
	Seq         int32
	Kind        string
	CharacterID *string
	Payload     []byte
}

// The event a change with this key already wrote, if any.
func (q *Queries) GetSessionEventByIdempotencyKey(ctx context.Context, arg GetSessionEventByIdempotencyKeyParams) (GetSessionEventByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getSessionEventByIdempotencyKey, arg.GameSessionID, arg.IdempotencyKey)
	var i GetSessionEventByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Kind,
		&i.CharacterID,
		&i.Payload,
	)
	return i, err
}

const insertCombatant = `-- name: InsertCombatant :one
INSERT INTO combatants (
    encounter_id, character_id, user_id, label, kind, hidden, initiative, initiative_bonus, initiative_face,
    order_index, grid_col, grid_row, speed_ft, hp_current, hp_max, hp_temp, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, encounter_id, character_id, user_id, label, kind, hidden, initiative, initiative_bonus, initiative_face, tie_ordered, order_index, grid_col, grid_row, speed_ft, movement_used_ft, dashed, action_used, bonus_action_used, reaction_used, hp_current, hp_max, hp_temp, defeated, death_successes, death_failures, conditions, concentration_spell, created_at
`

type InsertCombatantParams struct {
	EncounterID     string
	CharacterID     string
	UserID          *string
	Label           string
	Kind            string
	Hidden          bool
	Initiative      *int32
	InitiativeBonus int32
	InitiativeFace  *int32
	OrderIndex      int32
	GridCol         *int32
	GridRow         *int32
	SpeedFt         int32
	HpCurrent       *int32
	HpMax           *int32
	HpTemp          *int32
	CreatedAt       time.Time
}

func (q *Queries) InsertCombatant(ctx context.Context, arg InsertCombatantParams) (Combatant, error) {
	row := q.db.QueryRow(ctx, insertCombatant,
		arg.EncounterID,
		arg.CharacterID,
		arg.UserID,
		arg.Label,
		arg.Kind,
		arg.Hidden,
		arg.Initiative,
		arg.InitiativeBonus,
		arg.InitiativeFace,
		arg.OrderIndex,
		arg.GridCol,
		arg.GridRow,
		arg.SpeedFt,
		arg.HpCurrent,
		arg.HpMax,
		arg.HpTemp,
		arg.CreatedAt,
	)
	var i Combatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.CharacterID,
		&i.UserID,
		&i.Label,
		&i.Kind,
		&i.Hidden,
		&i.Initiative,
		&i.InitiativeBonus,
		&i.InitiativeFace,
		&i.TieOrdered,
		&i.OrderIndex,
		&i.GridCol,
		&i.GridRow,
		&i.SpeedFt,
		&i.MovementUsedFt,
		&i.Dashed,
		&i.ActionUsed,
		&i.BonusActionUsed,
		&i.ReactionUsed,
		&i.HpCurrent,
		&i.HpMax,
		&i.HpTemp,
		&i.Defeated,
		&i.DeathSuccesses,
		&i.DeathFailures,
		&i.Conditions,
		&i.ConcentrationSpell,
		&i.CreatedAt,
	)
	return i, err
}

const insertEncounter = `-- name: InsertEncounter :one
INSERT INTO encounters (game_session_id, map_id, map_point_id, name, status, grid_columns, grid_rows, created_at)
VALUES ($1, $2, $3, $4, 'setup', $5, $6, $7)
RETURNING id, game_session_id, map_id, map_point_id, name, status, round, current_combatant_id, grid_columns, grid_rows, revision, created_at, started_at, ended_at
`

type InsertEncounterParams struct {
	GameSessionID string
	MapID         *string
	MapPointID    *string
	Name          string
	GridColumns   int32
	GridRows      int32
	CreatedAt     time.Time
}

// A new combat starts in setup, in round 0.
func (q *Queries) InsertEncounter(ctx context.Context, arg InsertEncounterParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, insertEncounter,
		arg.GameSessionID,
		arg.MapID,
		arg.MapPointID,
		arg.Name,
		arg.GridColumns,
		arg.GridRows,
		arg.CreatedAt,
	)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.GameSessionID,
		&i.MapID,
		&i.MapPointID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.CurrentCombatantID,
		&i.GridColumns,
		&i.GridRows,
		&i.Revision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const insertGameSession = `-- name: InsertGameSession :one
INSERT INTO game_sessions (campaign_id, session_number, started_at)
VALUES ($1, $2, $3)
RETURNING id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep
`

type InsertGameSessionParams struct {
	CampaignID    string
	SessionNumber int32
	StartedAt     time.Time
}

func (q *Queries) InsertGameSession(ctx context.Context, arg InsertGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, insertGameSession, arg.CampaignID, arg.SessionNumber, arg.StartedAt)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
		&i.ShownImageKeep,
	)
	return i, err
}

const insertPendingDamage = `-- name: InsertPendingDamage :one

INSERT INTO pending_damages (
    encounter_id, attacker_id, target_id, attack_key, status, critical,
    dice_count, dice_sides, dice_bonus, damage_type, created_at
) VALUES ($1, $2, $3, $4, 'awaiting_roll', $5, $6, $7, $8, $9, $10)
RETURNING id, encounter_id, attacker_id, target_id, attack_key, status, critical, dice_count, dice_sides, dice_bonus, damage_type, faces, physical, amount, created_at, resolved_at
`

type InsertPendingDamageParams struct {
	EncounterID string
	AttackerID  string
	TargetID    string
	AttackKey   string
	Critical    bool
	DiceCount   int32
	DiceSides   int32
	DiceBonus   int32
	DamageType  string
	CreatedAt   time.Time
}

// Pending damage (MR-012, MR-014): the damage of an attack that hit. Every write
// below runs after the caller locked the open session's row.
func (q *Queries) InsertPendingDamage(ctx context.Context, arg InsertPendingDamageParams) (PendingDamage, error) {
	row := q.db.QueryRow(ctx, insertPendingDamage,
		arg.EncounterID,
		arg.AttackerID,
		arg.TargetID,
		arg.AttackKey,
		arg.Critical,
		arg.DiceCount,
		arg.DiceSides,
		arg.DiceBonus,
		arg.DamageType,
		arg.CreatedAt,
	)
	var i PendingDamage
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.AttackerID,
		&i.TargetID,
		&i.AttackKey,
		&i.Status,
		&i.Critical,
		&i.DiceCount,
		&i.DiceSides,
		&i.DiceBonus,
		&i.DamageType,
		&i.Faces,
		&i.Physical,
		&i.Amount,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertSessionEvent = `-- name: InsertSessionEvent :one
INSERT INTO session_events
    (game_session_id, seq, kind, actor_user_id, character_id, payload, idempotency_key, created_at, encounter_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, seq
`

type InsertSessionEventParams struct {
	GameSessionID  string
	Seq            int32
	Kind           string
	ActorUserID    *string
	CharacterID    *string
	Payload        []byte
	IdempotencyKey *string
	CreatedAt      time.Time
	EncounterID    *string
}

type InsertSessionEventRow struct {
	ID  string
	Seq int32
}

func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) (InsertSessionEventRow, error) {
	row := q.db.QueryRow(ctx, insertSessionEvent,
		arg.GameSessionID,
		arg.Seq,
		arg.Kind,
		arg.ActorUserID,
		arg.CharacterID,
		arg.Payload,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.EncounterID,
	)
	var i InsertSessionEventRow
	err := row.Scan(&i.ID, &i.Seq)
	return i, err
}

const listCombatants = `-- name: ListCombatants :many
SELECT id, encounter_id, character_id, user_id, label, kind, hidden, initiative, initiative_bonus, initiative_face, tie_ordered, order_index, grid_col, grid_row, speed_ft, movement_used_ft, dashed, action_used, bonus_action_used, reaction_used, hp_current, hp_max, hp_temp, defeated, death_successes, death_failures, conditions, concentration_spell, created_at FROM combatants
WHERE encounter_id = $1
ORDER BY order_index, created_at, id
`

// The combat's combatants in turn order.
func (q *Queries) ListCombatants(ctx context.Context, encounterID string) ([]Combatant, error) {
	rows, err := q.db.Query(ctx, listCombatants, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Combatant
	for rows.Next() {
		var i Combatant
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.CharacterID,
			&i.UserID,
			&i.Label,
			&i.Kind,
			&i.Hidden,
			&i.Initiative,
			&i.InitiativeBonus,
			&i.InitiativeFace,
			&i.TieOrdered,
			&i.OrderIndex,
			&i.GridCol,
			&i.GridRow,
			&i.SpeedFt,
			&i.MovementUsedFt,
			&i.Dashed,
			&i.ActionUsed,
			&i.BonusActionUsed,
			&i.ReactionUsed,
			&i.HpCurrent,
			&i.HpMax,
			&i.HpTemp,
			&i.Defeated,
			&i.DeathSuccesses,
			&i.DeathFailures,
			&i.Conditions,
			&i.ConcentrationSpell,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterEvents = `-- name: ListEncounterEvents :many

SELECT id, seq, kind, actor_user_id, payload, created_at FROM session_events
WHERE encounter_id = $1
ORDER BY seq DESC
LIMIT $2
`

type ListEncounterEventsParams struct {
	EncounterID *string
	Limit       int32
}

type ListEncounterEventsRow struct {
	ID          string
	Seq         int32
	Kind        string
	ActorUserID *string
	Payload     []byte
	CreatedAt   time.Time
}

// The combat log and the undo read the session's events (ADR-0007).
// A combat's latest events, newest first: when a combat is longer than the
// limit, it is the oldest lines that fall off the log, never the newest (or the
// one an undo would take back). The caller reverses them.
func (q *Queries) ListEncounterEvents(ctx context.Context, arg ListEncounterEventsParams) ([]ListEncounterEventsRow, error) {
	rows, err := q.db.Query(ctx, listEncounterEvents, arg.EncounterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncounterEventsRow
	for rows.Next() {
		var i ListEncounterEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Kind,
			&i.ActorUserID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameSessions = `-- name: ListGameSessions :many
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep FROM game_sessions
WHERE campaign_id = $1
ORDER BY session_number DESC
`

// Newest first.
func (q *Queries) ListGameSessions(ctx context.Context, campaignID string) ([]GameSession, error) {
	rows, err := q.db.Query(ctx, listGameSessions, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SessionNumber,
			&i.StartedAt,
			&i.EndedAt,
			&i.CurrentMapID,
			&i.ShownImageID,
			&i.ShownImageKeep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenGameSessions = `-- name: ListOpenGameSessions :many
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep FROM game_sessions
WHERE campaign_id = ANY($1::UUID[]) AND ended_at IS NULL
ORDER BY started_at DESC, id
`

// The open sessions of the given campaigns, newest first (RN-06). The
// partial unique index game_sessions_one_open_per_campaign finds each one.
func (q *Queries) ListOpenGameSessions(ctx context.Context, campaignIds []string) ([]GameSession, error) {
	rows, err := q.db.Query(ctx, listOpenGameSessions, campaignIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SessionNumber,
			&i.StartedAt,
			&i.EndedAt,
			&i.CurrentMapID,
			&i.ShownImageID,
			&i.ShownImageKeep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPendingDamages = `-- name: ListOpenPendingDamages :many
SELECT id, encounter_id, attacker_id, target_id, attack_key, status, critical, dice_count, dice_sides, dice_bonus, damage_type, faces, physical, amount, created_at, resolved_at FROM pending_damages
WHERE encounter_id = $1 AND status IN ('awaiting_roll', 'rolled')
ORDER BY created_at, id
`

// What still waits to be rolled or applied in the combat, oldest first.
func (q *Queries) ListOpenPendingDamages(ctx context.Context, encounterID string) ([]PendingDamage, error) {
	rows, err := q.db.Query(ctx, listOpenPendingDamages, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingDamage
	for rows.Next() {
		var i PendingDamage
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.AttackerID,
			&i.TargetID,
			&i.AttackKey,
			&i.Status,
			&i.Critical,
			&i.DiceCount,
			&i.DiceSides,
			&i.DiceBonus,
			&i.DamageType,
			&i.Faces,
			&i.Physical,
			&i.Amount,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSessionEvents = `-- name: ListRecentSessionEvents :many
SELECT id, seq, kind, encounter_id, payload FROM session_events
WHERE game_session_id = $1
ORDER BY seq DESC
LIMIT $2
`

type ListRecentSessionEventsParams struct {
	GameSessionID string
	Limit         int32
}

type ListRecentSessionEventsRow struct {
	ID          string
	Seq         int32
	Kind        string
	EncounterID *string
	Payload     []byte
}

// The session's latest events, newest first (the undo looks for the last action).
func (q *Queries) ListRecentSessionEvents(ctx context.Context, arg ListRecentSessionEventsParams) ([]ListRecentSessionEventsRow, error) {
	rows, err := q.db.Query(ctx, listRecentSessionEvents, arg.GameSessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentSessionEventsRow
	for rows.Next() {
		var i ListRecentSessionEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Kind,
			&i.EncounterID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCombatantDashed = `-- name: MarkCombatantDashed :exec
UPDATE combatants
SET dashed = true
WHERE id = $1
`

func (q *Queries) MarkCombatantDashed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markCombatantDashed, id)
	return err
}

const nextSessionEventSeq = `-- name: NextSessionEventSeq :one
SELECT (COALESCE(max(seq), 0) + 1)::INT4 AS next
FROM session_events
WHERE game_session_id = $1
`

// Events count from 1 in each session. The caller holds the session's row
// lock (GetOpenGameSessionForUpdate), so no other change reads the same
// number; UNIQUE (game_session_id, seq) is the backstop.
func (q *Queries) NextSessionEventSeq(ctx context.Context, gameSessionID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSessionEventSeq, gameSessionID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const nextSessionNumber = `-- name: NextSessionNumber :one
SELECT (COALESCE(max(session_number), 0) + 1)::INT4 AS next
FROM game_sessions
WHERE campaign_id = $1
`

// Sessions count from 1. Two starts racing both read the same number;
// CockroachDB's SERIALIZABLE isolation makes one of them retry, and the
// UNIQUE (campaign_id, session_number) constraint is the backstop.
func (q *Queries) NextSessionNumber(ctx context.Context, campaignID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSessionNumber, campaignID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const resetCombatantTurn = `-- name: ResetCombatantTurn :exec
UPDATE combatants
SET movement_used_ft = 0, dashed = false, action_used = false, bonus_action_used = false, reaction_used = false
WHERE id = $1
`

// The start of a combatant's own turn: movement, action, bonus action, dash and
// reaction come back.
func (q *Queries) ResetCombatantTurn(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resetCombatantTurn, id)
	return err
}

const setCombatantEconomy = `-- name: SetCombatantEconomy :exec
UPDATE combatants
SET action_used = $2, bonus_action_used = $3, reaction_used = $4, dashed = $5
WHERE id = $1
`

type SetCombatantEconomyParams struct {
	ID              string
	ActionUsed      bool
	BonusActionUsed bool
	ReactionUsed    bool
	Dashed          bool
}

// The turn's economy as an action, or its undo, leaves it.
func (q *Queries) SetCombatantEconomy(ctx context.Context, arg SetCombatantEconomyParams) error {
	_, err := q.db.Exec(ctx, setCombatantEconomy,
		arg.ID,
		arg.ActionUsed,
		arg.BonusActionUsed,
		arg.ReactionUsed,
		arg.Dashed,
	)
	return err
}

const setCombatantHidden = `-- name: SetCombatantHidden :exec
UPDATE combatants
SET hidden = $2
WHERE id = $1
`

type SetCombatantHiddenParams struct {
	ID     string
	Hidden bool
}

func (q *Queries) SetCombatantHidden(ctx context.Context, arg SetCombatantHiddenParams) error {
	_, err := q.db.Exec(ctx, setCombatantHidden, arg.ID, arg.Hidden)
	return err
}

const setCombatantHitPoints = `-- name: SetCombatantHitPoints :exec
UPDATE combatants
SET hp_current = $2, hp_temp = $3, defeated = $4
WHERE id = $1
`

type SetCombatantHitPointsParams struct {
	ID        string
	HpCurrent *int32
	HpTemp    *int32
	Defeated  bool
}

// An NPC's hit points, temporary hit points and defeated flag (damage, healing,
// the master's hand, an undo).
func (q *Queries) SetCombatantHitPoints(ctx context.Context, arg SetCombatantHitPointsParams) error {
	_, err := q.db.Exec(ctx, setCombatantHitPoints,
		arg.ID,
		arg.HpCurrent,
		arg.HpTemp,
		arg.Defeated,
	)
	return err
}

const setCombatantInitiative = `-- name: SetCombatantInitiative :exec
UPDATE combatants
SET initiative = $2, initiative_face = $3, tie_ordered = false
WHERE id = $1
`

type SetCombatantInitiativeParams struct {
	ID             string
	Initiative     *int32
	InitiativeFace *int32
}

// A new roll breaks any tie order decided before (tie_ordered).
func (q *Queries) SetCombatantInitiative(ctx context.Context, arg SetCombatantInitiativeParams) error {
	_, err := q.db.Exec(ctx, setCombatantInitiative, arg.ID, arg.Initiative, arg.InitiativeFace)
	return err
}

const setCombatantOrder = `-- name: SetCombatantOrder :exec
UPDATE combatants
SET order_index = $2, tie_ordered = $3
WHERE id = $1
`

type SetCombatantOrderParams struct {
	ID         string
	OrderIndex int32
	TieOrdered bool
}

func (q *Queries) SetCombatantOrder(ctx context.Context, arg SetCombatantOrderParams) error {
	_, err := q.db.Exec(ctx, setCombatantOrder, arg.ID, arg.OrderIndex, arg.TieOrdered)
	return err
}

const setCombatantSquare = `-- name: SetCombatantSquare :exec
UPDATE combatants
SET grid_col = $2, grid_row = $3, movement_used_ft = $4
WHERE id = $1
`

type SetCombatantSquareParams struct {
	ID             string
	GridCol        *int32
	GridRow        *int32
	MovementUsedFt int32
}

func (q *Queries) SetCombatantSquare(ctx context.Context, arg SetCombatantSquareParams) error {
	_, err := q.db.Exec(ctx, setCombatantSquare,
		arg.ID,
		arg.GridCol,
		arg.GridRow,
		arg.MovementUsedFt,
	)
	return err
}

const setCurrentMap = `-- name: SetCurrentMap :one
UPDATE game_sessions
SET current_map_id = $1
WHERE id = $2
RETURNING id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep
`

type SetCurrentMapParams struct {
	CurrentMapID *string
	ID           string
}

// The caller holds the session's row lock (GetOpenGameSessionForUpdate).
func (q *Queries) SetCurrentMap(ctx context.Context, arg SetCurrentMapParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, setCurrentMap, arg.CurrentMapID, arg.ID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
		&i.ShownImageKeep,
	)
	return i, err
}

const setEncounterState = `-- name: SetEncounterState :one
UPDATE encounters
SET status = $1, round = $2, current_combatant_id = $3,
    started_at = $4, ended_at = $5, revision = revision + 1
WHERE id = $6
RETURNING id, game_session_id, map_id, map_point_id, name, status, round, current_combatant_id, grid_columns, grid_rows, revision, created_at, started_at, ended_at
`

type SetEncounterStateParams struct {
	Status             string
	Round              int32
	CurrentCombatantID *string
	StartedAt          *time.Time
	EndedAt            *time.Time
	ID                 string
}

// Where the combat is: its status, round and whose turn it is. Every change
// to a combat raises its revision, so a write that changes only combatants
// uses TouchEncounter.
func (q *Queries) SetEncounterState(ctx context.Context, arg SetEncounterStateParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, setEncounterState,
		arg.Status,
		arg.Round,
		arg.CurrentCombatantID,
		arg.StartedAt,
		arg.EndedAt,
		arg.ID,
	)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.GameSessionID,
		&i.MapID,
		&i.MapPointID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.CurrentCombatantID,
		&i.GridColumns,
		&i.GridRows,
		&i.Revision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const setPendingDamageRolled = `-- name: SetPendingDamageRolled :one
UPDATE pending_damages
SET status = $2, faces = $3, physical = $4, amount = $5, resolved_at = $6
WHERE id = $1
RETURNING id, encounter_id, attacker_id, target_id, attack_key, status, critical, dice_count, dice_sides, dice_bonus, damage_type, faces, physical, amount, created_at, resolved_at
`

type SetPendingDamageRolledParams struct {
	ID         string
	Status     string
	Faces      []int32
	Physical   bool
	Amount     *int32
	ResolvedAt *time.Time
}

// The roll of a pending damage: 'rolled' for a player's character (waits for
// the master), 'applied' for an NPC.
func (q *Queries) SetPendingDamageRolled(ctx context.Context, arg SetPendingDamageRolledParams) (PendingDamage, error) {
	row := q.db.QueryRow(ctx, setPendingDamageRolled,
		arg.ID,
		arg.Status,
		arg.Faces,
		arg.Physical,
		arg.Amount,
		arg.ResolvedAt,
	)
	var i PendingDamage
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.AttackerID,
		&i.TargetID,
		&i.AttackKey,
		&i.Status,
		&i.Critical,
		&i.DiceCount,
		&i.DiceSides,
		&i.DiceBonus,
		&i.DamageType,
		&i.Faces,
		&i.Physical,
		&i.Amount,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const setPendingDamageStatus = `-- name: SetPendingDamageStatus :one
UPDATE pending_damages
SET status = $2, resolved_at = $3
WHERE id = $1
RETURNING id, encounter_id, attacker_id, target_id, attack_key, status, critical, dice_count, dice_sides, dice_bonus, damage_type, faces, physical, amount, created_at, resolved_at
`

type SetPendingDamageStatusParams struct {
	ID         string
	Status     string
	ResolvedAt *time.Time
}

// Applied or discarded by the master, or back to where it was (an undo).
func (q *Queries) SetPendingDamageStatus(ctx context.Context, arg SetPendingDamageStatusParams) (PendingDamage, error) {
	row := q.db.QueryRow(ctx, setPendingDamageStatus, arg.ID, arg.Status, arg.ResolvedAt)
	var i PendingDamage
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.AttackerID,
		&i.TargetID,
		&i.AttackKey,
		&i.Status,
		&i.Critical,
		&i.DiceCount,
		&i.DiceSides,
		&i.DiceBonus,
		&i.DamageType,
		&i.Faces,
		&i.Physical,
		&i.Amount,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const setShownImage = `-- name: SetShownImage :one
UPDATE game_sessions
SET shown_image_id = $1, shown_image_keep = $2
WHERE id = $3
RETURNING id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id, shown_image_keep
`

type SetShownImageParams struct {
	ShownImageID   *string
	ShownImageKeep bool
	ID             string
}

// The caller holds the session's row lock (GetOpenGameSessionForUpdate).
func (q *Queries) SetShownImage(ctx context.Context, arg SetShownImageParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, setShownImage, arg.ShownImageID, arg.ShownImageKeep, arg.ID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
		&i.ShownImageKeep,
	)
	return i, err
}

const touchEncounter = `-- name: TouchEncounter :one
UPDATE encounters
SET revision = revision + 1
WHERE id = $1
RETURNING id, game_session_id, map_id, map_point_id, name, status, round, current_combatant_id, grid_columns, grid_rows, revision, created_at, started_at, ended_at
`

func (q *Queries) TouchEncounter(ctx context.Context, id string) (Encounter, error) {
	row := q.db.QueryRow(ctx, touchEncounter, id)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.GameSessionID,
		&i.MapID,
		&i.MapPointID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.CurrentCombatantID,
		&i.GridColumns,
		&i.GridRows,
		&i.Revision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}
