// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package playdb

import (
	"context"
	"time"
)

const endGameSession = `-- name: EndGameSession :one
UPDATE game_sessions
SET ended_at = COALESCE(ended_at, GREATEST($3::TIMESTAMPTZ, started_at))
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id
`

type EndGameSessionParams struct {
	CampaignID string
	ID         string
	Now        time.Time
}

// Ending a session twice keeps the first ended_at, so the call is
// idempotent. GREATEST keeps ended_at from being before started_at if two
// servers' clocks disagree by a little (game_sessions_ends_after_start).
func (q *Queries) EndGameSession(ctx context.Context, arg EndGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, endGameSession, arg.CampaignID, arg.ID, arg.Now)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
	)
	return i, err
}

const getGameSessionForUpdate = `-- name: GetGameSessionForUpdate :one
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id FROM game_sessions
WHERE campaign_id = $1 AND id = $2
FOR UPDATE
`

type GetGameSessionForUpdateParams struct {
	CampaignID string
	ID         string
}

// One session of the campaign, locked until the transaction ends.
func (q *Queries) GetGameSessionForUpdate(ctx context.Context, arg GetGameSessionForUpdateParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, getGameSessionForUpdate, arg.CampaignID, arg.ID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
	)
	return i, err
}

const getOnScreen = `-- name: GetOnScreen :one
SELECT current_map_id, shown_image_id FROM game_sessions
WHERE campaign_id = $1 AND ended_at IS NULL
`

type GetOnScreenRow struct {
	CurrentMapID *string
	ShownImageID *string
}

// What the open session shows: its current map and the image the master
// shows (either NULL when none). No row: no open session.
func (q *Queries) GetOnScreen(ctx context.Context, campaignID string) (GetOnScreenRow, error) {
	row := q.db.QueryRow(ctx, getOnScreen, campaignID)
	var i GetOnScreenRow
	err := row.Scan(&i.CurrentMapID, &i.ShownImageID)
	return i, err
}

const getOpenGameSession = `-- name: GetOpenGameSession :one
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id FROM game_sessions
WHERE campaign_id = $1 AND ended_at IS NULL
`

// The campaign's open session, if any. The partial unique index
// game_sessions_one_open_per_campaign allows at most one.
func (q *Queries) GetOpenGameSession(ctx context.Context, campaignID string) (GameSession, error) {
	row := q.db.QueryRow(ctx, getOpenGameSession, campaignID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
	)
	return i, err
}

const getOpenGameSessionForUpdate = `-- name: GetOpenGameSessionForUpdate :one
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id FROM game_sessions
WHERE campaign_id = $1 AND ended_at IS NULL
FOR UPDATE
`

// GetOpenGameSession, locking the session's row until the transaction ends.
// Every change made during a session locks it first, so two changes at
// once take turns: each one reads the next event number after the other
// wrote its own, and EndGameSession waits for a change in progress.
func (q *Queries) GetOpenGameSessionForUpdate(ctx context.Context, campaignID string) (GameSession, error) {
	row := q.db.QueryRow(ctx, getOpenGameSessionForUpdate, campaignID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
	)
	return i, err
}

const getSessionEventByIdempotencyKey = `-- name: GetSessionEventByIdempotencyKey :one
SELECT id, seq, kind, character_id FROM session_events
WHERE game_session_id = $1 AND idempotency_key = $2
`

type GetSessionEventByIdempotencyKeyParams struct {
	GameSessionID  string
	IdempotencyKey *string
}

type GetSessionEventByIdempotencyKeyRow struct {
	ID          string
	Seq         int32
	Kind        string
	CharacterID *string
}

// The event a change with this key already wrote, if any.
func (q *Queries) GetSessionEventByIdempotencyKey(ctx context.Context, arg GetSessionEventByIdempotencyKeyParams) (GetSessionEventByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getSessionEventByIdempotencyKey, arg.GameSessionID, arg.IdempotencyKey)
	var i GetSessionEventByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Kind,
		&i.CharacterID,
	)
	return i, err
}

const insertGameSession = `-- name: InsertGameSession :one
INSERT INTO game_sessions (campaign_id, session_number, started_at)
VALUES ($1, $2, $3)
RETURNING id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id
`

type InsertGameSessionParams struct {
	CampaignID    string
	SessionNumber int32
	StartedAt     time.Time
}

func (q *Queries) InsertGameSession(ctx context.Context, arg InsertGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, insertGameSession, arg.CampaignID, arg.SessionNumber, arg.StartedAt)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
	)
	return i, err
}

const insertSessionEvent = `-- name: InsertSessionEvent :one
INSERT INTO session_events
    (game_session_id, seq, kind, actor_user_id, character_id, payload, idempotency_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, seq
`

type InsertSessionEventParams struct {
	GameSessionID  string
	Seq            int32
	Kind           string
	ActorUserID    *string
	CharacterID    *string
	Payload        []byte
	IdempotencyKey *string
	CreatedAt      time.Time
}

type InsertSessionEventRow struct {
	ID  string
	Seq int32
}

func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) (InsertSessionEventRow, error) {
	row := q.db.QueryRow(ctx, insertSessionEvent,
		arg.GameSessionID,
		arg.Seq,
		arg.Kind,
		arg.ActorUserID,
		arg.CharacterID,
		arg.Payload,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i InsertSessionEventRow
	err := row.Scan(&i.ID, &i.Seq)
	return i, err
}

const listGameSessions = `-- name: ListGameSessions :many
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id FROM game_sessions
WHERE campaign_id = $1
ORDER BY session_number DESC
`

// Newest first.
func (q *Queries) ListGameSessions(ctx context.Context, campaignID string) ([]GameSession, error) {
	rows, err := q.db.Query(ctx, listGameSessions, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SessionNumber,
			&i.StartedAt,
			&i.EndedAt,
			&i.CurrentMapID,
			&i.ShownImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenGameSessions = `-- name: ListOpenGameSessions :many
SELECT id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id FROM game_sessions
WHERE campaign_id = ANY($1::UUID[]) AND ended_at IS NULL
ORDER BY started_at DESC, id
`

// The open sessions of the given campaigns, newest first (RN-06). The
// partial unique index game_sessions_one_open_per_campaign finds each one.
func (q *Queries) ListOpenGameSessions(ctx context.Context, campaignIds []string) ([]GameSession, error) {
	rows, err := q.db.Query(ctx, listOpenGameSessions, campaignIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.SessionNumber,
			&i.StartedAt,
			&i.EndedAt,
			&i.CurrentMapID,
			&i.ShownImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSessionEventSeq = `-- name: NextSessionEventSeq :one
SELECT (COALESCE(max(seq), 0) + 1)::INT4 AS next
FROM session_events
WHERE game_session_id = $1
`

// Events count from 1 in each session. The caller holds the session's row
// lock (GetOpenGameSessionForUpdate), so no other change reads the same
// number; UNIQUE (game_session_id, seq) is the backstop.
func (q *Queries) NextSessionEventSeq(ctx context.Context, gameSessionID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSessionEventSeq, gameSessionID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const nextSessionNumber = `-- name: NextSessionNumber :one
SELECT (COALESCE(max(session_number), 0) + 1)::INT4 AS next
FROM game_sessions
WHERE campaign_id = $1
`

// Sessions count from 1. Two starts racing both read the same number;
// CockroachDB's SERIALIZABLE isolation makes one of them retry, and the
// UNIQUE (campaign_id, session_number) constraint is the backstop.
func (q *Queries) NextSessionNumber(ctx context.Context, campaignID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSessionNumber, campaignID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const setCurrentMap = `-- name: SetCurrentMap :one
UPDATE game_sessions
SET current_map_id = $1
WHERE id = $2
RETURNING id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id
`

type SetCurrentMapParams struct {
	CurrentMapID *string
	ID           string
}

// The caller holds the session's row lock (GetOpenGameSessionForUpdate).
func (q *Queries) SetCurrentMap(ctx context.Context, arg SetCurrentMapParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, setCurrentMap, arg.CurrentMapID, arg.ID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
	)
	return i, err
}

const setShownImage = `-- name: SetShownImage :one
UPDATE game_sessions
SET shown_image_id = $1
WHERE id = $2
RETURNING id, campaign_id, session_number, started_at, ended_at, current_map_id, shown_image_id
`

type SetShownImageParams struct {
	ShownImageID *string
	ID           string
}

// The caller holds the session's row lock (GetOpenGameSessionForUpdate).
func (q *Queries) SetShownImage(ctx context.Context, arg SetShownImageParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, setShownImage, arg.ShownImageID, arg.ID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.SessionNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.CurrentMapID,
		&i.ShownImageID,
	)
	return i, err
}
