// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notesdb

import (
	"time"
)

type PlayerNote struct {
	ID           string
	CampaignID   string
	AuthorUserID string
	Text         string
	ScenePointID *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CreateKey    *string
	CreateHash   *string
}
