// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package campaignsdb

import (
	"time"
)

type Campaign struct {
	ID        string
	Name      string
	XpMode    string
	CreatedBy string
	CreatedAt time.Time
}

type CampaignDocument struct {
	CampaignID string
	Body       string
	Revision   int32
	UpdatedAt  time.Time
	UpdatedBy  *string
}

type CampaignInvite struct {
	ID               string
	CampaignID       string
	TokenHash        []byte
	CreatedBy        string
	MaxUses          int32
	UseCount         int32
	CreatedAt        time.Time
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	RequiresApproval bool
}

type CampaignMember struct {
	CampaignID       string
	UserID           string
	Role             string
	JoinedAt         time.Time
	Status           string
	PendingExpiresAt *time.Time
}
