// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package campaignsdb

import (
	"context"
	"time"
)

const activatePendingMember = `-- name: ActivatePendingMember :execrows
UPDATE campaign_members
SET status = 'active'
WHERE campaign_id = $1 AND user_id = $2 AND status = 'pending'
`

type ActivatePendingMemberParams struct {
	CampaignID string
	UserID     string
}

// The master approved the pending member's character (RN-15): the
// membership becomes an ordinary one. An active membership matches no row
// and stays as it is.
func (q *Queries) ActivatePendingMember(ctx context.Context, arg ActivatePendingMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, activatePendingMember, arg.CampaignID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingMember = `-- name: DeletePendingMember :execrows
DELETE FROM campaign_members
WHERE campaign_id = $1 AND user_id = $2 AND status = 'pending'
`

type DeletePendingMemberParams struct {
	CampaignID string
	UserID     string
}

// The master rejected the pending member's character (RN-15): the pending
// membership goes with it. status = 'pending' in the WHERE clause means an
// active membership is never deleted here.
func (q *Queries) DeletePendingMember(ctx context.Context, arg DeletePendingMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingMember, arg.CampaignID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, xp_mode, created_by, created_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.XpMode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByTokenHashForUpdate = `-- name: GetInviteByTokenHashForUpdate :one
SELECT id, campaign_id, token_hash, created_by, max_uses, use_count, created_at, expires_at, revoked_at, requires_approval FROM campaign_invites WHERE token_hash = $1 FOR UPDATE
`

// FOR UPDATE locks the invite until the transaction ends. A second
// AcceptInvite for the same invite waits here, instead of both reading the
// same use_count, and then sees the first one's result.
func (q *Queries) GetInviteByTokenHashForUpdate(ctx context.Context, tokenHash []byte) (CampaignInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHashForUpdate, tokenHash)
	var i CampaignInvite
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RequiresApproval,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT role, status FROM campaign_members WHERE campaign_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	CampaignID string
	UserID     string
}

type GetMembershipRow struct {
	Role   string
	Status string
}

// The query behind every authorization check (package authz): one read of
// the primary key.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.CampaignID, arg.UserID)
	var i GetMembershipRow
	err := row.Scan(&i.Role, &i.Status)
	return i, err
}

const incrementInviteUses = `-- name: IncrementInviteUses :execrows
UPDATE campaign_invites
SET use_count = use_count + 1
WHERE id = $1 AND use_count < max_uses AND revoked_at IS NULL AND expires_at > $2
`

type IncrementInviteUsesParams struct {
	ID  string
	Now time.Time
}

// The WHERE clause repeats the rules, so an invite is never used more than
// max_uses times, after it expires or after it is revoked, even if the Go
// checks before it had a bug.
func (q *Queries) IncrementInviteUses(ctx context.Context, arg IncrementInviteUsesParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementInviteUses, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCampaign = `-- name: InsertCampaign :one
INSERT INTO campaigns (name, xp_mode, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, xp_mode, created_by, created_at
`

type InsertCampaignParams struct {
	Name      string
	XpMode    string
	CreatedBy string
}

func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, insertCampaign, arg.Name, arg.XpMode, arg.CreatedBy)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.XpMode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertInvite = `-- name: InsertInvite :one
INSERT INTO campaign_invites
    (campaign_id, token_hash, created_by, max_uses, created_at, expires_at, requires_approval)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, campaign_id, token_hash, created_by, max_uses, use_count, created_at, expires_at, revoked_at, requires_approval
`

type InsertInviteParams struct {
	CampaignID       string
	TokenHash        []byte
	CreatedBy        string
	MaxUses          int32
	CreatedAt        time.Time
	ExpiresAt        time.Time
	RequiresApproval bool
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) (CampaignInvite, error) {
	row := q.db.QueryRow(ctx, insertInvite,
		arg.CampaignID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.MaxUses,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RequiresApproval,
	)
	var i CampaignInvite
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RequiresApproval,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :one
INSERT INTO campaign_members (campaign_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING campaign_id, user_id, role, joined_at, status
`

type InsertMemberParams struct {
	CampaignID string
	UserID     string
	Role       string
	Status     string
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (CampaignMember, error) {
	row := q.db.QueryRow(ctx, insertMember,
		arg.CampaignID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i CampaignMember
	err := row.Scan(
		&i.CampaignID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Status,
	)
	return i, err
}

const listCampaignsOfUser = `-- name: ListCampaignsOfUser :many
SELECT c.id, c.name, c.xp_mode, c.created_by, c.created_at, m.role, m.status
FROM campaign_members AS m
JOIN campaigns AS c ON c.id = m.campaign_id
WHERE m.user_id = $1
ORDER BY c.created_at DESC, c.id
`

type ListCampaignsOfUserRow struct {
	Campaign Campaign
	Role     string
	Status   string
}

// Newest first. The index on campaign_members (user_id) finds the rows.
// Pending memberships (RN-15) come too: the handler shows only the name.
func (q *Queries) ListCampaignsOfUser(ctx context.Context, userID string) ([]ListCampaignsOfUserRow, error) {
	rows, err := q.db.Query(ctx, listCampaignsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsOfUserRow
	for rows.Next() {
		var i ListCampaignsOfUserRow
		if err := rows.Scan(
			&i.Campaign.ID,
			&i.Campaign.Name,
			&i.Campaign.XpMode,
			&i.Campaign.CreatedBy,
			&i.Campaign.CreatedAt,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, campaign_id, token_hash, created_by, max_uses, use_count, created_at, expires_at, revoked_at, requires_approval FROM campaign_invites
WHERE campaign_id = $1
ORDER BY created_at DESC, id
`

// Newest first. Invites that expired more than 30 days ago are gone (TTL).
func (q *Queries) ListInvites(ctx context.Context, campaignID string) ([]CampaignInvite, error) {
	rows, err := q.db.Query(ctx, listInvites, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignInvite
	for rows.Next() {
		var i CampaignInvite
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.TokenHash,
			&i.CreatedBy,
			&i.MaxUses,
			&i.UseCount,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RequiresApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT campaign_id, user_id, role, joined_at, status FROM campaign_members
WHERE campaign_id = $1 AND status = 'active'
ORDER BY role = 'master' DESC, joined_at, user_id
`

// The master first, then the players in the order they joined. Pending
// members (RN-15) are not members yet, so they are left out.
func (q *Queries) ListMembers(ctx context.Context, campaignID string) ([]CampaignMember, error) {
	rows, err := q.db.Query(ctx, listMembers, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignMember
	for rows.Next() {
		var i CampaignMember
		if err := rows.Scan(
			&i.CampaignID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE campaign_invites
SET revoked_at = COALESCE(revoked_at, $3)
WHERE campaign_id = $1 AND id = $2
RETURNING id, campaign_id, token_hash, created_by, max_uses, use_count, created_at, expires_at, revoked_at, requires_approval
`

type RevokeInviteParams struct {
	CampaignID string
	ID         string
	Now        *time.Time
}

// Revoking twice keeps the first revoked_at, so RevokeInvite is idempotent.
// An invite of another campaign matches no row, which reads as "not found".
func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (CampaignInvite, error) {
	row := q.db.QueryRow(ctx, revokeInvite, arg.CampaignID, arg.ID, arg.Now)
	var i CampaignInvite
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RequiresApproval,
	)
	return i, err
}
