#!/usr/bin/env bash
# Creates deploy/elk/.env with random passwords if it does not exist yet.
# Never prints a secret. Safe to run again: an existing .env is left alone.
set -euo pipefail
cd "$(dirname "$0")"

if [ -f .env ]; then
  exit 0
fi

command -v openssl >/dev/null || { echo "init-env.sh: openssl is required" >&2; exit 1; }

umask 077
{
  echo "# Generated by init-env.sh. Gitignored. Never commit."
  echo "ELASTIC_PASSWORD=$(openssl rand -hex 16)"
  echo "KIBANA_PASSWORD=$(openssl rand -hex 16)"
  echo "FILEBEAT_PASSWORD=$(openssl rand -hex 16)"
  echo "READER_PASSWORD=$(openssl rand -hex 16)"
  echo "KIBANA_ENCRYPTION_KEY=$(openssl rand -hex 32)"
} > .env
echo "init-env.sh: created deploy/elk/.env (random passwords, mode 600)"
