// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package charactersdb

import (
	"context"
	"time"
)

const claimReservedCharacter = `-- name: ClaimReservedCharacter :one
UPDATE characters
SET reserved = false, player_user_id = $1::UUID, claimed_at = $2::TIMESTAMPTZ
WHERE campaign_id = $3::UUID AND id = $4::UUID AND reserved
RETURNING id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at, create_key, create_hash, reserved, claimed_at, revived_at, death_round, death_encounter_id, revivify_blocked, revive_key, revive_hash
`

type ClaimReservedCharacterParams struct {
	PlayerUserID string
	Now          time.Time
	CampaignID   string
	ID           string
}

// A player takes a reserved character. Like approval and death, a change of owner does
// not change the revision or updated_at: the sheet and the story are as the master left them.
func (q *Queries) ClaimReservedCharacter(ctx context.Context, arg ClaimReservedCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, claimReservedCharacter,
		arg.PlayerUserID,
		arg.Now,
		arg.CampaignID,
		arg.ID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreateKey,
		&i.CreateHash,
		&i.Reserved,
		&i.ClaimedAt,
		&i.RevivedAt,
		&i.DeathRound,
		&i.DeathEncounterID,
		&i.RevivifyBlocked,
		&i.ReviveKey,
		&i.ReviveHash,
	)
	return i, err
}

const deleteClaimSignIn = `-- name: DeleteClaimSignIn :exec
DELETE FROM claim_sign_ins WHERE user_id = $1::UUID
`

func (q *Queries) DeleteClaimSignIn(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteClaimSignIn, userID)
	return err
}

const deleteReservedCharacter = `-- name: DeleteReservedCharacter :execrows
DELETE FROM characters
WHERE campaign_id = $1::UUID AND id = $2::UUID AND reserved
`

type DeleteReservedCharacterParams struct {
	CampaignID string
	ID         string
}

// Only a reserved character is ever deleted here: it never had an owner (RN-03 keeps
// every other one).
func (q *Queries) DeleteReservedCharacter(ctx context.Context, arg DeleteReservedCharacterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReservedCharacter, arg.CampaignID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCharacterNameAndOwner = `-- name: GetCharacterNameAndOwner :one
SELECT id, name, player_user_id FROM characters
WHERE campaign_id = $1::UUID AND id = $2::UUID
`

type GetCharacterNameAndOwnerParams struct {
	CampaignID string
	ID         string
}

type GetCharacterNameAndOwnerRow struct {
	ID           string
	Name         string
	PlayerUserID *string
}

func (q *Queries) GetCharacterNameAndOwner(ctx context.Context, arg GetCharacterNameAndOwnerParams) (GetCharacterNameAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getCharacterNameAndOwner, arg.CampaignID, arg.ID)
	var i GetCharacterNameAndOwnerRow
	err := row.Scan(&i.ID, &i.Name, &i.PlayerUserID)
	return i, err
}

const getClaimLinkByTokenHash = `-- name: GetClaimLinkByTokenHash :one
SELECT id, campaign_id, character_id, token_hash, created_by, created_at, expires_at, revoked_at, used_at, used_by FROM claim_links WHERE token_hash = $1
`

func (q *Queries) GetClaimLinkByTokenHash(ctx context.Context, tokenHash []byte) (ClaimLink, error) {
	row := q.db.QueryRow(ctx, getClaimLinkByTokenHash, tokenHash)
	var i ClaimLink
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const getClaimLinkByTokenHashForUpdate = `-- name: GetClaimLinkByTokenHashForUpdate :one
SELECT id, campaign_id, character_id, token_hash, created_by, created_at, expires_at, revoked_at, used_at, used_by FROM claim_links WHERE token_hash = $1 FOR UPDATE
`

// The link a token opens, locked until the transaction ends: two claims of one link,
// or a claim and a revoke, wait for each other and the second finds the first's result.
func (q *Queries) GetClaimLinkByTokenHashForUpdate(ctx context.Context, tokenHash []byte) (ClaimLink, error) {
	row := q.db.QueryRow(ctx, getClaimLinkByTokenHashForUpdate, tokenHash)
	var i ClaimLink
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const getClaimSignIn = `-- name: GetClaimSignIn :one
SELECT token_hash FROM claim_sign_ins
WHERE user_id = $1::UUID AND expires_at > $2::TIMESTAMPTZ
`

type GetClaimSignInParams struct {
	UserID string
	Now    time.Time
}

func (q *Queries) GetClaimSignIn(ctx context.Context, arg GetClaimSignInParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getClaimSignIn, arg.UserID, arg.Now)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}

const getLatestClaimLinkForUpdate = `-- name: GetLatestClaimLinkForUpdate :one
SELECT id, campaign_id, character_id, token_hash, created_by, created_at, expires_at, revoked_at, used_at, used_by FROM claim_links
WHERE campaign_id = $1::UUID AND character_id = $2::UUID
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

type GetLatestClaimLinkForUpdateParams struct {
	CampaignID  string
	CharacterID string
}

// The character's latest link, locked: RevokeClaimLink and the claim race for it.
func (q *Queries) GetLatestClaimLinkForUpdate(ctx context.Context, arg GetLatestClaimLinkForUpdateParams) (ClaimLink, error) {
	row := q.db.QueryRow(ctx, getLatestClaimLinkForUpdate, arg.CampaignID, arg.CharacterID)
	var i ClaimLink
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const insertClaimLink = `-- name: InsertClaimLink :one

INSERT INTO claim_links (campaign_id, character_id, token_hash, created_by, created_at, expires_at)
VALUES (
    $1::UUID, $2::UUID, $3, $4::UUID,
    $5, $6
)
RETURNING id, campaign_id, character_id, token_hash, created_by, created_at, expires_at, revoked_at, used_at, used_by
`

type InsertClaimLinkParams struct {
	CampaignID  string
	CharacterID string
	TokenHash   []byte
	CreatedBy   string
	Now         time.Time
	ExpiresAt   time.Time
}

// Reserved characters and their claim links (MR-049). A reserved character is a
// player character with no owner that no player can see (characters.reserved); a
// claim link hands it to a player. The tables are in migration 00203.
func (q *Queries) InsertClaimLink(ctx context.Context, arg InsertClaimLinkParams) (ClaimLink, error) {
	row := q.db.QueryRow(ctx, insertClaimLink,
		arg.CampaignID,
		arg.CharacterID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.Now,
		arg.ExpiresAt,
	)
	var i ClaimLink
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const listLatestClaimLinks = `-- name: ListLatestClaimLinks :many
SELECT DISTINCT ON (character_id) character_id, expires_at, revoked_at, used_at, used_by
FROM claim_links
WHERE campaign_id = $1::UUID
ORDER BY character_id, created_at DESC, id DESC
`

type ListLatestClaimLinksRow struct {
	CharacterID string
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	UsedAt      *time.Time
	UsedBy      *string
}

// The latest link of each character of the campaign that has one, for the master's list.
func (q *Queries) ListLatestClaimLinks(ctx context.Context, campaignID string) ([]ListLatestClaimLinksRow, error) {
	rows, err := q.db.Query(ctx, listLatestClaimLinks, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestClaimLinksRow
	for rows.Next() {
		var i ListLatestClaimLinksRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UsedAt,
			&i.UsedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClaimLinkUsed = `-- name: MarkClaimLinkUsed :execrows
UPDATE claim_links
SET used_at = $1::TIMESTAMPTZ, used_by = $2::UUID
WHERE id = $3::UUID AND used_at IS NULL AND revoked_at IS NULL AND expires_at > $1::TIMESTAMPTZ
`

type MarkClaimLinkUsedParams struct {
	Now    time.Time
	UsedBy string
	ID     string
}

// Spends a link that still works: the WHERE clause repeats what the caller checked
// under the row lock, so a bug there cannot spend a revoked or expired link.
func (q *Queries) MarkClaimLinkUsed(ctx context.Context, arg MarkClaimLinkUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markClaimLinkUsed, arg.Now, arg.UsedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const returnCharacterToReserve = `-- name: ReturnCharacterToReserve :one
UPDATE characters
SET reserved = true, player_user_id = NULL, claimed_at = NULL
WHERE campaign_id = $1::UUID AND id = $2::UUID
  AND kind = 'player' AND NOT reserved AND claimed_at IS NOT NULL AND status = 'active'
RETURNING id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at, create_key, create_hash, reserved, claimed_at, revived_at, death_round, death_encounter_id, revivify_blocked, revive_key, revive_hash
`

type ReturnCharacterToReserveParams struct {
	CampaignID string
	ID         string
}

// The master takes a claimed character back: no owner, reserved again. Only a living
// player character a claim brought to its player (claimed_at) goes back.
func (q *Queries) ReturnCharacterToReserve(ctx context.Context, arg ReturnCharacterToReserveParams) (Character, error) {
	row := q.db.QueryRow(ctx, returnCharacterToReserve, arg.CampaignID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreateKey,
		&i.CreateHash,
		&i.Reserved,
		&i.ClaimedAt,
		&i.RevivedAt,
		&i.DeathRound,
		&i.DeathEncounterID,
		&i.RevivifyBlocked,
		&i.ReviveKey,
		&i.ReviveHash,
	)
	return i, err
}

const revokeClaimLinkByID = `-- name: RevokeClaimLinkByID :execrows
UPDATE claim_links
SET revoked_at = $1::TIMESTAMPTZ
WHERE id = $2::UUID AND used_at IS NULL AND revoked_at IS NULL
`

type RevokeClaimLinkByIDParams struct {
	Now time.Time
	ID  string
}

func (q *Queries) RevokeClaimLinkByID(ctx context.Context, arg RevokeClaimLinkByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeClaimLinkByID, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLiveClaimLinks = `-- name: RevokeLiveClaimLinks :execrows
UPDATE claim_links
SET revoked_at = $1
WHERE character_id = $2::UUID AND revoked_at IS NULL AND used_at IS NULL
`

type RevokeLiveClaimLinksParams struct {
	Now         *time.Time
	CharacterID string
}

// A new link revokes the character's live one, in the same transaction. A link that
// ran out is revoked too: the unique index on live links counts it until it is.
func (q *Queries) RevokeLiveClaimLinks(ctx context.Context, arg RevokeLiveClaimLinksParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLiveClaimLinks, arg.Now, arg.CharacterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertClaimSignIn = `-- name: UpsertClaimSignIn :exec
INSERT INTO claim_sign_ins (user_id, token_hash, expires_at)
VALUES ($1::UUID, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET token_hash = excluded.token_hash, expires_at = excluded.expires_at
`

type UpsertClaimSignInParams struct {
	UserID    string
	TokenHash []byte
	ExpiresAt time.Time
}

// The link a person signed in with (sign-in intent character_claim): one row per person.
func (q *Queries) UpsertClaimSignIn(ctx context.Context, arg UpsertClaimSignInParams) error {
	_, err := q.db.Exec(ctx, upsertClaimSignIn, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}
