// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package charactersdb

import (
	"time"
)

type CampaignContent struct {
	CampaignID string
	ContentKey string
	Kind       string
	NamePt     string
	Data       []byte
	Revision   int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	CreateKey  *string
	CreateHash *string
}

type Character struct {
	ID                  string
	CampaignID          *string
	Kind                string
	PlayerUserID        *string
	MasterUserID        *string
	Status              string
	Name                string
	Sheet               []byte
	Story               []byte
	StoryEditingAllowed bool
	SheetSchema         int32
	Revision            int32
	SheetLockedAt       *time.Time
	DiedAt              *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CreateKey           *string
	CreateHash          *string
	RevivedAt           *time.Time
	DeathRound          *int32
	DeathEncounterID    *string
	RevivifyBlocked     bool
	ReviveKey           *string
	ReviveHash          *string
}

type CharacterCreature struct {
	ID                  string
	CampaignID          string
	CharacterID         string
	MonsterKey          string
	Name                string
	Source              string
	Attack              string
	SummonGroupID       string
	ConcentrationCastID *string
	HpCurrent           int32
	HpMax               int32
	CreatedAt           time.Time
	DismissedAt         *time.Time
	DismissedReason     *string
	CreateKey           *string
	CreateHash          *string
}

type CharacterLevelUp struct {
	ID          string
	CampaignID  string
	CharacterID string
	ClassKey    string
	FromLevel   int32
	ToLevel     int32
	HpMethod    string
	HpValue     int32
	Choices     []byte
	CreatedAt   time.Time
}

type CharacterReview struct {
	CharacterID   string
	CampaignID    string
	PlayerUserID  string
	Status        string
	Reason        string
	RequestedAt   time.Time
	ResubmittedAt *time.Time
	RequestKey    *string
	RequestHash   *string
	ResubmitKey   *string
	ResubmitHash  *string
}
