// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package charactersdb

import (
	"context"
	"time"
)

const approveCharacter = `-- name: ApproveCharacter :one
UPDATE characters
SET status = 'active'
WHERE campaign_id = $1::UUID AND id = $2 AND status = 'pending'
RETURNING id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at
`

type ApproveCharacterParams struct {
	CampaignID string
	ID         string
}

// The master approved a pending character (RN-15, MR-024): it becomes an
// ordinary living character, a draft until the next game session starts.
// Like death, approval changes neither the revision nor updated_at.
func (q *Queries) ApproveCharacter(ctx context.Context, arg ApproveCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, approveCharacter, arg.CampaignID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const approvePendingCharacterOfPlayer = `-- name: ApprovePendingCharacterOfPlayer :execrows
UPDATE characters
SET status = 'active'
WHERE campaign_id = $1::UUID AND player_user_id = $2
  AND kind = 'player' AND status = 'pending'
`

type ApprovePendingCharacterOfPlayerParams struct {
	CampaignID   string
	PlayerUserID *string
}

// An ordinary invite promotes a pending member (RN-15, Q25): that counts as
// the master's approval, so their character waiting for approval, if any,
// is approved with exactly the effect of ApproveCharacter above, found by
// player instead of by ID. A player has at most one living character
// (RN-03), so at most one row matches; none matches when they have not
// created it yet.
func (q *Queries) ApprovePendingCharacterOfPlayer(ctx context.Context, arg ApprovePendingCharacterOfPlayerParams) (int64, error) {
	result, err := q.db.Exec(ctx, approvePendingCharacterOfPlayer, arg.CampaignID, arg.PlayerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const characterIsInCampaign = `-- name: CharacterIsInCampaign :one
SELECT EXISTS (
    SELECT 1 FROM characters
    WHERE campaign_id = $1::UUID AND id = $2
)
`

type CharacterIsInCampaignParams struct {
	CampaignID string
	ID         string
}

func (q *Queries) CharacterIsInCampaign(ctx context.Context, arg CharacterIsInCampaignParams) (bool, error) {
	row := q.db.QueryRow(ctx, characterIsInCampaign, arg.CampaignID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clearPortraits = `-- name: ClearPortraits :execrows
UPDATE characters
SET sheet = (sheet #- '{full,portrait_image_id}') #- '{basic,portrait_image_id}',
    revision = revision + 1, updated_at = $1
WHERE campaign_id = $2::UUID
  AND (sheet -> 'full' ->> 'portrait_image_id' = $3::TEXT
       OR sheet -> 'basic' ->> 'portrait_image_id' = $3::TEXT)
`

type ClearPortraitsParams struct {
	Now        time.Time
	CampaignID string
	ImageID    string
}

// The master deleted a gallery image: the NPCs that had it as their portrait
// lose it (MR-031). The revision goes up, so a stale editor is told. Only the
// sheets that have it are touched.
func (q *Queries) ClearPortraits(ctx context.Context, arg ClearPortraitsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearPortraits, arg.Now, arg.CampaignID, arg.ImageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearWildShape = `-- name: ClearWildShape :exec
DELETE FROM character_wild_shapes WHERE character_id = $1
`

// The druid is itself again.
func (q *Queries) ClearWildShape(ctx context.Context, characterID string) error {
	_, err := q.db.Exec(ctx, clearWildShape, characterID)
	return err
}

const countLiveCreaturesOfCharacter = `-- name: CountLiveCreaturesOfCharacter :one
SELECT count(*)::INT4 FROM character_creatures
WHERE campaign_id = $1::UUID AND character_id = $2::UUID AND dismissed_at IS NULL
`

type CountLiveCreaturesOfCharacterParams struct {
	CampaignID  string
	CharacterID string
}

func (q *Queries) CountLiveCreaturesOfCharacter(ctx context.Context, arg CountLiveCreaturesOfCharacterParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLiveCreaturesOfCharacter, arg.CampaignID, arg.CharacterID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteCreatures = `-- name: DeleteCreatures :exec
DELETE FROM character_creatures
WHERE campaign_id = $1::UUID AND id = ANY($2::UUID[])
`

type DeleteCreaturesParams struct {
	CampaignID string
	Ids        []string
}

// Takes the creatures a casting made away for good (the master's undo of it).
func (q *Queries) DeleteCreatures(ctx context.Context, arg DeleteCreaturesParams) error {
	_, err := q.db.Exec(ctx, deleteCreatures, arg.CampaignID, arg.Ids)
	return err
}

const deleteLevelUpRoll = `-- name: DeleteLevelUpRoll :exec
DELETE FROM character_level_up_rolls
WHERE character_id = $1::UUID AND to_level = $2
`

type DeleteLevelUpRollParams struct {
	CharacterID string
	ToLevel     int32
}

// The level-up used the roll; its value goes on in character_level_ups.
func (q *Queries) DeleteLevelUpRoll(ctx context.Context, arg DeleteLevelUpRollParams) error {
	_, err := q.db.Exec(ctx, deleteLevelUpRoll, arg.CharacterID, arg.ToLevel)
	return err
}

const deleteMasterNotes = `-- name: DeleteMasterNotes :exec
DELETE FROM character_master_notes
WHERE campaign_id = $1 AND character_id = $2
`

type DeleteMasterNotesParams struct {
	CampaignID  string
	CharacterID string
}

// Empty notes are not stored (RN-11 keeps only what is needed).
func (q *Queries) DeleteMasterNotes(ctx context.Context, arg DeleteMasterNotesParams) error {
	_, err := q.db.Exec(ctx, deleteMasterNotes, arg.CampaignID, arg.CharacterID)
	return err
}

const deletePendingCharacter = `-- name: DeletePendingCharacter :execrows
DELETE FROM characters
WHERE campaign_id = $1::UUID AND id = $2 AND status = 'pending'
`

type DeletePendingCharacterParams struct {
	CampaignID string
	ID         string
}

// The master rejected a pending character (RN-15, MR-024): it never became
// part of the campaign, so it is deleted, story and all; the master's notes
// about it go too (character_master_notes cascades). status = 'pending' in
// the WHERE clause means no other character is ever deleted here: outside
// account deletion, characters change status, never row (RN-03).
func (q *Queries) DeletePendingCharacter(ctx context.Context, arg DeletePendingCharacterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingCharacter, arg.CampaignID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dismissCreatures = `-- name: DismissCreatures :many
UPDATE character_creatures
SET dismissed_at = $1::TIMESTAMPTZ, dismissed_reason = $2::TEXT,
    hp_current = CASE WHEN $2::TEXT = 'defeated' THEN 0 ELSE hp_current END
WHERE campaign_id = $3::UUID
  AND id = ANY($4::UUID[])
  AND dismissed_at IS NULL
RETURNING id
`

type DismissCreaturesParams struct {
	At         time.Time
	Reason     string
	CampaignID string
	Ids        []string
}

// Sends the live ones of these creatures away, with the reason; a creature
// dismissed because it was defeated is at 0 hit points. Returns the ones it
// dismissed.
func (q *Queries) DismissCreatures(ctx context.Context, arg DismissCreaturesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, dismissCreatures,
		arg.At,
		arg.Reason,
		arg.CampaignID,
		arg.Ids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endStoryEditing = `-- name: EndStoryEditing :execrows
UPDATE characters
SET story_editing_allowed = false
WHERE campaign_id = $1::UUID AND story_editing_allowed
`

// When a game session starts, every permission to edit a story ends.
func (q *Queries) EndStoryEditing(ctx context.Context, campaignID string) (int64, error) {
	result, err := q.db.Exec(ctx, endStoryEditing, campaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at FROM characters
WHERE campaign_id = $1::UUID AND id = $2
`

type GetCharacterParams struct {
	CampaignID string
	ID         string
}

func (q *Queries) GetCharacter(ctx context.Context, arg GetCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, arg.CampaignID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterCreature = `-- name: GetCharacterCreature :one
SELECT cc.id, cc.campaign_id, cc.character_id, cc.monster_key, cc.name, cc.source, cc.attack, cc.summon_group_id, cc.concentration_cast_id, cc.hp_current, cc.hp_max, cc.created_at, cc.dismissed_at, cc.dismissed_reason, c.player_user_id
FROM character_creatures cc
JOIN characters c ON c.id = cc.character_id
WHERE cc.campaign_id = $1::UUID AND cc.id = $2::UUID
`

type GetCharacterCreatureParams struct {
	CampaignID string
	ID         string
}

type GetCharacterCreatureRow struct {
	CharacterCreature CharacterCreature
	PlayerUserID      *string
}

// One creature of the campaign, live or not, with its owner's player.
func (q *Queries) GetCharacterCreature(ctx context.Context, arg GetCharacterCreatureParams) (GetCharacterCreatureRow, error) {
	row := q.db.QueryRow(ctx, getCharacterCreature, arg.CampaignID, arg.ID)
	var i GetCharacterCreatureRow
	err := row.Scan(
		&i.CharacterCreature.ID,
		&i.CharacterCreature.CampaignID,
		&i.CharacterCreature.CharacterID,
		&i.CharacterCreature.MonsterKey,
		&i.CharacterCreature.Name,
		&i.CharacterCreature.Source,
		&i.CharacterCreature.Attack,
		&i.CharacterCreature.SummonGroupID,
		&i.CharacterCreature.ConcentrationCastID,
		&i.CharacterCreature.HpCurrent,
		&i.CharacterCreature.HpMax,
		&i.CharacterCreature.CreatedAt,
		&i.CharacterCreature.DismissedAt,
		&i.CharacterCreature.DismissedReason,
		&i.PlayerUserID,
	)
	return i, err
}

const getCharacterCreatureForUpdate = `-- name: GetCharacterCreatureForUpdate :one
SELECT cc.id, cc.campaign_id, cc.character_id, cc.monster_key, cc.name, cc.source, cc.attack, cc.summon_group_id, cc.concentration_cast_id, cc.hp_current, cc.hp_max, cc.created_at, cc.dismissed_at, cc.dismissed_reason, c.player_user_id
FROM character_creatures cc
JOIN characters c ON c.id = cc.character_id
WHERE cc.campaign_id = $1::UUID AND cc.id = $2::UUID
FOR UPDATE OF cc
`

type GetCharacterCreatureForUpdateParams struct {
	CampaignID string
	ID         string
}

type GetCharacterCreatureForUpdateRow struct {
	CharacterCreature CharacterCreature
	PlayerUserID      *string
}

// The same, locking the creature's row until the transaction ends.
func (q *Queries) GetCharacterCreatureForUpdate(ctx context.Context, arg GetCharacterCreatureForUpdateParams) (GetCharacterCreatureForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCharacterCreatureForUpdate, arg.CampaignID, arg.ID)
	var i GetCharacterCreatureForUpdateRow
	err := row.Scan(
		&i.CharacterCreature.ID,
		&i.CharacterCreature.CampaignID,
		&i.CharacterCreature.CharacterID,
		&i.CharacterCreature.MonsterKey,
		&i.CharacterCreature.Name,
		&i.CharacterCreature.Source,
		&i.CharacterCreature.Attack,
		&i.CharacterCreature.SummonGroupID,
		&i.CharacterCreature.ConcentrationCastID,
		&i.CharacterCreature.HpCurrent,
		&i.CharacterCreature.HpMax,
		&i.CharacterCreature.CreatedAt,
		&i.CharacterCreature.DismissedAt,
		&i.CharacterCreature.DismissedReason,
		&i.PlayerUserID,
	)
	return i, err
}

const getCharacterForUpdate = `-- name: GetCharacterForUpdate :one
SELECT id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at FROM characters
WHERE campaign_id = $1::UUID AND id = $2
FOR UPDATE
`

type GetCharacterForUpdateParams struct {
	CampaignID string
	ID         string
}

// FOR UPDATE locks the row until the transaction ends, so two edits of the
// same character wait for each other instead of both reading the same
// revision.
func (q *Queries) GetCharacterForUpdate(ctx context.Context, arg GetCharacterForUpdateParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterForUpdate, arg.CampaignID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLevelUpRoll = `-- name: GetLevelUpRoll :one
SELECT class_key, die, value FROM character_level_up_rolls
WHERE character_id = $1::UUID AND to_level = $2
`

type GetLevelUpRollParams struct {
	CharacterID string
	ToLevel     int32
}

type GetLevelUpRollRow struct {
	ClassKey string
	Die      int32
	Value    int32
}

// The hit die the server rolled for the character's next level (MR-040): one
// per character and target total level (not per class: a multiclass
// character cannot roll twice for a level), kept until the level-up uses it.
func (q *Queries) GetLevelUpRoll(ctx context.Context, arg GetLevelUpRollParams) (GetLevelUpRollRow, error) {
	row := q.db.QueryRow(ctx, getLevelUpRoll, arg.CharacterID, arg.ToLevel)
	var i GetLevelUpRollRow
	err := row.Scan(&i.ClassKey, &i.Die, &i.Value)
	return i, err
}

const getLivingPlayerCharacterID = `-- name: GetLivingPlayerCharacterID :one
SELECT id FROM characters
WHERE campaign_id = $1::UUID
  AND player_user_id = $2::UUID
  AND kind = 'player' AND status <> 'dead'
LIMIT 1
`

type GetLivingPlayerCharacterIDParams struct {
	CampaignID   string
	PlayerUserID string
}

// The player's living character in the campaign, if any (RN-03). The
// partial unique index characters_one_living_player_character allows at
// most one.
func (q *Queries) GetLivingPlayerCharacterID(ctx context.Context, arg GetLivingPlayerCharacterIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getLivingPlayerCharacterID, arg.CampaignID, arg.PlayerUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getMasterNotes = `-- name: GetMasterNotes :one
SELECT notes, updated_at FROM character_master_notes
WHERE campaign_id = $1 AND character_id = $2
`

type GetMasterNotesParams struct {
	CampaignID  string
	CharacterID string
}

type GetMasterNotesRow struct {
	Notes     string
	UpdatedAt time.Time
}

func (q *Queries) GetMasterNotes(ctx context.Context, arg GetMasterNotesParams) (GetMasterNotesRow, error) {
	row := q.db.QueryRow(ctx, getMasterNotes, arg.CampaignID, arg.CharacterID)
	var i GetMasterNotesRow
	err := row.Scan(&i.Notes, &i.UpdatedAt)
	return i, err
}

const getVitals = `-- name: GetVitals :one
SELECT c.id, c.name, c.player_user_id, c.sheet,
       v.hit_points_current, v.hit_points_temporary, v.spell_slots_used,
       v.pact_slots_used, v.hit_dice_used, v.resources_used, v.revision, v.updated_at,
       ws.beast AS wild_shape_beast, ws.hp AS wild_shape_hp, v.familiar_sight_creature_id, v.familiar_sight_in_combat,
       v.familiar_sight_conditions
FROM characters AS c
LEFT JOIN character_vitals AS v ON v.character_id = c.id
LEFT JOIN character_wild_shapes AS ws ON ws.character_id = c.id
WHERE c.campaign_id = $1::UUID AND c.id = $2
  AND c.kind = 'player' AND c.status = 'active'
`

type GetVitalsParams struct {
	CampaignID string
	ID         string
}

type GetVitalsRow struct {
	ID                      string
	Name                    string
	PlayerUserID            *string
	Sheet                   []byte
	HitPointsCurrent        *int32
	HitPointsTemporary      *int32
	SpellSlotsUsed          []int32
	PactSlotsUsed           *int32
	HitDiceUsed             *int32
	ResourcesUsed           []byte
	Revision                *int32
	UpdatedAt               *time.Time
	WildShapeBeast          *string
	WildShapeHp             *int32
	FamiliarSightCreatureID *string
	FamiliarSightInCombat   *bool
	FamiliarSightConditions []string
}

// ListVitals for one character. No row means the character is not a
// living, active player character of the campaign.
func (q *Queries) GetVitals(ctx context.Context, arg GetVitalsParams) (GetVitalsRow, error) {
	row := q.db.QueryRow(ctx, getVitals, arg.CampaignID, arg.ID)
	var i GetVitalsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlayerUserID,
		&i.Sheet,
		&i.HitPointsCurrent,
		&i.HitPointsTemporary,
		&i.SpellSlotsUsed,
		&i.PactSlotsUsed,
		&i.HitDiceUsed,
		&i.ResourcesUsed,
		&i.Revision,
		&i.UpdatedAt,
		&i.WildShapeBeast,
		&i.WildShapeHp,
		&i.FamiliarSightCreatureID,
		&i.FamiliarSightInCombat,
		&i.FamiliarSightConditions,
	)
	return i, err
}

const insertCharacter = `-- name: InsertCharacter :one

INSERT INTO characters
    (campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, created_at, updated_at)
VALUES (
    $1::UUID, $2, $3, $4,
    $5, $6, $7, $8, $9, $9
)
RETURNING id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at
`

type InsertCharacterParams struct {
	CampaignID   string
	Kind         string
	PlayerUserID *string
	MasterUserID *string
	Status       string
	Name         string
	Sheet        []byte
	Story        []byte
	Now          time.Time
}

// Every query names the campaign next to the character: a character ID of
// another campaign matches no row, which the handlers answer as "not found".
// campaign_id is nullable in the table (a deleted campaign sets it to NULL),
// so the argument is cast to UUID to make it a plain string in Go.
// status is 'active', or 'pending' for a character created by a pending
// member (RN-15, MR-024).
func (q *Queries) InsertCharacter(ctx context.Context, arg InsertCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, insertCharacter,
		arg.CampaignID,
		arg.Kind,
		arg.PlayerUserID,
		arg.MasterUserID,
		arg.Status,
		arg.Name,
		arg.Sheet,
		arg.Story,
		arg.Now,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCharacterCreature = `-- name: InsertCharacterCreature :one

INSERT INTO character_creatures
    (campaign_id, character_id, monster_key, name, source, attack, summon_group_id, concentration_cast_id, hp_current, hp_max, created_at)
VALUES (
    $1::UUID, $2::UUID, $3, $4, $5,
    $6, $7::UUID, $8::UUID, $9, $10,
    $11
)
RETURNING id, campaign_id, character_id, monster_key, name, source, attack, summon_group_id, concentration_cast_id, hp_current, hp_max, created_at, dismissed_at, dismissed_reason
`

type InsertCharacterCreatureParams struct {
	CampaignID          string
	CharacterID         string
	MonsterKey          string
	Name                string
	Source              string
	Attack              string
	SummonGroupID       string
	ConcentrationCastID *string
	HpCurrent           int32
	HpMax               int32
	CreatedAt           time.Time
}

// A character's creatures (MR-037, Etapa 9). A creature is "live" until it is
// dismissed; a dismissed one is kept (dismissed_at, dismissed_reason) so an
// undo can bring it back.
func (q *Queries) InsertCharacterCreature(ctx context.Context, arg InsertCharacterCreatureParams) (CharacterCreature, error) {
	row := q.db.QueryRow(ctx, insertCharacterCreature,
		arg.CampaignID,
		arg.CharacterID,
		arg.MonsterKey,
		arg.Name,
		arg.Source,
		arg.Attack,
		arg.SummonGroupID,
		arg.ConcentrationCastID,
		arg.HpCurrent,
		arg.HpMax,
		arg.CreatedAt,
	)
	var i CharacterCreature
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.MonsterKey,
		&i.Name,
		&i.Source,
		&i.Attack,
		&i.SummonGroupID,
		&i.ConcentrationCastID,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.DismissedAt,
		&i.DismissedReason,
	)
	return i, err
}

const insertLevelUp = `-- name: InsertLevelUp :one
INSERT INTO character_level_ups
    (campaign_id, character_id, class_key, from_level, to_level, hp_method, hp_value, choices, created_at)
VALUES (
    $1::UUID, $2::UUID, $3, $4,
    $5, $6, $7, $8, $9
)
RETURNING id, campaign_id, character_id, class_key, from_level, to_level, hp_method, hp_value, choices, created_at
`

type InsertLevelUpParams struct {
	CampaignID  string
	CharacterID string
	ClassKey    string
	FromLevel   int32
	ToLevel     int32
	HpMethod    string
	HpValue     int32
	Choices     []byte
	CreatedAt   time.Time
}

// The record of a guided level-up (MR-040), written in the transaction that
// saves the sheet.
func (q *Queries) InsertLevelUp(ctx context.Context, arg InsertLevelUpParams) (CharacterLevelUp, error) {
	row := q.db.QueryRow(ctx, insertLevelUp,
		arg.CampaignID,
		arg.CharacterID,
		arg.ClassKey,
		arg.FromLevel,
		arg.ToLevel,
		arg.HpMethod,
		arg.HpValue,
		arg.Choices,
		arg.CreatedAt,
	)
	var i CharacterLevelUp
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CharacterID,
		&i.ClassKey,
		&i.FromLevel,
		&i.ToLevel,
		&i.HpMethod,
		&i.HpValue,
		&i.Choices,
		&i.CreatedAt,
	)
	return i, err
}

const insertLevelUpRoll = `-- name: InsertLevelUpRoll :execrows
INSERT INTO character_level_up_rolls (character_id, class_key, to_level, die, value, created_at)
VALUES ($1::UUID, $2, $3, $4, $5, $6)
ON CONFLICT (character_id, to_level) DO NOTHING
`

type InsertLevelUpRollParams struct {
	CharacterID string
	ClassKey    string
	ToLevel     int32
	Die         int32
	Value       int32
	Now         time.Time
}

// Keeps a roll. A second roll for the same level does nothing (0 rows), so the
// first one stands: asking again never rerolls.
func (q *Queries) InsertLevelUpRoll(ctx context.Context, arg InsertLevelUpRollParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLevelUpRoll,
		arg.CharacterID,
		arg.ClassKey,
		arg.ToLevel,
		arg.Die,
		arg.Value,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCharacterNames = `-- name: ListCharacterNames :many
SELECT id, name FROM characters
WHERE campaign_id = $1::UUID
  AND id = ANY($2::UUID[])
`

type ListCharacterNamesParams struct {
	CampaignID string
	Ids        []string
}

type ListCharacterNamesRow struct {
	ID   string
	Name string
}

// The names of the given characters of the campaign, whatever their kind or
// status (package progression names the characters of an award, even one that
// died since).
func (q *Queries) ListCharacterNames(ctx context.Context, arg ListCharacterNamesParams) ([]ListCharacterNamesRow, error) {
	rows, err := q.db.Query(ctx, listCharacterNames, arg.CampaignID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterNamesRow
	for rows.Next() {
		var i ListCharacterNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, kind, status, name, player_user_id, sheet, sheet_locked_at, created_at
FROM characters
WHERE campaign_id = $1::UUID
  AND (
      $2::UUID IS NULL
      OR (kind = 'player' AND player_user_id = $2::UUID)
  )
  AND ($3::TEXT IS NULL OR status = $3::TEXT)
ORDER BY kind <> 'player', created_at, id
`

type ListCharactersParams struct {
	CampaignID   string
	PlayerUserID *string
	Status       *string
}

type ListCharactersRow struct {
	ID            string
	Kind          string
	Status        string
	Name          string
	PlayerUserID  *string
	Sheet         []byte
	SheetLockedAt *time.Time
	CreatedAt     time.Time
}

// Without player_user_id, every character of the campaign (the master's
// list); with it, only that player's characters. With status, only the
// characters in that status (a pending member sees only their pending
// character, RN-15). Players' characters come first, then NPCs, each group
// oldest first. The story is left out: a list does not show it.
func (q *Queries) ListCharacters(ctx context.Context, arg ListCharactersParams) ([]ListCharactersRow, error) {
	rows, err := q.db.Query(ctx, listCharacters, arg.CampaignID, arg.PlayerUserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharactersRow
	for rows.Next() {
		var i ListCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Name,
			&i.PlayerUserID,
			&i.Sheet,
			&i.SheetLockedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatCharacters = `-- name: ListCombatCharacters :many
SELECT c.id, c.kind, c.name, c.player_user_id, c.sheet, ws.beast AS wild_shape_beast
FROM characters AS c
LEFT JOIN character_wild_shapes AS ws ON ws.character_id = c.id
WHERE c.campaign_id = $1::UUID
  AND c.id = ANY($2::UUID[])
  AND c.status = 'active'
ORDER BY c.created_at, c.id
`

type ListCombatCharactersParams struct {
	CampaignID string
	Ids        []string
}

type ListCombatCharactersRow struct {
	ID             string
	Kind           string
	Name           string
	PlayerUserID   *string
	Sheet          []byte
	WildShapeBeast *string
}

// Those of the given characters that may fight in a combat of the campaign:
// its living characters, players' and NPCs, oldest first (package play).
// The beast of a druid in Wild Shape comes along, as in ListCombatParty.
func (q *Queries) ListCombatCharacters(ctx context.Context, arg ListCombatCharactersParams) ([]ListCombatCharactersRow, error) {
	rows, err := q.db.Query(ctx, listCombatCharacters, arg.CampaignID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCombatCharactersRow
	for rows.Next() {
		var i ListCombatCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.PlayerUserID,
			&i.Sheet,
			&i.WildShapeBeast,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatParty = `-- name: ListCombatParty :many
SELECT c.id, c.kind, c.name, c.player_user_id, c.sheet, ws.beast AS wild_shape_beast
FROM characters AS c
LEFT JOIN character_wild_shapes AS ws ON ws.character_id = c.id
WHERE c.campaign_id = $1::UUID
  AND c.kind = 'player' AND c.status = 'active'
ORDER BY c.created_at, c.id
`

type ListCombatPartyRow struct {
	ID             string
	Kind           string
	Name           string
	PlayerUserID   *string
	Sheet          []byte
	WildShapeBeast *string
}

// The campaign's living, active player characters, oldest first: the party
// that fights (package play). The sheet comes along for the numbers a
// combatant starts with (initiative, speed).
// The beast of a druid in Wild Shape comes along (MR-037): the combatant starts
// with the beast's speed and size.
func (q *Queries) ListCombatParty(ctx context.Context, campaignID string) ([]ListCombatPartyRow, error) {
	rows, err := q.db.Query(ctx, listCombatParty, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCombatPartyRow
	for rows.Next() {
		var i ListCombatPartyRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.PlayerUserID,
			&i.Sheet,
			&i.WildShapeBeast,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreaturesByIDs = `-- name: ListCreaturesByIDs :many
SELECT cc.id, cc.campaign_id, cc.character_id, cc.monster_key, cc.name, cc.source, cc.attack, cc.summon_group_id, cc.concentration_cast_id, cc.hp_current, cc.hp_max, cc.created_at, cc.dismissed_at, cc.dismissed_reason, c.player_user_id
FROM character_creatures cc
JOIN characters c ON c.id = cc.character_id
WHERE cc.campaign_id = $1::UUID AND cc.id = ANY($2::UUID[])
ORDER BY cc.created_at, cc.id
`

type ListCreaturesByIDsParams struct {
	CampaignID string
	Ids        []string
}

type ListCreaturesByIDsRow struct {
	CharacterCreature CharacterCreature
	PlayerUserID      *string
}

// The creatures of the campaign with the given IDs, live or not.
func (q *Queries) ListCreaturesByIDs(ctx context.Context, arg ListCreaturesByIDsParams) ([]ListCreaturesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listCreaturesByIDs, arg.CampaignID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreaturesByIDsRow
	for rows.Next() {
		var i ListCreaturesByIDsRow
		if err := rows.Scan(
			&i.CharacterCreature.ID,
			&i.CharacterCreature.CampaignID,
			&i.CharacterCreature.CharacterID,
			&i.CharacterCreature.MonsterKey,
			&i.CharacterCreature.Name,
			&i.CharacterCreature.Source,
			&i.CharacterCreature.Attack,
			&i.CharacterCreature.SummonGroupID,
			&i.CharacterCreature.ConcentrationCastID,
			&i.CharacterCreature.HpCurrent,
			&i.CharacterCreature.HpMax,
			&i.CharacterCreature.CreatedAt,
			&i.CharacterCreature.DismissedAt,
			&i.CharacterCreature.DismissedReason,
			&i.PlayerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLevelUps = `-- name: ListLevelUps :many
SELECT l.id, l.character_id, l.class_key, l.from_level, l.to_level, l.choices, l.created_at,
       c.name AS character_name, c.player_user_id
FROM character_level_ups l
JOIN characters c ON c.id = l.character_id
WHERE l.campaign_id = $1::UUID
  AND ($2::UUID IS NULL OR l.character_id = $2::UUID)
  AND ($3::TIMESTAMPTZ IS NULL
       OR (l.created_at, l.id) < ($3::TIMESTAMPTZ, $4::UUID))
ORDER BY l.created_at DESC, l.id DESC
LIMIT $5
`

type ListLevelUpsParams struct {
	CampaignID      string
	CharacterID     *string
	BeforeCreatedAt *time.Time
	BeforeID        *string
	MaxRows         int32
}

type ListLevelUpsRow struct {
	ID            string
	CharacterID   string
	ClassKey      string
	FromLevel     int32
	ToLevel       int32
	Choices       []byte
	CreatedAt     time.Time
	CharacterName string
	PlayerUserID  *string
}

// A campaign's level-ups, newest first, for the master's "O que mudou". With
// character_id, only that character's. The character's name is the current
// one, and its player the character's own.
func (q *Queries) ListLevelUps(ctx context.Context, arg ListLevelUpsParams) ([]ListLevelUpsRow, error) {
	rows, err := q.db.Query(ctx, listLevelUps,
		arg.CampaignID,
		arg.CharacterID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLevelUpsRow
	for rows.Next() {
		var i ListLevelUpsRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.ClassKey,
			&i.FromLevel,
			&i.ToLevel,
			&i.Choices,
			&i.CreatedAt,
			&i.CharacterName,
			&i.PlayerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCreaturesOfCharacters = `-- name: ListLiveCreaturesOfCharacters :many
SELECT cc.id, cc.campaign_id, cc.character_id, cc.monster_key, cc.name, cc.source, cc.attack, cc.summon_group_id, cc.concentration_cast_id, cc.hp_current, cc.hp_max, cc.created_at, cc.dismissed_at, cc.dismissed_reason, c.player_user_id
FROM character_creatures cc
JOIN characters c ON c.id = cc.character_id
WHERE cc.campaign_id = $1::UUID
  AND cc.character_id = ANY($2::UUID[])
  AND cc.dismissed_at IS NULL
ORDER BY cc.created_at, cc.id
`

type ListLiveCreaturesOfCharactersParams struct {
	CampaignID   string
	CharacterIds []string
}

type ListLiveCreaturesOfCharactersRow struct {
	CharacterCreature CharacterCreature
	PlayerUserID      *string
}

// The live creatures of the given characters of the campaign, oldest first.
func (q *Queries) ListLiveCreaturesOfCharacters(ctx context.Context, arg ListLiveCreaturesOfCharactersParams) ([]ListLiveCreaturesOfCharactersRow, error) {
	rows, err := q.db.Query(ctx, listLiveCreaturesOfCharacters, arg.CampaignID, arg.CharacterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveCreaturesOfCharactersRow
	for rows.Next() {
		var i ListLiveCreaturesOfCharactersRow
		if err := rows.Scan(
			&i.CharacterCreature.ID,
			&i.CharacterCreature.CampaignID,
			&i.CharacterCreature.CharacterID,
			&i.CharacterCreature.MonsterKey,
			&i.CharacterCreature.Name,
			&i.CharacterCreature.Source,
			&i.CharacterCreature.Attack,
			&i.CharacterCreature.SummonGroupID,
			&i.CharacterCreature.ConcentrationCastID,
			&i.CharacterCreature.HpCurrent,
			&i.CharacterCreature.HpMax,
			&i.CharacterCreature.CreatedAt,
			&i.CharacterCreature.DismissedAt,
			&i.CharacterCreature.DismissedReason,
			&i.PlayerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCreaturesOnConcentration = `-- name: ListLiveCreaturesOnConcentration :many
SELECT cc.id, cc.campaign_id, cc.character_id, cc.monster_key, cc.name, cc.source, cc.attack, cc.summon_group_id, cc.concentration_cast_id, cc.hp_current, cc.hp_max, cc.created_at, cc.dismissed_at, cc.dismissed_reason, c.player_user_id
FROM character_creatures cc
JOIN characters c ON c.id = cc.character_id
WHERE cc.campaign_id = $1::UUID
  AND cc.character_id = $2::UUID
  AND cc.concentration_cast_id IS NOT NULL
  AND cc.dismissed_at IS NULL
ORDER BY cc.created_at, cc.id
`

type ListLiveCreaturesOnConcentrationParams struct {
	CampaignID  string
	CharacterID string
}

type ListLiveCreaturesOnConcentrationRow struct {
	CharacterCreature CharacterCreature
	PlayerUserID      *string
}

// The live creatures of the character that last only while it concentrates.
func (q *Queries) ListLiveCreaturesOnConcentration(ctx context.Context, arg ListLiveCreaturesOnConcentrationParams) ([]ListLiveCreaturesOnConcentrationRow, error) {
	rows, err := q.db.Query(ctx, listLiveCreaturesOnConcentration, arg.CampaignID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveCreaturesOnConcentrationRow
	for rows.Next() {
		var i ListLiveCreaturesOnConcentrationRow
		if err := rows.Scan(
			&i.CharacterCreature.ID,
			&i.CharacterCreature.CampaignID,
			&i.CharacterCreature.CharacterID,
			&i.CharacterCreature.MonsterKey,
			&i.CharacterCreature.Name,
			&i.CharacterCreature.Source,
			&i.CharacterCreature.Attack,
			&i.CharacterCreature.SummonGroupID,
			&i.CharacterCreature.ConcentrationCastID,
			&i.CharacterCreature.HpCurrent,
			&i.CharacterCreature.HpMax,
			&i.CharacterCreature.CreatedAt,
			&i.CharacterCreature.DismissedAt,
			&i.CharacterCreature.DismissedReason,
			&i.PlayerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveFamiliars = `-- name: ListLiveFamiliars :many
SELECT cc.id, cc.campaign_id, cc.character_id, cc.monster_key, cc.name, cc.source, cc.attack, cc.summon_group_id, cc.concentration_cast_id, cc.hp_current, cc.hp_max, cc.created_at, cc.dismissed_at, cc.dismissed_reason, c.player_user_id
FROM character_creatures cc
JOIN characters c ON c.id = cc.character_id
WHERE cc.campaign_id = $1::UUID
  AND cc.character_id = $2::UUID
  AND cc.source = 'familiar'
  AND cc.dismissed_at IS NULL
ORDER BY cc.created_at, cc.id
`

type ListLiveFamiliarsParams struct {
	CampaignID  string
	CharacterID string
}

type ListLiveFamiliarsRow struct {
	CharacterCreature CharacterCreature
	PlayerUserID      *string
}

// The character's live familiars: one at a time (the SRD), so a new one
// dismisses these.
func (q *Queries) ListLiveFamiliars(ctx context.Context, arg ListLiveFamiliarsParams) ([]ListLiveFamiliarsRow, error) {
	rows, err := q.db.Query(ctx, listLiveFamiliars, arg.CampaignID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveFamiliarsRow
	for rows.Next() {
		var i ListLiveFamiliarsRow
		if err := rows.Scan(
			&i.CharacterCreature.ID,
			&i.CharacterCreature.CampaignID,
			&i.CharacterCreature.CharacterID,
			&i.CharacterCreature.MonsterKey,
			&i.CharacterCreature.Name,
			&i.CharacterCreature.Source,
			&i.CharacterCreature.Attack,
			&i.CharacterCreature.SummonGroupID,
			&i.CharacterCreature.ConcentrationCastID,
			&i.CharacterCreature.HpCurrent,
			&i.CharacterCreature.HpMax,
			&i.CharacterCreature.CreatedAt,
			&i.CharacterCreature.DismissedAt,
			&i.CharacterCreature.DismissedReason,
			&i.PlayerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapCharacters = `-- name: ListMapCharacters :many
SELECT id, kind, name, player_user_id FROM characters
WHERE campaign_id = $1::UUID
  AND id = ANY($2::UUID[])
  AND status = 'active'
ORDER BY kind <> 'player', created_at, id
`

type ListMapCharactersParams struct {
	CampaignID string
	Ids        []string
}

type ListMapCharactersRow struct {
	ID           string
	Kind         string
	Name         string
	PlayerUserID *string
}

// Those of the given characters that may stand on a map of the campaign as
// tokens (package maps): its living characters, the players' (active: not
// dead, not waiting for approval) and the NPCs. Players' characters first,
// then NPCs, each group oldest first, as ListCharacters. No sheet, no story.
func (q *Queries) ListMapCharacters(ctx context.Context, arg ListMapCharactersParams) ([]ListMapCharactersRow, error) {
	rows, err := q.db.Query(ctx, listMapCharacters, arg.CampaignID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapCharactersRow
	for rows.Next() {
		var i ListMapCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.PlayerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapCreatures = `-- name: ListMapCreatures :many
SELECT cc.id, cc.character_id, cc.name, cc.monster_key, c.player_user_id
FROM character_creatures AS cc
JOIN characters AS c ON c.id = cc.character_id
WHERE cc.campaign_id = $1::UUID
  AND cc.id = ANY($2::UUID[])
  AND cc.dismissed_at IS NULL
  AND c.status = 'active'
ORDER BY cc.created_at, cc.id
`

type ListMapCreaturesParams struct {
	CampaignID string
	Ids        []string
}

type ListMapCreaturesRow struct {
	ID           string
	CharacterID  string
	Name         string
	MonsterKey   string
	PlayerUserID *string
}

// The live creatures of the given IDs that belong to a living player's character
// of the campaign: the ones that may have a token on a map (package maps). Oldest
// first.
func (q *Queries) ListMapCreatures(ctx context.Context, arg ListMapCreaturesParams) ([]ListMapCreaturesRow, error) {
	rows, err := q.db.Query(ctx, listMapCreatures, arg.CampaignID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapCreaturesRow
	for rows.Next() {
		var i ListMapCreaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.Name,
			&i.MonsterKey,
			&i.PlayerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartyVision = `-- name: ListPartyVision :many
SELECT c.id, c.player_user_id, c.sheet, ws.beast AS wild_shape_beast,
       cc.id AS familiar_id, cc.monster_key AS familiar_monster_key
FROM characters AS c
LEFT JOIN character_wild_shapes AS ws ON ws.character_id = c.id
LEFT JOIN character_vitals AS v ON v.character_id = c.id
LEFT JOIN character_creatures AS cc ON cc.id = v.familiar_sight_creature_id AND cc.dismissed_at IS NULL
WHERE c.campaign_id = $1::UUID
  AND c.kind = 'player' AND c.status = 'active'
ORDER BY c.created_at, c.id
`

type ListPartyVisionRow struct {
	ID                 string
	PlayerUserID       *string
	Sheet              []byte
	WildShapeBeast     *string
	FamiliarID         *string
	FamiliarMonsterKey *string
}

// The campaign's living, active player characters, oldest first, with what the
// fog needs to know of how each one sees (package maps): the sheet, the beast of
// a Wild Shape form, and the familiar the player looks through, if it is still with
// the character (MR-036, MR-037).
func (q *Queries) ListPartyVision(ctx context.Context, campaignID string) ([]ListPartyVisionRow, error) {
	rows, err := q.db.Query(ctx, listPartyVision, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartyVisionRow
	for rows.Next() {
		var i ListPartyVisionRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerUserID,
			&i.Sheet,
			&i.WildShapeBeast,
			&i.FamiliarID,
			&i.FamiliarMonsterKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCharacters = `-- name: ListSessionCharacters :many
SELECT id, kind, name, player_user_id FROM characters
WHERE campaign_id = $1::UUID
  AND id = ANY($2::UUID[])
`

type ListSessionCharactersParams struct {
	CampaignID string
	Ids        []string
}

type ListSessionCharactersRow struct {
	ID           string
	Kind         string
	Name         string
	PlayerUserID *string
}

// Those of the given characters of the campaign, whatever their status: the
// session summary names a character that died or left during the session
// (package play).
func (q *Queries) ListSessionCharacters(ctx context.Context, arg ListSessionCharactersParams) ([]ListSessionCharactersRow, error) {
	rows, err := q.db.Query(ctx, listSessionCharacters, arg.CampaignID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionCharactersRow
	for rows.Next() {
		var i ListSessionCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.PlayerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVitals = `-- name: ListVitals :many
SELECT c.id, c.name, c.player_user_id, c.sheet,
       v.hit_points_current, v.hit_points_temporary, v.spell_slots_used,
       v.pact_slots_used, v.hit_dice_used, v.resources_used, v.revision, v.updated_at,
       ws.beast AS wild_shape_beast, ws.hp AS wild_shape_hp, v.familiar_sight_creature_id, v.familiar_sight_in_combat,
       v.familiar_sight_conditions
FROM characters AS c
LEFT JOIN character_vitals AS v ON v.character_id = c.id
LEFT JOIN character_wild_shapes AS ws ON ws.character_id = c.id
WHERE c.campaign_id = $1::UUID
  AND c.kind = 'player' AND c.status = 'active'
ORDER BY c.created_at, c.id
`

type ListVitalsRow struct {
	ID                      string
	Name                    string
	PlayerUserID            *string
	Sheet                   []byte
	HitPointsCurrent        *int32
	HitPointsTemporary      *int32
	SpellSlotsUsed          []int32
	PactSlotsUsed           *int32
	HitDiceUsed             *int32
	ResourcesUsed           []byte
	Revision                *int32
	UpdatedAt               *time.Time
	WildShapeBeast          *string
	WildShapeHp             *int32
	FamiliarSightCreatureID *string
	FamiliarSightInCombat   *bool
	FamiliarSightConditions []string
}

// The vitals of the campaign's living, active player characters (RN-02),
// oldest first: the party at the table. A character without a
// character_vitals row has fresh vitals, so the columns from it may be NULL.
// The sheet comes along because the maximums are derived from it. The Wild Shape
// form and the familiar's sight come along too (MR-037, MR-036).
func (q *Queries) ListVitals(ctx context.Context, campaignID string) ([]ListVitalsRow, error) {
	rows, err := q.db.Query(ctx, listVitals, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVitalsRow
	for rows.Next() {
		var i ListVitalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlayerUserID,
			&i.Sheet,
			&i.HitPointsCurrent,
			&i.HitPointsTemporary,
			&i.SpellSlotsUsed,
			&i.PactSlotsUsed,
			&i.HitDiceUsed,
			&i.ResourcesUsed,
			&i.Revision,
			&i.UpdatedAt,
			&i.WildShapeBeast,
			&i.WildShapeHp,
			&i.FamiliarSightCreatureID,
			&i.FamiliarSightInCombat,
			&i.FamiliarSightConditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSheets = `-- name: LockSheets :execrows
UPDATE characters
SET sheet_locked_at = $1::TIMESTAMPTZ
WHERE campaign_id = $2::UUID
  AND kind = 'player' AND status = 'active' AND sheet_locked_at IS NULL
`

type LockSheetsParams struct {
	Now        time.Time
	CampaignID string
}

// RN-01: when a game session starts, the sheets of the campaign's living
// player characters that are still drafts lock. A character waiting for
// approval (MR-024) does not lock yet, and NPCs never lock.
func (q *Queries) LockSheets(ctx context.Context, arg LockSheetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockSheets, arg.Now, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCharacterDead = `-- name: MarkCharacterDead :one
UPDATE characters
SET status = 'dead', died_at = COALESCE(died_at, $1::TIMESTAMPTZ)
WHERE campaign_id = $2::UUID AND id = $3
RETURNING id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at
`

type MarkCharacterDeadParams struct {
	Now        time.Time
	CampaignID string
	ID         string
}

// Marking a dead character again keeps the first died_at, so the call is
// idempotent. It changes neither the revision nor updated_at.
func (q *Queries) MarkCharacterDead(ctx context.Context, arg MarkCharacterDeadParams) (Character, error) {
	row := q.db.QueryRow(ctx, markCharacterDead, arg.Now, arg.CampaignID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const portraitInUse = `-- name: PortraitInUse :one
SELECT EXISTS (
    SELECT 1 FROM characters
    WHERE campaign_id = $1::UUID
      AND (sheet -> 'full' ->> 'portrait_image_id' = $2::TEXT
           OR sheet -> 'basic' ->> 'portrait_image_id' = $2::TEXT)
)
`

type PortraitInUseParams struct {
	CampaignID string
	ImageID    string
}

// Whether any NPC of the campaign has the gallery image as its portrait (the
// maps module copies a fog map's image when something else uses it, MR-036).
func (q *Queries) PortraitInUse(ctx context.Context, arg PortraitInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, portraitInUse, arg.CampaignID, arg.ImageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reviveCreatures = `-- name: ReviveCreatures :many
UPDATE character_creatures
SET dismissed_at = NULL, dismissed_reason = NULL
WHERE campaign_id = $1::UUID
  AND id = ANY($2::UUID[])
  AND dismissed_reason = $3::TEXT
RETURNING id
`

type ReviveCreaturesParams struct {
	CampaignID string
	Ids        []string
	Reason     string
}

// Brings back the creatures dismissed for this reason (an undo): the ones
// defeated that an undo healed, the ones a master's undo of a casting or of the
// end of a concentration gives back. Returns the ones it revived.
func (q *Queries) ReviveCreatures(ctx context.Context, arg ReviveCreaturesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, reviveCreatures, arg.CampaignID, arg.Ids, arg.Reason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCharacterCreatureHitPoints = `-- name: SetCharacterCreatureHitPoints :exec
UPDATE character_creatures SET hp_current = $1
WHERE campaign_id = $2::UUID AND id = $3::UUID
`

type SetCharacterCreatureHitPointsParams struct {
	HpCurrent  int32
	CampaignID string
	ID         string
}

// The creature's hit points: the master's correction, or a combat's write-back.
func (q *Queries) SetCharacterCreatureHitPoints(ctx context.Context, arg SetCharacterCreatureHitPointsParams) error {
	_, err := q.db.Exec(ctx, setCharacterCreatureHitPoints, arg.HpCurrent, arg.CampaignID, arg.ID)
	return err
}

const setCharacterCreatureName = `-- name: SetCharacterCreatureName :exec
UPDATE character_creatures SET name = $1
WHERE campaign_id = $2::UUID AND id = $3::UUID
`

type SetCharacterCreatureNameParams struct {
	Name       string
	CampaignID string
	ID         string
}

func (q *Queries) SetCharacterCreatureName(ctx context.Context, arg SetCharacterCreatureNameParams) error {
	_, err := q.db.Exec(ctx, setCharacterCreatureName, arg.Name, arg.CampaignID, arg.ID)
	return err
}

const setFamiliarSight = `-- name: SetFamiliarSight :one
INSERT INTO character_vitals (character_id, hit_points_current, familiar_sight_creature_id, familiar_sight_in_combat, familiar_sight_conditions, revision, updated_at)
VALUES ($1, $2, $3, $4, $5::TEXT[], 1, $6)
ON CONFLICT (character_id) DO UPDATE SET
    familiar_sight_creature_id = excluded.familiar_sight_creature_id,
    familiar_sight_in_combat = excluded.familiar_sight_in_combat,
    familiar_sight_conditions = excluded.familiar_sight_conditions,
    revision = character_vitals.revision + 1,
    updated_at = excluded.updated_at
RETURNING revision, updated_at
`

type SetFamiliarSightParams struct {
	CharacterID      string
	HitPointsCurrent int32
	CreatureID       *string
	InCombat         bool
	Conditions       []string
	Now              time.Time
}

type SetFamiliarSightRow struct {
	Revision  int32
	UpdatedAt time.Time
}

// "Ver pelos olhos do familiar" (MR-036): the familiar the player looks through
// (NULL for none), whether it started in a combat and the conditions it gave the
// combatant. The first write creates the vitals row, as TouchVitals does.
func (q *Queries) SetFamiliarSight(ctx context.Context, arg SetFamiliarSightParams) (SetFamiliarSightRow, error) {
	row := q.db.QueryRow(ctx, setFamiliarSight,
		arg.CharacterID,
		arg.HitPointsCurrent,
		arg.CreatureID,
		arg.InCombat,
		arg.Conditions,
		arg.Now,
	)
	var i SetFamiliarSightRow
	err := row.Scan(&i.Revision, &i.UpdatedAt)
	return i, err
}

const setStoryEditing = `-- name: SetStoryEditing :one
UPDATE characters
SET story_editing_allowed = $1
WHERE campaign_id = $2::UUID AND id = $3
RETURNING id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at
`

type SetStoryEditingParams struct {
	Allowed    bool
	CampaignID string
	ID         string
}

// The master's permission for the player to edit the story. It changes
// neither the revision nor updated_at, which follow the content.
func (q *Queries) SetStoryEditing(ctx context.Context, arg SetStoryEditingParams) (Character, error) {
	row := q.db.QueryRow(ctx, setStoryEditing, arg.Allowed, arg.CampaignID, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setWildShape = `-- name: SetWildShape :exec
INSERT INTO character_wild_shapes (character_id, beast, hp, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (character_id) DO UPDATE SET beast = excluded.beast, hp = excluded.hp, updated_at = excluded.updated_at
`

type SetWildShapeParams struct {
	CharacterID string
	Beast       string
	Hp          int32
	Now         time.Time
}

// A druid's Wild Shape form (MR-037): the beast and its current hit points
// (1 or more). The caller also bumps the vitals' revision (TouchVitals).
func (q *Queries) SetWildShape(ctx context.Context, arg SetWildShapeParams) error {
	_, err := q.db.Exec(ctx, setWildShape,
		arg.CharacterID,
		arg.Beast,
		arg.Hp,
		arg.Now,
	)
	return err
}

const touchVitals = `-- name: TouchVitals :one
INSERT INTO character_vitals (character_id, hit_points_current, revision, updated_at)
VALUES ($1, $2, 1, $3)
ON CONFLICT (character_id) DO UPDATE SET
    revision = character_vitals.revision + 1,
    updated_at = excluded.updated_at
RETURNING revision, updated_at
`

type TouchVitalsParams struct {
	CharacterID      string
	HitPointsCurrent int32
	Now              time.Time
}

type TouchVitalsRow struct {
	Revision  int32
	UpdatedAt time.Time
}

// Bumps a character's vitals revision for a change made on a table of its own (the
// Wild Shape form): the first write creates the vitals row, as UpsertVitals does
// (hit_points_current is only for that insert).
func (q *Queries) TouchVitals(ctx context.Context, arg TouchVitalsParams) (TouchVitalsRow, error) {
	row := q.db.QueryRow(ctx, touchVitals, arg.CharacterID, arg.HitPointsCurrent, arg.Now)
	var i TouchVitalsRow
	err := row.Scan(&i.Revision, &i.UpdatedAt)
	return i, err
}

const updateCharacterSheet = `-- name: UpdateCharacterSheet :one
UPDATE characters
SET name = $1, sheet = $2, revision = revision + 1, updated_at = $3
WHERE campaign_id = $4::UUID AND id = $5 AND revision = $6
RETURNING id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at
`

type UpdateCharacterSheetParams struct {
	Name       string
	Sheet      []byte
	Now        time.Time
	CampaignID string
	ID         string
	Revision   int32
}

// revision in the WHERE clause is a second guard: the handler already
// compared it under FOR UPDATE, so no row here means a stale revision.
func (q *Queries) UpdateCharacterSheet(ctx context.Context, arg UpdateCharacterSheetParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterSheet,
		arg.Name,
		arg.Sheet,
		arg.Now,
		arg.CampaignID,
		arg.ID,
		arg.Revision,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterStory = `-- name: UpdateCharacterStory :one
UPDATE characters
SET story = $1, revision = revision + 1, updated_at = $2
WHERE campaign_id = $3::UUID AND id = $4 AND revision = $5
RETURNING id, campaign_id, kind, player_user_id, master_user_id, status, name, sheet, story, story_editing_allowed, sheet_schema, revision, sheet_locked_at, died_at, created_at, updated_at
`

type UpdateCharacterStoryParams struct {
	Story      []byte
	Now        time.Time
	CampaignID string
	ID         string
	Revision   int32
}

// As UpdateCharacterSheet: the story and the sheet share one revision.
func (q *Queries) UpdateCharacterStory(ctx context.Context, arg UpdateCharacterStoryParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacterStory,
		arg.Story,
		arg.Now,
		arg.CampaignID,
		arg.ID,
		arg.Revision,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Kind,
		&i.PlayerUserID,
		&i.MasterUserID,
		&i.Status,
		&i.Name,
		&i.Sheet,
		&i.Story,
		&i.StoryEditingAllowed,
		&i.SheetSchema,
		&i.Revision,
		&i.SheetLockedAt,
		&i.DiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMasterNotes = `-- name: UpsertMasterNotes :one
INSERT INTO character_master_notes (campaign_id, character_id, notes, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id, character_id)
DO UPDATE SET notes = excluded.notes, updated_at = excluded.updated_at
RETURNING notes, updated_at
`

type UpsertMasterNotesParams struct {
	CampaignID  string
	CharacterID string
	Notes       string
	UpdatedAt   time.Time
}

type UpsertMasterNotesRow struct {
	Notes     string
	UpdatedAt time.Time
}

func (q *Queries) UpsertMasterNotes(ctx context.Context, arg UpsertMasterNotesParams) (UpsertMasterNotesRow, error) {
	row := q.db.QueryRow(ctx, upsertMasterNotes,
		arg.CampaignID,
		arg.CharacterID,
		arg.Notes,
		arg.UpdatedAt,
	)
	var i UpsertMasterNotesRow
	err := row.Scan(&i.Notes, &i.UpdatedAt)
	return i, err
}

const upsertVitals = `-- name: UpsertVitals :one
INSERT INTO character_vitals
    (character_id, hit_points_current, hit_points_temporary, spell_slots_used,
     pact_slots_used, hit_dice_used, resources_used, revision, updated_at)
VALUES (
    $1, $2, $3,
    $4::INT4[], $5, $6,
    $7::JSONB, 1, $8
)
ON CONFLICT (character_id) DO UPDATE SET
    hit_points_current = excluded.hit_points_current,
    hit_points_temporary = excluded.hit_points_temporary,
    spell_slots_used = excluded.spell_slots_used,
    pact_slots_used = excluded.pact_slots_used,
    hit_dice_used = excluded.hit_dice_used,
    resources_used = excluded.resources_used,
    revision = character_vitals.revision + 1,
    updated_at = excluded.updated_at
RETURNING revision, updated_at
`

type UpsertVitalsParams struct {
	CharacterID        string
	HitPointsCurrent   int32
	HitPointsTemporary int32
	SpellSlotsUsed     []int32
	PactSlotsUsed      int32
	HitDiceUsed        int32
	ResourcesUsed      []byte
	Now                time.Time
}

type UpsertVitalsRow struct {
	Revision  int32
	UpdatedAt time.Time
}

// Saves a character's vitals: the first save creates the row with revision
// 1, and every later one adds 1.
func (q *Queries) UpsertVitals(ctx context.Context, arg UpsertVitalsParams) (UpsertVitalsRow, error) {
	row := q.db.QueryRow(ctx, upsertVitals,
		arg.CharacterID,
		arg.HitPointsCurrent,
		arg.HitPointsTemporary,
		arg.SpellSlotsUsed,
		arg.PactSlotsUsed,
		arg.HitDiceUsed,
		arg.ResourcesUsed,
		arg.Now,
	)
	var i UpsertVitalsRow
	err := row.Scan(&i.Revision, &i.UpdatedAt)
	return i, err
}
