// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitydb

import (
	"context"
	"time"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM auth_sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getDisplayName = `-- name: GetDisplayName :one
SELECT display_name FROM users WHERE id = $1
`

func (q *Queries) GetDisplayName(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getDisplayName, id)
	var display_name *string
	err := row.Scan(&display_name)
	return display_name, err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO user_identities (issuer, subject, user_id, email)
VALUES ($1, $2, $3, $4)
`

type InsertIdentityParams struct {
	Issuer  string
	Subject string
	UserID  string
	Email   *string
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.Exec(ctx, insertIdentity,
		arg.Issuer,
		arg.Subject,
		arg.UserID,
		arg.Email,
	)
	return err
}

const insertLoginState = `-- name: InsertLoginState :exec
INSERT INTO oidc_login_states
    (state_hash, code_verifier, nonce, return_to, created_at, expires_at, intent_kind, intent_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLoginStateParams struct {
	StateHash    []byte
	CodeVerifier string
	Nonce        string
	ReturnTo     string
	CreatedAt    time.Time
	ExpiresAt    time.Time
	IntentKind   *string
	IntentData   []byte
}

func (q *Queries) InsertLoginState(ctx context.Context, arg InsertLoginStateParams) error {
	_, err := q.db.Exec(ctx, insertLoginState,
		arg.StateHash,
		arg.CodeVerifier,
		arg.Nonce,
		arg.ReturnTo,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.IntentKind,
		arg.IntentData,
	)
	return err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO auth_sessions (token_hash, user_id, created_at, expires_at, auth_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertSessionParams struct {
	TokenHash []byte
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
	AuthTime  *time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.AuthTime,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users DEFAULT VALUES RETURNING id
`

func (q *Queries) InsertUser(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, insertUser)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listDisplayNames = `-- name: ListDisplayNames :many
SELECT id, display_name::TEXT AS display_name
FROM users
WHERE id = ANY($1::UUID[]) AND display_name IS NOT NULL
`

type ListDisplayNamesRow struct {
	ID          string
	DisplayName string
}

// Users without a display name are left out.
func (q *Queries) ListDisplayNames(ctx context.Context, ids []string) ([]ListDisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, listDisplayNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisplayNamesRow
	for rows.Next() {
		var i ListDisplayNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupSession = `-- name: LookupSession :one
SELECT id, user_id, created_at, expires_at
FROM auth_sessions
WHERE token_hash = $1 AND expires_at > $2
`

type LookupSessionParams struct {
	TokenHash []byte
	Now       time.Time
}

type LookupSessionRow struct {
	ID        string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) LookupSession(ctx context.Context, arg LookupSessionParams) (LookupSessionRow, error) {
	row := q.db.QueryRow(ctx, lookupSession, arg.TokenHash, arg.Now)
	var i LookupSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setDisplayName = `-- name: SetDisplayName :execrows
UPDATE users SET display_name = $2 WHERE id = $1
`

type SetDisplayNameParams struct {
	ID          string
	DisplayName *string
}

func (q *Queries) SetDisplayName(ctx context.Context, arg SetDisplayNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDisplayName, arg.ID, arg.DisplayName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeLoginState = `-- name: TakeLoginState :one
DELETE FROM oidc_login_states
WHERE state_hash = $1
RETURNING code_verifier, nonce, return_to, created_at, expires_at, intent_kind, intent_data
`

type TakeLoginStateRow struct {
	CodeVerifier string
	Nonce        string
	ReturnTo     string
	CreatedAt    time.Time
	ExpiresAt    time.Time
	IntentKind   *string
	IntentData   []byte
}

// Reads and deletes in one statement, so two callbacks racing with the same
// state cannot both get it.
func (q *Queries) TakeLoginState(ctx context.Context, stateHash []byte) (TakeLoginStateRow, error) {
	row := q.db.QueryRow(ctx, takeLoginState, stateHash)
	var i TakeLoginStateRow
	err := row.Scan(
		&i.CodeVerifier,
		&i.Nonce,
		&i.ReturnTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IntentKind,
		&i.IntentData,
	)
	return i, err
}

const updateIdentityEmail = `-- name: UpdateIdentityEmail :one
UPDATE user_identities SET email = $3
WHERE issuer = $1 AND subject = $2
RETURNING user_id
`

type UpdateIdentityEmailParams struct {
	Issuer  string
	Subject string
	Email   *string
}

func (q *Queries) UpdateIdentityEmail(ctx context.Context, arg UpdateIdentityEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, updateIdentityEmail, arg.Issuer, arg.Subject, arg.Email)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
