// @ts-check
// ESLint flat config for the Angular app. Run it with `npm run lint`.
//
// The gate is a ratchet: violations that already existed when the lint was introduced are listed in
// eslint-suppressions.json, so the lint starts green and fails on any NEW violation. Never grow that file;
// fix a suppressed spot when you touch it and run `npx eslint --prune-suppressions` (see CONTRIBUTING).
const eslint = require('@eslint/js');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

module.exports = tseslint.config(
  // Generated by `make proto` and the build output: never linted.
  { ignores: ['src/gen/**', 'dist/**', 'coverage/**', '.angular/**', 'out-tsc/**'] },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommended,
      ...angular.configs.tsRecommended,
    ],
    languageOptions: {
      parserOptions: {
        // Type-aware rules (no-floating-promises & co.) need the TypeScript program of each file.
        project: ['./tsconfig.app.json', './tsconfig.spec.json'],
      },
    },
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'app', style: 'camelCase' },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'app', style: 'kebab-case' },
      ],
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',
      '@angular-eslint/prefer-standalone': 'error',
      '@angular-eslint/prefer-inject': 'error',
      // A forgotten await or a promise handed to a callback that ignores it fails silently.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      // Keep functions small enough to read and test.
      complexity: ['error', 15],
      // A leading underscore marks a parameter or variable that is unused on purpose (test fakes
      // that must match a signature, the unused half of a destructuring).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
        },
      ],
      // The UI is Portuguese and uses non-breaking spaces on purpose (before units, in "1 / 2"), in strings,
      // templates, comments and regular expressions. Only an invisible character loose in code is a bug.
      'no-irregular-whitespace': [
        'error',
        { skipStrings: true, skipTemplates: true, skipComments: true, skipRegExps: true },
      ],
      'max-depth': ['error', 4],
    },
  },
  {
    // A bare number in app code needs a name: a `const` whose name (and comment) says what it is. The common
    // neutral values are allowed (-1, 0, 1, 2, the radix 10, 100 for percentages, 1000 for milliseconds), and so are
    // default values, enum members, readonly fields and array indexes. Specs are exempt: their numbers are the data.
    files: ['src/app/**/*.ts'],
    ignores: ['**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-magic-numbers': [
        'error',
        {
          ignore: [-1, 0, 1, 2, 10, 100, 1000],
          ignoreArrayIndexes: true,
          ignoreDefaultValues: true,
          ignoreClassFieldInitialValues: true,
          ignoreEnums: true,
          ignoreNumericLiteralTypes: true,
          ignoreReadonlyClassProperties: true,
          ignoreTypeIndexes: true,
        },
      ],
    },
  },
  {
    files: ['**/*.html'],
    extends: [...angular.configs.templateRecommended, ...angular.configs.templateAccessibility],
    rules: {},
  },
);
